apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: heimdall-tls
  namespace: heimdall
spec:
  secretName: heimdall-tls
  additionalOutputFormats:
    - type: CombinedPEM
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  duration: 720h # 30d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - heimdall
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - "server auth"
  dnsNames:
    - heimdall
    - heimdall.heimdall
    - heimdall.heimdall.svc
    - heimdall.heimdall.svc.cluster.local

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: heimdall-jwt
  namespace: heimdall
spec:
  secretName: heimdall-jwt
  additionalOutputFormats:
    - type: CombinedPEM
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  duration: 720h # 30d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - heimdall
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - "digital signature"
  dnsNames:
    - heimdall