---
title: "HAProxy Integration"
date: 2023-08-08T07:32:14+02:00
draft: false
weight: 28
menu:
  docs:
    parent: "Integration Guides"
  main:
    parent: guides
description: Explains how to integrate heimdall with HAProxy, a popular open source, fast, and reliable solution providing load balancer and reverse proxy features.
---

https://www.haproxy.com/[HAProxy] (High Availability Proxy) is a popular open source, fast, and reliable solution providing load balancer and reverse proxy features for TCP- and HTTP-based applications, capable handling heavy load traffic and rerouting requests seamlessly across multiple workloads (e.g. web, application, database).

HAProxy is highly extensible thanks to Lua scripting support. For that reason the vanilla HAProxy does not implement any means of external authorization support and requires custom Lua code to achieve integration with heimdall.

The https://haproxy-ingress.github.io/[HAProxy Ingress Controller] has the required https://haproxy-ingress.github.io/docs/configuration/keys/#auth-external[integration options] however in place. That way, delegation of authentication and authorization to heimdall operated in link:{{< relref "/docs/introduction/core_concepts.adoc#_decision_mode" >}}[Decision Mode] is easily possible using the Ingress rule annotations, which you can see below. Alternatively, configuring the HAProxy Ingress Controller https://haproxy-ingress.github.io/docs/configuration/keys/#configmap[globally] to perform the aforesaid delegation to heimdall is possible as well. With that global configuration you can implement secure defaults for all your workloads.

If heimdall answers with a 2XX code, HAProxy grants access and forwards the original request to the upstream service. Otherwise, the response from heimdall is returned to the client.

NOTE: This integration requires proper configuration of `trusted_proxies`.

.Ingress annotations
====
[source, yaml]
----
haproxy-ingress.github.io/auth-url: "https://<heimdall service name>.<namespace>.svc.cluster.local:<decision port>" <1>
haproxy-ingress.github.io/auth-headers-succeed: "authorization" <2>
haproxy-ingress.github.io/headers: | <3>
  X-Forwarded-Uri: %[baseq]
  X-Forwarded-Method: %[method]
  X-Forwarded-Host: %[req.hdr(host)]
----
<1> Configures the controller to use heimdall's decision service endpoint with `<heimdall service name>`, `<namespace>` and `<decision port>` depending on your configuration.
<2> Let HAProxy forward the `Authorization` header set by heimdall to the upstream service upon successful response. This configuration depends on
your link:{{< relref "/docs/configuration/rules/pipeline_mechanisms/contextualizers.adoc" >}}[Contextualizers] and link:{{< relref "/docs/configuration/rules/pipeline_mechanisms/finalizers.adoc" >}}[Finalizers] configuration.
+
NOTE: There is currently a limitation in HAProxy Ingress Controller regarding the case-insensitivity for headers. Since heimdall returns the header in lower-case, it is important to set the names of the required to be forwarded headers in lower case as well.
<3> Configures the required headers to pass the information about the used HTTP scheme, host and port, request path and used query parameters to be forwarded to heimdall. `X-Forwarded-Proto` is not used, as it is already set by HAProxy by default.
====

Checkout the examples on https://github.com/dadrus/heimdall/tree/main/examples[GitHub] for a working demo.