---
title: "Traefik Proxy Integration"
date: 2022-06-09T18:59:49+02:00
draft: false
menu:
  docs:
    parent: "Guides"
---

https://doc.traefik.io/traefik/[Traefik Proxy] is a modern HTTP proxy and load balancer for microservices, heimdall can be integrated with via the https://doc.traefik.io/traefik/middlewares/http/forwardauth/[ForwardAuth Middleware] by making use of the link:{{< relref "/docs/introduction/architecture.adoc#_decision_api_mode" >}}[Decision API]. In such setup, traefik delegates authentication and authorization to heimdall. If heimdall answers with a 2XX code, traefik grants access and forwards the original request to the upstream service. Otherwise, the response  from heimdall is returned to the client.

To achieve this,

* Configure traefik
  * to make use of the aforesaid ForwardAuth middleware by setting the `address` property to the decision api endpoint and
  * configure the `authResponseHeaders` to contain the required header name(s), heimdall sets in the HTTP responses (depends on your [Mutators]({{< relref "/docs/configuration/pipeline/mutators.adoc" >}}) configuration).
* Configure the route of your service to make use of this middleware.

[IMPORTANT]
====
Traefik makes use of `X-Forwarded-*` HTTP headers to forward the HTTP method, protocol, host, etc. to the ForwardAuth middleware. These headers can be spoofed, if no caution is taken. To ensure, heimdall accepts such headers only from trusted sources, you should consider setting [trusted proxies]({{< relref "/docs/configuration/services/decision_api.adoc#_trusted_proxies" >}}) in heimdall's decision api configuration.
====

.Using Docker labels
====

[source, yaml]
----
edge-router:
  image: traefik
  # further configuration
  labels:
    - traefik.http.middlewares.heimdall.forwardauth.address=http://heimdall:4456/decisions
    - traefik.http.middlewares.heimdall.forwardauth.authResponseHeaders=X-Id-Token,Authorization
    # further labels

service:
  image: my-service
  # further configuration
  labels:
    - traefik.http.routers.service.middlewares=heimdall
    # further labels
----

====
