// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1alpha3 "github.com/dadrus/heimdall/internal/rules/provider/kubernetes/api/v1alpha4"

	watch "k8s.io/apimachinery/pkg/watch"
)

// RuleSetRepositoryMock is an autogenerated mock type for the RuleSetRepository type
type RuleSetRepositoryMock struct {
	mock.Mock
}

type RuleSetRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RuleSetRepositoryMock) EXPECT() *RuleSetRepositoryMock_Expecter {
	return &RuleSetRepositoryMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key, opts
func (_m *RuleSetRepositoryMock) Get(ctx context.Context, key types.NamespacedName, opts v1.GetOptions) (*v1alpha3.RuleSet, error) {
	ret := _m.Called(ctx, key, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1alpha3.RuleSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.NamespacedName, v1.GetOptions) (*v1alpha3.RuleSet, error)); ok {
		return rf(ctx, key, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.NamespacedName, v1.GetOptions) *v1alpha3.RuleSet); ok {
		r0 = rf(ctx, key, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha3.RuleSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.NamespacedName, v1.GetOptions) error); ok {
		r1 = rf(ctx, key, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuleSetRepositoryMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type RuleSetRepositoryMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key types.NamespacedName
//   - opts v1.GetOptions
func (_e *RuleSetRepositoryMock_Expecter) Get(ctx interface{}, key interface{}, opts interface{}) *RuleSetRepositoryMock_Get_Call {
	return &RuleSetRepositoryMock_Get_Call{Call: _e.mock.On("Get", ctx, key, opts)}
}

func (_c *RuleSetRepositoryMock_Get_Call) Run(run func(ctx context.Context, key types.NamespacedName, opts v1.GetOptions)) *RuleSetRepositoryMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.NamespacedName), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *RuleSetRepositoryMock_Get_Call) Return(_a0 *v1alpha3.RuleSet, _a1 error) *RuleSetRepositoryMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuleSetRepositoryMock_Get_Call) RunAndReturn(run func(context.Context, types.NamespacedName, v1.GetOptions) (*v1alpha3.RuleSet, error)) *RuleSetRepositoryMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *RuleSetRepositoryMock) List(ctx context.Context, opts v1.ListOptions) (*v1alpha3.RuleSetList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1alpha3.RuleSetList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*v1alpha3.RuleSetList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *v1alpha3.RuleSetList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha3.RuleSetList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuleSetRepositoryMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RuleSetRepositoryMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *RuleSetRepositoryMock_Expecter) List(ctx interface{}, opts interface{}) *RuleSetRepositoryMock_List_Call {
	return &RuleSetRepositoryMock_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *RuleSetRepositoryMock_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *RuleSetRepositoryMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *RuleSetRepositoryMock_List_Call) Return(_a0 *v1alpha3.RuleSetList, _a1 error) *RuleSetRepositoryMock_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuleSetRepositoryMock_List_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (*v1alpha3.RuleSetList, error)) *RuleSetRepositoryMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// PatchStatus provides a mock function with given fields: ctx, patch, opts
func (_m *RuleSetRepositoryMock) PatchStatus(ctx context.Context, patch v1alpha3.Patch, opts v1.PatchOptions) (*v1alpha3.RuleSet, error) {
	ret := _m.Called(ctx, patch, opts)

	if len(ret) == 0 {
		panic("no return value specified for PatchStatus")
	}

	var r0 *v1alpha3.RuleSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1alpha3.Patch, v1.PatchOptions) (*v1alpha3.RuleSet, error)); ok {
		return rf(ctx, patch, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1alpha3.Patch, v1.PatchOptions) *v1alpha3.RuleSet); ok {
		r0 = rf(ctx, patch, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha3.RuleSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1alpha3.Patch, v1.PatchOptions) error); ok {
		r1 = rf(ctx, patch, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuleSetRepositoryMock_PatchStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchStatus'
type RuleSetRepositoryMock_PatchStatus_Call struct {
	*mock.Call
}

// PatchStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - patch v1alpha4.Patch
//   - opts v1.PatchOptions
func (_e *RuleSetRepositoryMock_Expecter) PatchStatus(ctx interface{}, patch interface{}, opts interface{}) *RuleSetRepositoryMock_PatchStatus_Call {
	return &RuleSetRepositoryMock_PatchStatus_Call{Call: _e.mock.On("PatchStatus", ctx, patch, opts)}
}

func (_c *RuleSetRepositoryMock_PatchStatus_Call) Run(run func(ctx context.Context, patch v1alpha3.Patch, opts v1.PatchOptions)) *RuleSetRepositoryMock_PatchStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1alpha3.Patch), args[2].(v1.PatchOptions))
	})
	return _c
}

func (_c *RuleSetRepositoryMock_PatchStatus_Call) Return(_a0 *v1alpha3.RuleSet, _a1 error) *RuleSetRepositoryMock_PatchStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuleSetRepositoryMock_PatchStatus_Call) RunAndReturn(run func(context.Context, v1alpha3.Patch, v1.PatchOptions) (*v1alpha3.RuleSet, error)) *RuleSetRepositoryMock_PatchStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *RuleSetRepositoryMock) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuleSetRepositoryMock_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type RuleSetRepositoryMock_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *RuleSetRepositoryMock_Expecter) Watch(ctx interface{}, opts interface{}) *RuleSetRepositoryMock_Watch_Call {
	return &RuleSetRepositoryMock_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *RuleSetRepositoryMock_Watch_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *RuleSetRepositoryMock_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *RuleSetRepositoryMock_Watch_Call) Return(_a0 watch.Interface, _a1 error) *RuleSetRepositoryMock_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuleSetRepositoryMock_Watch_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (watch.Interface, error)) *RuleSetRepositoryMock_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// NewRuleSetRepositoryMock creates a new instance of RuleSetRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRuleSetRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RuleSetRepositoryMock {
	mock := &RuleSetRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
