apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki-datasource
  namespace: monitoring
spec:
  name: loki-datasource
  datasources:
  - name: Loki
    type: loki
    uid: LOKI
    url: http://loki:3100
    isDefault: false
    jsonData:
      derivedFields:
      - name: trace_id
        matcherRegex: 'trace_id\":\"(\w+)\"'
        url: '$${__value.raw}'
        datasourceUid: TEMPO