apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-datasource
  namespace: monitoring
spec:
  name: prometheus-datasource
  datasources:
  - name: Prometheus
    type: prometheus
    uid: PROMETHEUS
    url: http://prometheus-kube-prometheus-prometheus:9090
    isDefault: true