apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: tempo-datasource
  namespace: monitoring
spec:
  name: tempo-datasource
  datasources:
    - name: Tempo
      type: tempo
      uid: TEMPO
      url: http://tempo:3100
      isDefault: false
      jsonData:
        tracesToLogs:
          datasourceUid: LOKI
          filterBySpanID: true
