apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo-datasource
  namespace: monitoring
spec:
  datasource:
    name: Tempo
    type: tempo
    url: http://tempo-grafana-tempo-query-frontend:3200
    isDefault: false
    uid: TEMPO
    access: proxy
    jsonData:
      tracesToLogs:
        datasourceUid: LOKI
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: PROMETHEUS
  instanceSelector:
    matchLabels:
      dashboards: grafana
