{{- if .Values.demoSetup }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heimdall.demo.fullname" . }}
  {{- include "heimdall.namespace" . | nindent 2 }}
  labels:
    {{- include "heimdall.demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "heimdall.demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "heimdall.demo.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      # https://github.com/kubernetes/kubernetes/issues/57601
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.deployment.pod.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          image: "containous/whoami:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "--port", "8080", "--name", "{{ include "heimdall.demo.name" . }}" ]
          ports:
            - name: http-demo
              protocol: TCP
              containerPort: 8080
{{- end }}