// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dadrus/heimdall/internal/secrets/types"
	mock "github.com/stretchr/testify/mock"
)

// NewProviderMock creates a new instance of ProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProviderMock {
	mock := &ProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProviderMock is an autogenerated mock type for the Provider type
type ProviderMock struct {
	mock.Mock
}

type ProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ProviderMock) EXPECT() *ProviderMock_Expecter {
	return &ProviderMock_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type ProviderMock
func (_mock *ProviderMock) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ProviderMock_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type ProviderMock_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *ProviderMock_Expecter) Name() *ProviderMock_Name_Call {
	return &ProviderMock_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *ProviderMock_Name_Call) Run(run func()) *ProviderMock_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProviderMock_Name_Call) Return(s string) *ProviderMock_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ProviderMock_Name_Call) RunAndReturn(run func() string) *ProviderMock_Name_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveSecret provides a mock function for the type ProviderMock
func (_mock *ProviderMock) ResolveSecret(ctx context.Context, ref string) (types.Secret, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for ResolveSecret")
	}

	var r0 types.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (types.Secret, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) types.Secret); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Get(0).(types.Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProviderMock_ResolveSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveSecret'
type ProviderMock_ResolveSecret_Call struct {
	*mock.Call
}

// ResolveSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
func (_e *ProviderMock_Expecter) ResolveSecret(ctx interface{}, ref interface{}) *ProviderMock_ResolveSecret_Call {
	return &ProviderMock_ResolveSecret_Call{Call: _e.mock.On("ResolveSecret", ctx, ref)}
}

func (_c *ProviderMock_ResolveSecret_Call) Run(run func(ctx context.Context, ref string)) *ProviderMock_ResolveSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProviderMock_ResolveSecret_Call) Return(secret types.Secret, err error) *ProviderMock_ResolveSecret_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *ProviderMock_ResolveSecret_Call) RunAndReturn(run func(ctx context.Context, ref string) (types.Secret, error)) *ProviderMock_ResolveSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveSecrets provides a mock function for the type ProviderMock
func (_mock *ProviderMock) ResolveSecrets(ctx context.Context, ref string, keys ...string) (map[string]types.Secret, error) {
	// string
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, ref)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ResolveSecrets")
	}

	var r0 map[string]types.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) (map[string]types.Secret, error)); ok {
		return returnFunc(ctx, ref, keys...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) map[string]types.Secret); ok {
		r0 = returnFunc(ctx, ref, keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]types.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, ref, keys...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProviderMock_ResolveSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveSecrets'
type ProviderMock_ResolveSecrets_Call struct {
	*mock.Call
}

// ResolveSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
//   - keys ...string
func (_e *ProviderMock_Expecter) ResolveSecrets(ctx interface{}, ref interface{}, keys ...interface{}) *ProviderMock_ResolveSecrets_Call {
	return &ProviderMock_ResolveSecrets_Call{Call: _e.mock.On("ResolveSecrets",
		append([]interface{}{ctx, ref}, keys...)...)}
}

func (_c *ProviderMock_ResolveSecrets_Call) Run(run func(ctx context.Context, ref string, keys ...string)) *ProviderMock_ResolveSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ProviderMock_ResolveSecrets_Call) Return(stringToSecret map[string]types.Secret, err error) *ProviderMock_ResolveSecrets_Call {
	_c.Call.Return(stringToSecret, err)
	return _c
}

func (_c *ProviderMock_ResolveSecrets_Call) RunAndReturn(run func(ctx context.Context, ref string, keys ...string) (map[string]types.Secret, error)) *ProviderMock_ResolveSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type ProviderMock
func (_mock *ProviderMock) Start(ctx context.Context, onChange func(types.ChangeEvent)) error {
	ret := _mock.Called(ctx, onChange)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(types.ChangeEvent)) error); ok {
		r0 = returnFunc(ctx, onChange)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProviderMock_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ProviderMock_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - onChange func(types.ChangeEvent)
func (_e *ProviderMock_Expecter) Start(ctx interface{}, onChange interface{}) *ProviderMock_Start_Call {
	return &ProviderMock_Start_Call{Call: _e.mock.On("Start", ctx, onChange)}
}

func (_c *ProviderMock_Start_Call) Run(run func(ctx context.Context, onChange func(types.ChangeEvent))) *ProviderMock_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(types.ChangeEvent)
		if args[1] != nil {
			arg1 = args[1].(func(types.ChangeEvent))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProviderMock_Start_Call) Return(err error) *ProviderMock_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProviderMock_Start_Call) RunAndReturn(run func(ctx context.Context, onChange func(types.ChangeEvent)) error) *ProviderMock_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type ProviderMock
func (_mock *ProviderMock) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProviderMock_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type ProviderMock_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ProviderMock_Expecter) Stop(ctx interface{}) *ProviderMock_Stop_Call {
	return &ProviderMock_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *ProviderMock_Stop_Call) Run(run func(ctx context.Context)) *ProviderMock_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProviderMock_Stop_Call) Return(err error) *ProviderMock_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProviderMock_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *ProviderMock_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type ProviderMock
func (_mock *ProviderMock) Type() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ProviderMock_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type ProviderMock_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *ProviderMock_Expecter) Type() *ProviderMock_Type_Call {
	return &ProviderMock_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *ProviderMock_Type_Call) Run(run func()) *ProviderMock_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProviderMock_Type_Call) Return(s string) *ProviderMock_Type_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ProviderMock_Type_Call) RunAndReturn(run func() string) *ProviderMock_Type_Call {
	_c.Call.Return(run)
	return _c
}
