// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dadrus/heimdall/internal/secrets/types"
	mock "github.com/stretchr/testify/mock"
)

// NewWatchableMock creates a new instance of WatchableMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWatchableMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *WatchableMock {
	mock := &WatchableMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WatchableMock is an autogenerated mock type for the Watchable type
type WatchableMock struct {
	mock.Mock
}

type WatchableMock_Expecter struct {
	mock *mock.Mock
}

func (_m *WatchableMock) EXPECT() *WatchableMock_Expecter {
	return &WatchableMock_Expecter{mock: &_m.Mock}
}

// Watch provides a mock function for the type WatchableMock
func (_mock *WatchableMock) Watch(ctx context.Context, onChange func(types.ChangeEvent)) error {
	ret := _mock.Called(ctx, onChange)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(types.ChangeEvent)) error); ok {
		r0 = returnFunc(ctx, onChange)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WatchableMock_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type WatchableMock_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - onChange func(types.ChangeEvent)
func (_e *WatchableMock_Expecter) Watch(ctx interface{}, onChange interface{}) *WatchableMock_Watch_Call {
	return &WatchableMock_Watch_Call{Call: _e.mock.On("Watch", ctx, onChange)}
}

func (_c *WatchableMock_Watch_Call) Run(run func(ctx context.Context, onChange func(types.ChangeEvent))) *WatchableMock_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(types.ChangeEvent)
		if args[1] != nil {
			arg1 = args[1].(func(types.ChangeEvent))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WatchableMock_Watch_Call) Return(err error) *WatchableMock_Watch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WatchableMock_Watch_Call) RunAndReturn(run func(ctx context.Context, onChange func(types.ChangeEvent)) error) *WatchableMock_Watch_Call {
	_c.Call.Return(run)
	return _c
}
