{
 "title": "Heimdall Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Request Duration Distribution",
   "type": "bargauge",
   "description": "Shows the duration distribution of requests handled by heimdall",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_bucket{container=\"heimdall\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{container=\"heimdall\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{container=\"heimdall\"}[1m])) by (le))",
     "legendFormat": "q99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{container=\"heimdall\"}[1m])) by (le))",
     "legendFormat": "q95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{container=\"heimdall\"}[1m])) by (le))",
     "legendFormat": "q90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{container=\"heimdall\"}[1m])) by (le))",
     "legendFormat": "q50"
    },
    {
     "expr": "avg(rate(http_request_duration_seconds_sum{container=\"heimdall\"}[1m]) / rate(http_request_duration_seconds_count{container=\"heimdall\"}[1m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Stack Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{container=\"heimdall\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{container=\"heimdall\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{container=\"heimdall\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{container=\"heimdall\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{container=\"heimdall\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{container=\"heimdall\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{container=\"heimdall\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_released_bytes{container=\"heimdall\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GO Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "go_goroutines{container=\"heimdall\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{container=\"heimdall\"}[1m])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}