// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dadrus/heimdall/internal/secrets/source"
	"github.com/dadrus/heimdall/internal/secrets/types"
	mock "github.com/stretchr/testify/mock"
)

// NewSourceMock creates a new instance of SourceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSourceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SourceMock {
	mock := &SourceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SourceMock is an autogenerated mock type for the Source type
type SourceMock struct {
	mock.Mock
}

type SourceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SourceMock) EXPECT() *SourceMock_Expecter {
	return &SourceMock_Expecter{mock: &_m.Mock}
}

// AccessFromRulesAllowed provides a mock function for the type SourceMock
func (_mock *SourceMock) AccessFromRulesAllowed() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AccessFromRulesAllowed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// SourceMock_AccessFromRulesAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessFromRulesAllowed'
type SourceMock_AccessFromRulesAllowed_Call struct {
	*mock.Call
}

// AccessFromRulesAllowed is a helper method to define mock.On call
func (_e *SourceMock_Expecter) AccessFromRulesAllowed() *SourceMock_AccessFromRulesAllowed_Call {
	return &SourceMock_AccessFromRulesAllowed_Call{Call: _e.mock.On("AccessFromRulesAllowed")}
}

func (_c *SourceMock_AccessFromRulesAllowed_Call) Run(run func()) *SourceMock_AccessFromRulesAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceMock_AccessFromRulesAllowed_Call) Return(b bool) *SourceMock_AccessFromRulesAllowed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *SourceMock_AccessFromRulesAllowed_Call) RunAndReturn(run func() bool) *SourceMock_AccessFromRulesAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificateBundle provides a mock function for the type SourceMock
func (_mock *SourceMock) GetCertificateBundle(ctx context.Context, selector source.Selector) (types.CertificateBundle, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateBundle")
	}

	var r0 types.CertificateBundle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, source.Selector) (types.CertificateBundle, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, source.Selector) types.CertificateBundle); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.CertificateBundle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, source.Selector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SourceMock_GetCertificateBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateBundle'
type SourceMock_GetCertificateBundle_Call struct {
	*mock.Call
}

// GetCertificateBundle is a helper method to define mock.On call
//   - ctx context.Context
//   - selector source.Selector
func (_e *SourceMock_Expecter) GetCertificateBundle(ctx interface{}, selector interface{}) *SourceMock_GetCertificateBundle_Call {
	return &SourceMock_GetCertificateBundle_Call{Call: _e.mock.On("GetCertificateBundle", ctx, selector)}
}

func (_c *SourceMock_GetCertificateBundle_Call) Run(run func(ctx context.Context, selector source.Selector)) *SourceMock_GetCertificateBundle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 source.Selector
		if args[1] != nil {
			arg1 = args[1].(source.Selector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SourceMock_GetCertificateBundle_Call) Return(certificateBundle types.CertificateBundle, err error) *SourceMock_GetCertificateBundle_Call {
	_c.Call.Return(certificateBundle, err)
	return _c
}

func (_c *SourceMock_GetCertificateBundle_Call) RunAndReturn(run func(ctx context.Context, selector source.Selector) (types.CertificateBundle, error)) *SourceMock_GetCertificateBundle_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentials provides a mock function for the type SourceMock
func (_mock *SourceMock) GetCredentials(ctx context.Context, selector source.Selector) (types.Credentials, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentials")
	}

	var r0 types.Credentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, source.Selector) (types.Credentials, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, source.Selector) types.Credentials); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, source.Selector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SourceMock_GetCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentials'
type SourceMock_GetCredentials_Call struct {
	*mock.Call
}

// GetCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - selector source.Selector
func (_e *SourceMock_Expecter) GetCredentials(ctx interface{}, selector interface{}) *SourceMock_GetCredentials_Call {
	return &SourceMock_GetCredentials_Call{Call: _e.mock.On("GetCredentials", ctx, selector)}
}

func (_c *SourceMock_GetCredentials_Call) Run(run func(ctx context.Context, selector source.Selector)) *SourceMock_GetCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 source.Selector
		if args[1] != nil {
			arg1 = args[1].(source.Selector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SourceMock_GetCredentials_Call) Return(credentials types.Credentials, err error) *SourceMock_GetCredentials_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *SourceMock_GetCredentials_Call) RunAndReturn(run func(ctx context.Context, selector source.Selector) (types.Credentials, error)) *SourceMock_GetCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function for the type SourceMock
func (_mock *SourceMock) GetSecret(ctx context.Context, selector source.Selector) (types.Secret, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 types.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, source.Selector) (types.Secret, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, source.Selector) types.Secret); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, source.Selector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SourceMock_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type SourceMock_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - selector source.Selector
func (_e *SourceMock_Expecter) GetSecret(ctx interface{}, selector interface{}) *SourceMock_GetSecret_Call {
	return &SourceMock_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, selector)}
}

func (_c *SourceMock_GetSecret_Call) Run(run func(ctx context.Context, selector source.Selector)) *SourceMock_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 source.Selector
		if args[1] != nil {
			arg1 = args[1].(source.Selector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SourceMock_GetSecret_Call) Return(secret types.Secret, err error) *SourceMock_GetSecret_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *SourceMock_GetSecret_Call) RunAndReturn(run func(ctx context.Context, selector source.Selector) (types.Secret, error)) *SourceMock_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretSet provides a mock function for the type SourceMock
func (_mock *SourceMock) GetSecretSet(ctx context.Context, selector source.Selector) ([]types.Secret, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretSet")
	}

	var r0 []types.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, source.Selector) ([]types.Secret, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, source.Selector) []types.Secret); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, source.Selector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SourceMock_GetSecretSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretSet'
type SourceMock_GetSecretSet_Call struct {
	*mock.Call
}

// GetSecretSet is a helper method to define mock.On call
//   - ctx context.Context
//   - selector source.Selector
func (_e *SourceMock_Expecter) GetSecretSet(ctx interface{}, selector interface{}) *SourceMock_GetSecretSet_Call {
	return &SourceMock_GetSecretSet_Call{Call: _e.mock.On("GetSecretSet", ctx, selector)}
}

func (_c *SourceMock_GetSecretSet_Call) Run(run func(ctx context.Context, selector source.Selector)) *SourceMock_GetSecretSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 source.Selector
		if args[1] != nil {
			arg1 = args[1].(source.Selector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SourceMock_GetSecretSet_Call) Return(secrets []types.Secret, err error) *SourceMock_GetSecretSet_Call {
	_c.Call.Return(secrets, err)
	return _c
}

func (_c *SourceMock_GetSecretSet_Call) RunAndReturn(run func(ctx context.Context, selector source.Selector) ([]types.Secret, error)) *SourceMock_GetSecretSet_Call {
	_c.Call.Return(run)
	return _c
}

// IsNamespaceAware provides a mock function for the type SourceMock
func (_mock *SourceMock) IsNamespaceAware() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsNamespaceAware")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// SourceMock_IsNamespaceAware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNamespaceAware'
type SourceMock_IsNamespaceAware_Call struct {
	*mock.Call
}

// IsNamespaceAware is a helper method to define mock.On call
func (_e *SourceMock_Expecter) IsNamespaceAware() *SourceMock_IsNamespaceAware_Call {
	return &SourceMock_IsNamespaceAware_Call{Call: _e.mock.On("IsNamespaceAware")}
}

func (_c *SourceMock_IsNamespaceAware_Call) Run(run func()) *SourceMock_IsNamespaceAware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceMock_IsNamespaceAware_Call) Return(b bool) *SourceMock_IsNamespaceAware_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *SourceMock_IsNamespaceAware_Call) RunAndReturn(run func() bool) *SourceMock_IsNamespaceAware_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type SourceMock
func (_mock *SourceMock) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SourceMock_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type SourceMock_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *SourceMock_Expecter) Name() *SourceMock_Name_Call {
	return &SourceMock_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *SourceMock_Name_Call) Run(run func()) *SourceMock_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceMock_Name_Call) Return(s string) *SourceMock_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *SourceMock_Name_Call) RunAndReturn(run func() string) *SourceMock_Name_Call {
	_c.Call.Return(run)
	return _c
}
