# Options for analysis running.
run:
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - dupl
    - wrapcheck
    - ireturn
    - exhaustruct
    - exhaustivestruct
    - maligned
    - scopelint
    - golint
    - ifshort
    - interfacer
    - testpackage
    - funlen
    - paralleltest
    - nolintlint
    - tparallel

linters-settings:
  exhaustive:
    ignore-enum-members: "POT.+"
  tagliatelle:
    # Check the struck tag name case.
    case:
      rules:
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`
        json: snake
        yaml: snake
  gci:
    no-inline-comments: true
    no-prefix-comments: true
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/dadrus/heimdall) # Groups all imports with the specified Prefix.
  varnamelen:
    min-name-length: 2
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
    # Optional list of variable declarations that should be ignored completely. (defaults to empty list)
    # Entries must be in one of the following forms (see below for examples):
    # - for variables, parameters, named return values, method receivers, or type parameters:
    #   <name> <type>  (<type> can also be a pointer/slice/map/chan/...)
    # - for constants: const <name>
    ignore-decls:
      - c *fiber.Ctx
      - t testing.T
      - i int
      - T any
      - m map[string]int
      - w http.ResponseWriter
      - r *http.Request
  goconst:
    ignore-tests: true
#  revive:
#    max-open-files: 2048
#    severity: error
#    enable-all-rules: true
#    rules:
#      - name: unexported-return
#        severity: warning
#        disabled: true
  cyclop:
    # The maximal code complexity to report.
    max-complexity: 11
