{
 "title": "Heimdall Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Request Duration Distribution",
   "type": "bargauge",
   "description": "Shows the duration distribution of requests handled by heimdall",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_bucket{container=\"heimdall\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{container=\"heimdall\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{container=\"heimdall\"}[$__rate_interval])) by (le))",
     "legendFormat": "q99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{container=\"heimdall\"}[$__rate_interval])) by (le))",
     "legendFormat": "q95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{container=\"heimdall\"}[$__rate_interval])) by (le))",
     "legendFormat": "q90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_request_duration_seconds_bucket{container=\"heimdall\"}[$__rate_interval])) by (le))",
     "legendFormat": "q50"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{container=\"heimdall\"}[$__rate_interval]))\n/\nsum(rate(http_server_request_duration_seconds_count{container=\"heimdall\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{container=\"heimdall\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Stack Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{container=\"heimdall\"}",
     "legendFormat": "in-use"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{container=\"heimdall\"}",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "GC pauses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{container=\"heimdall\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "go_gc_duration_seconds{container=\"heimdall\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "rate(go_gc_duration_seconds_sum{container=\"heimdall\"}[$__rate_interval])\n/\nrate(go_gc_duration_seconds_count{container=\"heimdall\"}[$__rate_interval])",
     "legendFormat": "ave"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{container=\"heimdall\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{container=\"heimdall\"}",
     "legendFormat": "allocated"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{container=\"heimdall\"}",
     "legendFormat": "system"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{container=\"heimdall\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{container=\"heimdall\"}",
     "legendFormat": "in-use"
    },
    {
     "expr": "go_memstats_heap_released_bytes{container=\"heimdall\"}",
     "legendFormat": "released"
    }
   ]
  },
  {
   "title": "GC frequency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{container=\"heimdall\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Allocation rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(go_memory_allocated_bytes_total{container=\"heimdall\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GO Routines",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "go_goroutines{container=\"heimdall\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC CPU time ratio",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{container=\"heimdall\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}