// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dadrus/heimdall/internal/secrets/types"
	mock "github.com/stretchr/testify/mock"
)

// NewSecretUsageMock creates a new instance of SecretUsageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretUsageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretUsageMock {
	mock := &SecretUsageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SecretUsageMock is an autogenerated mock type for the SecretUsage type
type SecretUsageMock struct {
	mock.Mock
}

type SecretUsageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretUsageMock) EXPECT() *SecretUsageMock_Expecter {
	return &SecretUsageMock_Expecter{mock: &_m.Mock}
}

// Track provides a mock function for the type SecretUsageMock
func (_mock *SecretUsageMock) Track(secret types.Secret) {
	_mock.Called(secret)
	return
}

// SecretUsageMock_Track_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Track'
type SecretUsageMock_Track_Call struct {
	*mock.Call
}

// Track is a helper method to define mock.On call
//   - secret types.Secret
func (_e *SecretUsageMock_Expecter) Track(secret interface{}) *SecretUsageMock_Track_Call {
	return &SecretUsageMock_Track_Call{Call: _e.mock.On("Track", secret)}
}

func (_c *SecretUsageMock_Track_Call) Run(run func(secret types.Secret)) *SecretUsageMock_Track_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Secret
		if args[0] != nil {
			arg0 = args[0].(types.Secret)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SecretUsageMock_Track_Call) Return() *SecretUsageMock_Track_Call {
	_c.Call.Return()
	return _c
}

func (_c *SecretUsageMock_Track_Call) RunAndReturn(run func(secret types.Secret)) *SecretUsageMock_Track_Call {
	_c.Run(run)
	return _c
}

// Untrack provides a mock function for the type SecretUsageMock
func (_mock *SecretUsageMock) Untrack(secret types.Secret) {
	_mock.Called(secret)
	return
}

// SecretUsageMock_Untrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Untrack'
type SecretUsageMock_Untrack_Call struct {
	*mock.Call
}

// Untrack is a helper method to define mock.On call
//   - secret types.Secret
func (_e *SecretUsageMock_Expecter) Untrack(secret interface{}) *SecretUsageMock_Untrack_Call {
	return &SecretUsageMock_Untrack_Call{Call: _e.mock.On("Untrack", secret)}
}

func (_c *SecretUsageMock_Untrack_Call) Run(run func(secret types.Secret)) *SecretUsageMock_Untrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Secret
		if args[0] != nil {
			arg0 = args[0].(types.Secret)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SecretUsageMock_Untrack_Call) Return() *SecretUsageMock_Untrack_Call {
	_c.Call.Return()
	return _c
}

func (_c *SecretUsageMock_Untrack_Call) RunAndReturn(run func(secret types.Secret)) *SecretUsageMock_Untrack_Call {
	_c.Run(run)
	return _c
}
