# Copyright 2022 Dimitrij Drus <dadrus@gmx.de>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "heimdall.fullname" . }}
  namespace: {{ include "heimdall.namespace" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
automountServiceAccountToken: false

---
# Rules are not expected to contain any secrets. For that reason it is acceptable to
# have a long living token, which might be exposed via a k8s API
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heimdall.fullname" . }}-account-token
  namespace: {{ include "heimdall.namespace" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "heimdall.fullname" . }}
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "heimdall.fullname" . }}-ruleset-accessor
  namespace: {{ include "heimdall.namespace" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "heimdall.dadrus.github.com" ]
    resources: [ "rulesets", "rulesets/status" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "heimdall.dadrus.github.com" ]
    resources: [ "rulesets/status" ]
    verbs: [ "patch", "update" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "heimdall.fullname" . }}-ruleset-accessor
  namespace: {{ include "heimdall.namespace" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "heimdall.fullname" . }}
    namespace: {{ include "heimdall.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "heimdall.fullname" . }}-ruleset-accessor
  apiGroup: rbac.authorization.k8s.io
