= Heimdall Helm Chart

== Introduction

This chart helps you to deploy heimdall in your Kubernetes cluster using Helm.

== Prerequisites

* A Kubernetes version >= 1.19 or >= 1.23 if you would like to use HPA
* https://helm.sh/docs/intro/install/[Helm] 3.0+
* https://git-scm.com/downloads[Git] (optional)

== Getting the Chart Sources

This step is required if you want installing the chart using its sources. Additionally, the step may also be required for managing the custom resource definitions (CRDs), which heimdall requires, or for upgrading/deleting the CRDs.

To install the chart with the release name "my-release" ("my-release" is the name that you choose):

1. Clone the heimdall repo:
+
[source,bash]
----
git clone https://github.com/dadrus/heimddall
----

2. Change your working directory to the root directory of the cloned repository:
+
[source,bash]
----
cd heimdall
----

== Adding the Helm Repository

This step is required if you're installing the chart via the helm repository.

[source,bash]
----
$ helm repo add heimdall https://dadrus.github.io/heimdall/chart
$ helm repo update
----

== Installing the Chart

This chart expects a heimdall configuration file with authentication, authorization and so on mechanisms, required for your particular setup. This file can be passed by using the `-f heimdall.yaml` flag during the installation.

This chart does also support a demo installation, which can be enabled by using the `--set demo.enabled=true` flag during the installation. For the demo installation there is no need to provide a configuration file, as some simple mechanisms are already part of that installation. In addition, a demo rule set, as well as a simple echo service will be installed. If you're using an NGINX Ingress Controller, the chart will do the required integration, so you can directly see heimdall in action, by e.g. using curl:

* Send requests to a "public" (unprotected) endpoint
+
[source,bash]
----
$ curl -v -H "Host: demo-app" <you cluster ip and port>/heimdall-demo/public
----

* Send requests to an endpoint which expects a JWT with a `sub` claim set to `anonymous`
+
[source,bash]
----
$ curl -v -H "Host: demo-app" <you cluster ip and port>/heimdall-demo/anonymous
----

* All other endpoints are not allowed to be called and will result in HTTP 403
+
[source,bash]
----
$ curl -v -H "Host: demo-app" <you cluster ip and port>/heimdall-demo/foo
----


=== Installing the CRD

By default, heimdall requires a custom resource definition (CRD) installed in the cluster. The Helm client will install it for you. If the CRD is not installed, you'll neither be able to deploy the corresponding rule sets, nor will heimdall be able to communicate with the api server.

=== Installing via Helm Repository

To install the chart with the release name "my-release" ("my-release" is the name that you choose) and configure heimdall to operate in decision mode:

[source,bash]
----
$ helm install my-release -f heimdall.yaml heimdall
----

If you need proxy mode, install it with:

[source,bash]
----
$ helm install my-release -f heimdall.yaml --set operationMode=proxy heimdall
----

In both cases you have to integrate it with your ingress controller. For decision mode that means setting corresponding annotations on Ingress resources to let the traffic first be verified by heimdall before it is forwarded to the upstream services by the Ingress Controller.

=== Installing Using Chart Sources

To install the chart with the release name "my-release" ("my-release" is the name that you choose) and configure heimdall to operate in decision mode:

[source,bash]
----
$ helm install my-release -f heimdall.yaml ./helm-chart
----

If you need proxy mode, install it with:

[source,bash]
----
$ helm install my-release -f heimdall.yaml --set operationMode=proxy ./helm-chart
----

In both cases you have to integrate it with your ingress controller. For decision mode that means setting corresponding annotations on Ingress resources to let the traffic first be verified by heimdall before it is forwarded to the upstream services by the Ingress Controller.

== Upgrading the Chart

=== Upgrading the CRD

Helm does not upgrade the CRDs during a release upgrade. Before you upgrade a release, run the following command to upgrade the CRDs:

[source,bash]
----
$ kubectl apply -f ./helm-chart/crds/
----

=== Upgrading the Release

To upgrade the release "my-release" using Chart Sources:

[source,bash]
----
$ helm upgrade my-release ./helm-chart
----

To upgrade the release "my-release" using Helm Repository:

$ helm upgrade my-release heimdall

== Uninstalling the Chart
=== Uninstalling the Release

To uninstall/delete the release "my-release":

[source,bash]
----
$ helm uninstall my-release
----

The command removes all the Kubernetes components associated with the release and deletes the release.

=== Uninstalling the CRDs

Uninstalling the release does not remove the CRDs. To remove the CRDs, run:

[source,bash]
----
$ kubectl delete -f crds/
----

== Configuration

The following table lists the configurable parameters of the heimdall chart and their default values.

|===
|Parameter |Description | Default Value

a| `operationMode`
a| The mode of operation for the heimdall installation. Can be `proxy` or `decision`
a| `decision`

a| `demo.enabled`
a| Wether a demo installation should be done. If demo installation is chosen, you don't have to provide a `heimdall.yaml` config file, as the required configuration is included in the demo setup.
a| `false`

a| `demo.forwardAuthMiddlewareAnnotation`
a| Which annotation to use on the demo app Ingress rule for decision operation mode to let the Ingress Controller use heimdall as authentication middleware
a| `nginx.ingress.kubernetes.io/auth-url`

a| `demo.forwardAuthMiddlewareResponseAnnotation`
a| Which annotation to use on the demo app Ingress rule for decision operation mode to let the Ingress Controller forwarding the response headers coming from heimdall to the demo app.
a| `nginx.ingress.kubernetes.io/auth-response-headers`

a| `demo.forwardAuthMiddlewareRequestUri`
a| Which macro/variable to use to forward the request uri to heimdall. Depending on your Ingress Controller, it can be omitted. E.g. Traefik sends such information in a header.
a| `/$request_uri`

a| `image.repository`
a| The image repository to load heimdall image from
a| `dadrus/heimdall`

a| `image.tag`
a| The tag of the image to use
a| `latest`

a| `image.pullPolicy`
a| The pull policy to apply
a| `IfNotPresent`

a| `image.pullSecrets`
a| Image pull secrets
a| `[]` (empty list)

a| `nameOverride`
a| Enables you to override the name used for heimdall (which is "heimdall")
a| `""`

a| `fullnameOverride`
a| Enables you to override the name used for the service created for the heimdall deployment
a| `""`

a|`deployment.annotations`
a| Enables you to set additional annotations for the deployment
a| `{}` (empty map)

a| `deployment.labels`
a| Enables you to set additional labels for the deployment
a| `{}` (empty map)

a| `deployment.pod.annotations`
a| Enables you to set additional annotations for the pod
a| `{}` (empty map)

a| `deployment.pod.securityContext`
a| Enables you to set the security context for the pod
a| `{}` (empty map)

a| `deployment.securityContext`
a| Enables you to set the security context for the deployment
a|
[source,yaml]
----
capabilities:
  drop:
   - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
----

a|`deployment.resources`
a| Enables you to specify the resources for the deployment, like limits, etc
a| `{}` (empty map)

a| `deployment.replicaCount`
a| If HPA is disabled, allows specifying the amount of desired replicas
a| `2`

a| `deployment.autoscaling.enabled`
a| Enables or disables HPA based on CPU and memory utilization
a| `true`

a| `deployment.autoscaling.minReplicas`
a| Minimal amount of desired replicas
a| `2`

a| `deployment.autoscaling.maxReplicas`
a| Maximim amount of desired replicas
a| `10`

a| `deployment.autoscaling.targetCPUUtilizationPercentage`
a| Target CPU utilization in % to scale up
a| `80`

a| `deployment.autoscaling.targetMemoryUtilizationPercentage`
a| Target Memory utilization in % to scale up
a| `80`

a| `deployment.nodeSelector`
a| Node selector settings for the deployment
a| `{}` (empty map)

a| `deployment.tolerations`
a| Tolerations for the deploment
a| `[]` (empty array)

a| `deployment.affinity`
a| Affinity settings for the deploment
a| `{}` (empty map)

a| `service.labels`
a| Enables you to set additional labels for the created services
a| `{}` (empty map)

a| `service.annotations`
a| Enables you to set additional annotations for the created services
a| `{}` (empty map)

a| `service.decision.port`
a| The port exposed by the k8s Service created for heimdall's decision endpoint. Only used if the `operationMode` is set to `decision`.
a| `4456`

a| `service.decision.name`
a| The name of the port exposed by the k8s Service created for heimdall's decision endpoint. Only used if the `operationMode` is set to `decision`.
a| `decision`

a| `service.proxy.port`
a| The port exposed by the k8s Service created for heimdall's proxy endpoint. Only used if the `operationMode` is set to `proxy`.
a| `4456`

a| `service.proxy.name`
a| The name of the port exposed by the k8s Service created for heimdall's proxy endpoint. Only used if the `operationMode` is set to `proxy`.
a| `proxy`

a| `service.management.port`
a| The port exposed by the k8s Service created for heimdall's proxy endpoint. Only used if the `operationMode` is set to `proxy`.
a| `4456`

a| `service.management.name`
a| The name of the port exposed by the k8s Service created for heimdall's management endpoint.
a| `management`
|===