apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "heimdall.fullname" . }}-configmap
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "heimdall.labels" . | indent 4 }}
data:
{{ (.Files.Glob "config/heimdall.yaml").AsConfig | indent 2 }}