apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heimdall.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
spec:
  {{- if not .Values.deployment.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "heimdall.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.pod.metadata.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "heimdall.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "heimdall.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.pod.securityContext | nindent 8 }}
      # https://github.com/kubernetes/kubernetes/issues/57601
      automountServiceAccountToken: false
      volumes:
        - name: {{ include "heimdall.name" . }}-config-volume
          configMap:
            name: {{ include "heimdall.fullname" . }}-configmap
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if eq .Values.operationMode "decision" }}
          command: [ "serve", "decision", "-c", "/etc/heimdall/config.yaml" ]
          {{- else if eq .Values.operationMode "proxy" }}
          command: [ "serve", "proxy", "-c", "/etc/heimdall/config.yaml" ]
          {{- else -}}
          {{- required "A valid operationMode is required!" .Values.operationMode -}}
          {{- end }}
          ports:
            {{- if eq .Values.operationMode "decision" }}
            - name: http-decision
              containerPort: {{ .Values.heimdall.config.serve.decision.port }}
              protocol: TCP
            {{- else if eq .Values.operationMode "proxy" }}
            - name: http-proxy
              containerPort: {{ .Values.heimdall.config.serve.proxy.port }}
              protocol: TCP
            {{- else -}}
            {{- required "A valid operationMode is required!" .Values.operationMode -}}
            {{- end }}
            - name: http-management
              protocol: TCP
              containerPort: {{ .Values.heimdall.config.serve.management.port }}
            - name: http-metrics
              protocol: TCP
              containerPort: {{ .Values.heimdall.config.metrics.prometheus.port }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
