apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sts-tls
  namespace: minio-operator
spec:
  dnsNames:
    - sts
    - sts.minio-operator.svc
    - sts.minio-operator.svc.cluster.local # Replace cluster.local with the value for your domain.
  secretName: sts-tls
  issuerRef:
    name: root-ca
    kind: ClusterIssuer