// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dadrus/heimdall/internal/secrets2/provider"
	mock "github.com/stretchr/testify/mock"
)

// NewProviderMock creates a new instance of ProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProviderMock {
	mock := &ProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProviderMock is an autogenerated mock type for the Provider type
type ProviderMock struct {
	mock.Mock
}

type ProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ProviderMock) EXPECT() *ProviderMock_Expecter {
	return &ProviderMock_Expecter{mock: &_m.Mock}
}

// Dependencies provides a mock function for the type ProviderMock
func (_mock *ProviderMock) Dependencies() []provider.Reference {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dependencies")
	}

	var r0 []provider.Reference
	if returnFunc, ok := ret.Get(0).(func() []provider.Reference); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]provider.Reference)
		}
	}
	return r0
}

// ProviderMock_Dependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dependencies'
type ProviderMock_Dependencies_Call struct {
	*mock.Call
}

// Dependencies is a helper method to define mock.On call
func (_e *ProviderMock_Expecter) Dependencies() *ProviderMock_Dependencies_Call {
	return &ProviderMock_Dependencies_Call{Call: _e.mock.On("Dependencies")}
}

func (_c *ProviderMock_Dependencies_Call) Run(run func()) *ProviderMock_Dependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProviderMock_Dependencies_Call) Return(vs []provider.Reference) *ProviderMock_Dependencies_Call {
	_c.Call.Return(vs)
	return _c
}

func (_c *ProviderMock_Dependencies_Call) RunAndReturn(run func() []provider.Reference) *ProviderMock_Dependencies_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificateBundle provides a mock function for the type ProviderMock
func (_mock *ProviderMock) GetCertificateBundle(ctx context.Context, selector provider.Selector) (provider.CertificateBundle, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificateBundle")
	}

	var r0 provider.CertificateBundle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, provider.Selector) (provider.CertificateBundle, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, provider.Selector) provider.CertificateBundle); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provider.CertificateBundle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, provider.Selector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProviderMock_GetCertificateBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificateBundle'
type ProviderMock_GetCertificateBundle_Call struct {
	*mock.Call
}

// GetCertificateBundle is a helper method to define mock.On call
//   - ctx context.Context
//   - selector provider.Selector
func (_e *ProviderMock_Expecter) GetCertificateBundle(ctx interface{}, selector interface{}) *ProviderMock_GetCertificateBundle_Call {
	return &ProviderMock_GetCertificateBundle_Call{Call: _e.mock.On("GetCertificateBundle", ctx, selector)}
}

func (_c *ProviderMock_GetCertificateBundle_Call) Run(run func(ctx context.Context, selector provider.Selector)) *ProviderMock_GetCertificateBundle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 provider.Selector
		if args[1] != nil {
			arg1 = args[1].(provider.Selector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProviderMock_GetCertificateBundle_Call) Return(v provider.CertificateBundle, err error) *ProviderMock_GetCertificateBundle_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *ProviderMock_GetCertificateBundle_Call) RunAndReturn(run func(ctx context.Context, selector provider.Selector) (provider.CertificateBundle, error)) *ProviderMock_GetCertificateBundle_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentials provides a mock function for the type ProviderMock
func (_mock *ProviderMock) GetCredentials(ctx context.Context, selector provider.Selector) (provider.Credentials, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentials")
	}

	var r0 provider.Credentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, provider.Selector) (provider.Credentials, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, provider.Selector) provider.Credentials); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provider.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, provider.Selector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProviderMock_GetCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentials'
type ProviderMock_GetCredentials_Call struct {
	*mock.Call
}

// GetCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - selector provider.Selector
func (_e *ProviderMock_Expecter) GetCredentials(ctx interface{}, selector interface{}) *ProviderMock_GetCredentials_Call {
	return &ProviderMock_GetCredentials_Call{Call: _e.mock.On("GetCredentials", ctx, selector)}
}

func (_c *ProviderMock_GetCredentials_Call) Run(run func(ctx context.Context, selector provider.Selector)) *ProviderMock_GetCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 provider.Selector
		if args[1] != nil {
			arg1 = args[1].(provider.Selector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProviderMock_GetCredentials_Call) Return(v provider.Credentials, err error) *ProviderMock_GetCredentials_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *ProviderMock_GetCredentials_Call) RunAndReturn(run func(ctx context.Context, selector provider.Selector) (provider.Credentials, error)) *ProviderMock_GetCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function for the type ProviderMock
func (_mock *ProviderMock) GetSecret(ctx context.Context, selector provider.Selector) (provider.Secret, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 provider.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, provider.Selector) (provider.Secret, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, provider.Selector) provider.Secret); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provider.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, provider.Selector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProviderMock_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type ProviderMock_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - selector provider.Selector
func (_e *ProviderMock_Expecter) GetSecret(ctx interface{}, selector interface{}) *ProviderMock_GetSecret_Call {
	return &ProviderMock_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, selector)}
}

func (_c *ProviderMock_GetSecret_Call) Run(run func(ctx context.Context, selector provider.Selector)) *ProviderMock_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 provider.Selector
		if args[1] != nil {
			arg1 = args[1].(provider.Selector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProviderMock_GetSecret_Call) Return(v provider.Secret, err error) *ProviderMock_GetSecret_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *ProviderMock_GetSecret_Call) RunAndReturn(run func(ctx context.Context, selector provider.Selector) (provider.Secret, error)) *ProviderMock_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretSet provides a mock function for the type ProviderMock
func (_mock *ProviderMock) GetSecretSet(ctx context.Context, selector provider.Selector) ([]provider.Secret, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretSet")
	}

	var r0 []provider.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, provider.Selector) ([]provider.Secret, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, provider.Selector) []provider.Secret); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]provider.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, provider.Selector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProviderMock_GetSecretSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretSet'
type ProviderMock_GetSecretSet_Call struct {
	*mock.Call
}

// GetSecretSet is a helper method to define mock.On call
//   - ctx context.Context
//   - selector provider.Selector
func (_e *ProviderMock_Expecter) GetSecretSet(ctx interface{}, selector interface{}) *ProviderMock_GetSecretSet_Call {
	return &ProviderMock_GetSecretSet_Call{Call: _e.mock.On("GetSecretSet", ctx, selector)}
}

func (_c *ProviderMock_GetSecretSet_Call) Run(run func(ctx context.Context, selector provider.Selector)) *ProviderMock_GetSecretSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 provider.Selector
		if args[1] != nil {
			arg1 = args[1].(provider.Selector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProviderMock_GetSecretSet_Call) Return(vs []provider.Secret, err error) *ProviderMock_GetSecretSet_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *ProviderMock_GetSecretSet_Call) RunAndReturn(run func(ctx context.Context, selector provider.Selector) ([]provider.Secret, error)) *ProviderMock_GetSecretSet_Call {
	_c.Call.Return(run)
	return _c
}

// IsNamespaceAware provides a mock function for the type ProviderMock
func (_mock *ProviderMock) IsNamespaceAware() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsNamespaceAware")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ProviderMock_IsNamespaceAware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNamespaceAware'
type ProviderMock_IsNamespaceAware_Call struct {
	*mock.Call
}

// IsNamespaceAware is a helper method to define mock.On call
func (_e *ProviderMock_Expecter) IsNamespaceAware() *ProviderMock_IsNamespaceAware_Call {
	return &ProviderMock_IsNamespaceAware_Call{Call: _e.mock.On("IsNamespaceAware")}
}

func (_c *ProviderMock_IsNamespaceAware_Call) Run(run func()) *ProviderMock_IsNamespaceAware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProviderMock_IsNamespaceAware_Call) Return(b bool) *ProviderMock_IsNamespaceAware_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ProviderMock_IsNamespaceAware_Call) RunAndReturn(run func() bool) *ProviderMock_IsNamespaceAware_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type ProviderMock
func (_mock *ProviderMock) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProviderMock_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ProviderMock_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ProviderMock_Expecter) Start(ctx interface{}) *ProviderMock_Start_Call {
	return &ProviderMock_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *ProviderMock_Start_Call) Run(run func(ctx context.Context)) *ProviderMock_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProviderMock_Start_Call) Return(err error) *ProviderMock_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProviderMock_Start_Call) RunAndReturn(run func(ctx context.Context) error) *ProviderMock_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type ProviderMock
func (_mock *ProviderMock) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProviderMock_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type ProviderMock_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ProviderMock_Expecter) Stop(ctx interface{}) *ProviderMock_Stop_Call {
	return &ProviderMock_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *ProviderMock_Stop_Call) Run(run func(ctx context.Context)) *ProviderMock_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProviderMock_Stop_Call) Return(err error) *ProviderMock_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProviderMock_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *ProviderMock_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type ProviderMock
func (_mock *ProviderMock) Type() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ProviderMock_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type ProviderMock_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *ProviderMock_Expecter) Type() *ProviderMock_Type_Call {
	return &ProviderMock_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *ProviderMock_Type_Call) Run(run func()) *ProviderMock_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProviderMock_Type_Call) Return(s string) *ProviderMock_Type_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ProviderMock_Type_Call) RunAndReturn(run func() string) *ProviderMock_Type_Call {
	_c.Call.Return(run)
	return _c
}
