// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewInsecureMock creates a new instance of InsecureMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInsecureMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *InsecureMock {
	mock := &InsecureMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InsecureMock is an autogenerated mock type for the Insecure type
type InsecureMock struct {
	mock.Mock
}

type InsecureMock_Expecter struct {
	mock *mock.Mock
}

func (_m *InsecureMock) EXPECT() *InsecureMock_Expecter {
	return &InsecureMock_Expecter{mock: &_m.Mock}
}

// IsInsecure provides a mock function for the type InsecureMock
func (_mock *InsecureMock) IsInsecure() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInsecure")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// InsecureMock_IsInsecure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInsecure'
type InsecureMock_IsInsecure_Call struct {
	*mock.Call
}

// IsInsecure is a helper method to define mock.On call
func (_e *InsecureMock_Expecter) IsInsecure() *InsecureMock_IsInsecure_Call {
	return &InsecureMock_IsInsecure_Call{Call: _e.mock.On("IsInsecure")}
}

func (_c *InsecureMock_IsInsecure_Call) Run(run func()) *InsecureMock_IsInsecure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InsecureMock_IsInsecure_Call) Return(b bool) *InsecureMock_IsInsecure_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *InsecureMock_IsInsecure_Call) RunAndReturn(run func() bool) *InsecureMock_IsInsecure_Call {
	_c.Call.Return(run)
	return _c
}
