// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPrincipalNamerMock creates a new instance of PrincipalNamerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrincipalNamerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrincipalNamerMock {
	mock := &PrincipalNamerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PrincipalNamerMock is an autogenerated mock type for the PrincipalNamer type
type PrincipalNamerMock struct {
	mock.Mock
}

type PrincipalNamerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PrincipalNamerMock) EXPECT() *PrincipalNamerMock_Expecter {
	return &PrincipalNamerMock_Expecter{mock: &_m.Mock}
}

// PrincipalName provides a mock function for the type PrincipalNamerMock
func (_mock *PrincipalNamerMock) PrincipalName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PrincipalName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// PrincipalNamerMock_PrincipalName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrincipalName'
type PrincipalNamerMock_PrincipalName_Call struct {
	*mock.Call
}

// PrincipalName is a helper method to define mock.On call
func (_e *PrincipalNamerMock_Expecter) PrincipalName() *PrincipalNamerMock_PrincipalName_Call {
	return &PrincipalNamerMock_PrincipalName_Call{Call: _e.mock.On("PrincipalName")}
}

func (_c *PrincipalNamerMock_PrincipalName_Call) Run(run func()) *PrincipalNamerMock_PrincipalName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PrincipalNamerMock_PrincipalName_Call) Return(s string) *PrincipalNamerMock_PrincipalName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *PrincipalNamerMock_PrincipalName_Call) RunAndReturn(run func() string) *PrincipalNamerMock_PrincipalName_Call {
	_c.Call.Return(run)
	return _c
}
