// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RequestFunctionsMock is an autogenerated mock type for the RequestFunctions type
type RequestFunctionsMock struct {
	mock.Mock
}

type RequestFunctionsMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RequestFunctionsMock) EXPECT() *RequestFunctionsMock_Expecter {
	return &RequestFunctionsMock_Expecter{mock: &_m.Mock}
}

// Body provides a mock function with given fields:
func (_m *RequestFunctionsMock) Body() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Body")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// RequestFunctionsMock_Body_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Body'
type RequestFunctionsMock_Body_Call struct {
	*mock.Call
}

// Body is a helper method to define mock.On call
func (_e *RequestFunctionsMock_Expecter) Body() *RequestFunctionsMock_Body_Call {
	return &RequestFunctionsMock_Body_Call{Call: _e.mock.On("Body")}
}

func (_c *RequestFunctionsMock_Body_Call) Run(run func()) *RequestFunctionsMock_Body_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RequestFunctionsMock_Body_Call) Return(_a0 interface{}) *RequestFunctionsMock_Body_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestFunctionsMock_Body_Call) RunAndReturn(run func() interface{}) *RequestFunctionsMock_Body_Call {
	_c.Call.Return(run)
	return _c
}

// Cookie provides a mock function with given fields: name
func (_m *RequestFunctionsMock) Cookie(name string) string {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Cookie")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RequestFunctionsMock_Cookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cookie'
type RequestFunctionsMock_Cookie_Call struct {
	*mock.Call
}

// Cookie is a helper method to define mock.On call
//   - name string
func (_e *RequestFunctionsMock_Expecter) Cookie(name interface{}) *RequestFunctionsMock_Cookie_Call {
	return &RequestFunctionsMock_Cookie_Call{Call: _e.mock.On("Cookie", name)}
}

func (_c *RequestFunctionsMock_Cookie_Call) Run(run func(name string)) *RequestFunctionsMock_Cookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RequestFunctionsMock_Cookie_Call) Return(_a0 string) *RequestFunctionsMock_Cookie_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestFunctionsMock_Cookie_Call) RunAndReturn(run func(string) string) *RequestFunctionsMock_Cookie_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function with given fields: name
func (_m *RequestFunctionsMock) Header(name string) string {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RequestFunctionsMock_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type RequestFunctionsMock_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
//   - name string
func (_e *RequestFunctionsMock_Expecter) Header(name interface{}) *RequestFunctionsMock_Header_Call {
	return &RequestFunctionsMock_Header_Call{Call: _e.mock.On("Header", name)}
}

func (_c *RequestFunctionsMock_Header_Call) Run(run func(name string)) *RequestFunctionsMock_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RequestFunctionsMock_Header_Call) Return(_a0 string) *RequestFunctionsMock_Header_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestFunctionsMock_Header_Call) RunAndReturn(run func(string) string) *RequestFunctionsMock_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Headers provides a mock function with given fields:
func (_m *RequestFunctionsMock) Headers() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Headers")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// RequestFunctionsMock_Headers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Headers'
type RequestFunctionsMock_Headers_Call struct {
	*mock.Call
}

// Headers is a helper method to define mock.On call
func (_e *RequestFunctionsMock_Expecter) Headers() *RequestFunctionsMock_Headers_Call {
	return &RequestFunctionsMock_Headers_Call{Call: _e.mock.On("Headers")}
}

func (_c *RequestFunctionsMock_Headers_Call) Run(run func()) *RequestFunctionsMock_Headers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RequestFunctionsMock_Headers_Call) Return(_a0 map[string]string) *RequestFunctionsMock_Headers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestFunctionsMock_Headers_Call) RunAndReturn(run func() map[string]string) *RequestFunctionsMock_Headers_Call {
	_c.Call.Return(run)
	return _c
}

// NewRequestFunctionsMock creates a new instance of RequestFunctionsMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestFunctionsMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestFunctionsMock {
	mock := &RequestFunctionsMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
