// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	heimdall "github.com/dadrus/heimdall/internal/heimdall"
	mock "github.com/stretchr/testify/mock"
)

// RequestContextMock is an autogenerated mock type for the RequestContext type
type RequestContextMock struct {
	mock.Mock
}

type RequestContextMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RequestContextMock) EXPECT() *RequestContextMock_Expecter {
	return &RequestContextMock_Expecter{mock: &_m.Mock}
}

// AddCookieForUpstream provides a mock function with given fields: name, value
func (_m *RequestContextMock) AddCookieForUpstream(name string, value string) {
	_m.Called(name, value)
}

// RequestContextMock_AddCookieForUpstream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCookieForUpstream'
type RequestContextMock_AddCookieForUpstream_Call struct {
	*mock.Call
}

// AddCookieForUpstream is a helper method to define mock.On call
//   - name string
//   - value string
func (_e *RequestContextMock_Expecter) AddCookieForUpstream(name interface{}, value interface{}) *RequestContextMock_AddCookieForUpstream_Call {
	return &RequestContextMock_AddCookieForUpstream_Call{Call: _e.mock.On("AddCookieForUpstream", name, value)}
}

func (_c *RequestContextMock_AddCookieForUpstream_Call) Run(run func(name string, value string)) *RequestContextMock_AddCookieForUpstream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RequestContextMock_AddCookieForUpstream_Call) Return() *RequestContextMock_AddCookieForUpstream_Call {
	_c.Call.Return()
	return _c
}

func (_c *RequestContextMock_AddCookieForUpstream_Call) RunAndReturn(run func(string, string)) *RequestContextMock_AddCookieForUpstream_Call {
	_c.Call.Return(run)
	return _c
}

// AddHeaderForUpstream provides a mock function with given fields: name, value
func (_m *RequestContextMock) AddHeaderForUpstream(name string, value string) {
	_m.Called(name, value)
}

// RequestContextMock_AddHeaderForUpstream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHeaderForUpstream'
type RequestContextMock_AddHeaderForUpstream_Call struct {
	*mock.Call
}

// AddHeaderForUpstream is a helper method to define mock.On call
//   - name string
//   - value string
func (_e *RequestContextMock_Expecter) AddHeaderForUpstream(name interface{}, value interface{}) *RequestContextMock_AddHeaderForUpstream_Call {
	return &RequestContextMock_AddHeaderForUpstream_Call{Call: _e.mock.On("AddHeaderForUpstream", name, value)}
}

func (_c *RequestContextMock_AddHeaderForUpstream_Call) Run(run func(name string, value string)) *RequestContextMock_AddHeaderForUpstream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RequestContextMock_AddHeaderForUpstream_Call) Return() *RequestContextMock_AddHeaderForUpstream_Call {
	_c.Call.Return()
	return _c
}

func (_c *RequestContextMock_AddHeaderForUpstream_Call) RunAndReturn(run func(string, string)) *RequestContextMock_AddHeaderForUpstream_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with given fields:
func (_m *RequestContextMock) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// RequestContextMock_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type RequestContextMock_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *RequestContextMock_Expecter) Context() *RequestContextMock_Context_Call {
	return &RequestContextMock_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *RequestContextMock_Context_Call) Run(run func()) *RequestContextMock_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RequestContextMock_Context_Call) Return(_a0 context.Context) *RequestContextMock_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestContextMock_Context_Call) RunAndReturn(run func() context.Context) *RequestContextMock_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Outputs provides a mock function with given fields:
func (_m *RequestContextMock) Outputs() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Outputs")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// RequestContextMock_Outputs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Outputs'
type RequestContextMock_Outputs_Call struct {
	*mock.Call
}

// Outputs is a helper method to define mock.On call
func (_e *RequestContextMock_Expecter) Outputs() *RequestContextMock_Outputs_Call {
	return &RequestContextMock_Outputs_Call{Call: _e.mock.On("Outputs")}
}

func (_c *RequestContextMock_Outputs_Call) Run(run func()) *RequestContextMock_Outputs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RequestContextMock_Outputs_Call) Return(_a0 map[string]interface{}) *RequestContextMock_Outputs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestContextMock_Outputs_Call) RunAndReturn(run func() map[string]interface{}) *RequestContextMock_Outputs_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function with given fields:
func (_m *RequestContextMock) Request() *heimdall.Request {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 *heimdall.Request
	if rf, ok := ret.Get(0).(func() *heimdall.Request); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*heimdall.Request)
		}
	}

	return r0
}

// RequestContextMock_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type RequestContextMock_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
func (_e *RequestContextMock_Expecter) Request() *RequestContextMock_Request_Call {
	return &RequestContextMock_Request_Call{Call: _e.mock.On("Request")}
}

func (_c *RequestContextMock_Request_Call) Run(run func()) *RequestContextMock_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RequestContextMock_Request_Call) Return(_a0 *heimdall.Request) *RequestContextMock_Request_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestContextMock_Request_Call) RunAndReturn(run func() *heimdall.Request) *RequestContextMock_Request_Call {
	_c.Call.Return(run)
	return _c
}

// SetPipelineError provides a mock function with given fields: err
func (_m *RequestContextMock) SetPipelineError(err error) {
	_m.Called(err)
}

// RequestContextMock_SetPipelineError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPipelineError'
type RequestContextMock_SetPipelineError_Call struct {
	*mock.Call
}

// SetPipelineError is a helper method to define mock.On call
//   - err error
func (_e *RequestContextMock_Expecter) SetPipelineError(err interface{}) *RequestContextMock_SetPipelineError_Call {
	return &RequestContextMock_SetPipelineError_Call{Call: _e.mock.On("SetPipelineError", err)}
}

func (_c *RequestContextMock_SetPipelineError_Call) Run(run func(err error)) *RequestContextMock_SetPipelineError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *RequestContextMock_SetPipelineError_Call) Return() *RequestContextMock_SetPipelineError_Call {
	_c.Call.Return()
	return _c
}

func (_c *RequestContextMock_SetPipelineError_Call) RunAndReturn(run func(error)) *RequestContextMock_SetPipelineError_Call {
	_c.Call.Return(run)
	return _c
}

// NewRequestContextMock creates a new instance of RequestContextMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestContextMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestContextMock {
	mock := &RequestContextMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
