controller:
  config:
    global-auth-url: https://heimdall.heimdall.svc.cluster.local:4455
    global-auth-response-headers: "Authorization"
    global-auth-snippet: |
      proxy_set_header         X-Forwarded-Method     $request_method;
      proxy_set_header         X-Forwarded-Proto      $scheme;
      proxy_set_header         X-Forwarded-Host       $http_host;
      proxy_set_header         X-Forwarded-Uri        $request_uri;
    enable-opentelemetry: "true"
    opentelemetry-config: "/etc/nginx/opentelemetry.toml"
    opentelemetry-operation-name: "HTTP $request_method $service_name $uri"
    opentelemetry-trust-incoming-span: "true"
    otlp-collector-host: "alloy.monitoring"
    otlp-collector-port: "4317"
    otel-max-queuesize: "2048"
    otel-schedule-delay-millis: "5000"
    otel-max-export-batch-size: "512"
    otel-service-name: "nginx-ingress" # Opentelemetry resource name
    otel-sampler: "AlwaysOn" # Also: AlwaysOff, TraceIdRatioBased
    otel-sampler-ratio: "1.0"

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
