controller:
  config:
    global-auth-url: https://heimdall.heimdall.svc.cluster.local:4456
    global-auth-response-headers: "Authorization"
    global-auth-snippet: |
      proxy_set_header         X-Forwarded-Method     $request_method;
      proxy_set_header         X-Forwarded-Proto      $scheme;
      proxy_set_header         X-Forwarded-Host       $http_host;
      proxy_set_header         X-Forwarded-Uri        $request_uri;