// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	authenticators "github.com/dadrus/heimdall/internal/rules/mechanisms/authenticators"
	authorizers "github.com/dadrus/heimdall/internal/rules/mechanisms/authorizers"

	config "github.com/dadrus/heimdall/internal/config"

	contextualizers "github.com/dadrus/heimdall/internal/rules/mechanisms/contextualizers"

	errorhandlers "github.com/dadrus/heimdall/internal/rules/mechanisms/errorhandlers"

	finalizers "github.com/dadrus/heimdall/internal/rules/mechanisms/finalizers"

	mock "github.com/stretchr/testify/mock"
)

// MechanismFactoryMock is an autogenerated mock type for the MechanismFactory type
type MechanismFactoryMock struct {
	mock.Mock
}

type MechanismFactoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MechanismFactoryMock) EXPECT() *MechanismFactoryMock_Expecter {
	return &MechanismFactoryMock_Expecter{mock: &_m.Mock}
}

// CreateAuthenticator provides a mock function with given fields: version, id, conf
func (_m *MechanismFactoryMock) CreateAuthenticator(version string, id string, conf config.MechanismConfig) (authenticators.Authenticator, error) {
	ret := _m.Called(version, id, conf)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthenticator")
	}

	var r0 authenticators.Authenticator
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, config.MechanismConfig) (authenticators.Authenticator, error)); ok {
		return rf(version, id, conf)
	}
	if rf, ok := ret.Get(0).(func(string, string, config.MechanismConfig) authenticators.Authenticator); ok {
		r0 = rf(version, id, conf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authenticators.Authenticator)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, config.MechanismConfig) error); ok {
		r1 = rf(version, id, conf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MechanismFactoryMock_CreateAuthenticator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthenticator'
type MechanismFactoryMock_CreateAuthenticator_Call struct {
	*mock.Call
}

// CreateAuthenticator is a helper method to define mock.On call
//   - version string
//   - id string
//   - conf config.MechanismConfig
func (_e *MechanismFactoryMock_Expecter) CreateAuthenticator(version interface{}, id interface{}, conf interface{}) *MechanismFactoryMock_CreateAuthenticator_Call {
	return &MechanismFactoryMock_CreateAuthenticator_Call{Call: _e.mock.On("CreateAuthenticator", version, id, conf)}
}

func (_c *MechanismFactoryMock_CreateAuthenticator_Call) Run(run func(version string, id string, conf config.MechanismConfig)) *MechanismFactoryMock_CreateAuthenticator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(config.MechanismConfig))
	})
	return _c
}

func (_c *MechanismFactoryMock_CreateAuthenticator_Call) Return(_a0 authenticators.Authenticator, _a1 error) *MechanismFactoryMock_CreateAuthenticator_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MechanismFactoryMock_CreateAuthenticator_Call) RunAndReturn(run func(string, string, config.MechanismConfig) (authenticators.Authenticator, error)) *MechanismFactoryMock_CreateAuthenticator_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAuthorizer provides a mock function with given fields: version, id, conf
func (_m *MechanismFactoryMock) CreateAuthorizer(version string, id string, conf config.MechanismConfig) (authorizers.Authorizer, error) {
	ret := _m.Called(version, id, conf)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthorizer")
	}

	var r0 authorizers.Authorizer
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, config.MechanismConfig) (authorizers.Authorizer, error)); ok {
		return rf(version, id, conf)
	}
	if rf, ok := ret.Get(0).(func(string, string, config.MechanismConfig) authorizers.Authorizer); ok {
		r0 = rf(version, id, conf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authorizers.Authorizer)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, config.MechanismConfig) error); ok {
		r1 = rf(version, id, conf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MechanismFactoryMock_CreateAuthorizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthorizer'
type MechanismFactoryMock_CreateAuthorizer_Call struct {
	*mock.Call
}

// CreateAuthorizer is a helper method to define mock.On call
//   - version string
//   - id string
//   - conf config.MechanismConfig
func (_e *MechanismFactoryMock_Expecter) CreateAuthorizer(version interface{}, id interface{}, conf interface{}) *MechanismFactoryMock_CreateAuthorizer_Call {
	return &MechanismFactoryMock_CreateAuthorizer_Call{Call: _e.mock.On("CreateAuthorizer", version, id, conf)}
}

func (_c *MechanismFactoryMock_CreateAuthorizer_Call) Run(run func(version string, id string, conf config.MechanismConfig)) *MechanismFactoryMock_CreateAuthorizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(config.MechanismConfig))
	})
	return _c
}

func (_c *MechanismFactoryMock_CreateAuthorizer_Call) Return(_a0 authorizers.Authorizer, _a1 error) *MechanismFactoryMock_CreateAuthorizer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MechanismFactoryMock_CreateAuthorizer_Call) RunAndReturn(run func(string, string, config.MechanismConfig) (authorizers.Authorizer, error)) *MechanismFactoryMock_CreateAuthorizer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateContextualizer provides a mock function with given fields: version, id, conf
func (_m *MechanismFactoryMock) CreateContextualizer(version string, id string, conf config.MechanismConfig) (contextualizers.Contextualizer, error) {
	ret := _m.Called(version, id, conf)

	if len(ret) == 0 {
		panic("no return value specified for CreateContextualizer")
	}

	var r0 contextualizers.Contextualizer
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, config.MechanismConfig) (contextualizers.Contextualizer, error)); ok {
		return rf(version, id, conf)
	}
	if rf, ok := ret.Get(0).(func(string, string, config.MechanismConfig) contextualizers.Contextualizer); ok {
		r0 = rf(version, id, conf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contextualizers.Contextualizer)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, config.MechanismConfig) error); ok {
		r1 = rf(version, id, conf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MechanismFactoryMock_CreateContextualizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateContextualizer'
type MechanismFactoryMock_CreateContextualizer_Call struct {
	*mock.Call
}

// CreateContextualizer is a helper method to define mock.On call
//   - version string
//   - id string
//   - conf config.MechanismConfig
func (_e *MechanismFactoryMock_Expecter) CreateContextualizer(version interface{}, id interface{}, conf interface{}) *MechanismFactoryMock_CreateContextualizer_Call {
	return &MechanismFactoryMock_CreateContextualizer_Call{Call: _e.mock.On("CreateContextualizer", version, id, conf)}
}

func (_c *MechanismFactoryMock_CreateContextualizer_Call) Run(run func(version string, id string, conf config.MechanismConfig)) *MechanismFactoryMock_CreateContextualizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(config.MechanismConfig))
	})
	return _c
}

func (_c *MechanismFactoryMock_CreateContextualizer_Call) Return(_a0 contextualizers.Contextualizer, _a1 error) *MechanismFactoryMock_CreateContextualizer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MechanismFactoryMock_CreateContextualizer_Call) RunAndReturn(run func(string, string, config.MechanismConfig) (contextualizers.Contextualizer, error)) *MechanismFactoryMock_CreateContextualizer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateErrorHandler provides a mock function with given fields: version, id, conf
func (_m *MechanismFactoryMock) CreateErrorHandler(version string, id string, conf config.MechanismConfig) (errorhandlers.ErrorHandler, error) {
	ret := _m.Called(version, id, conf)

	if len(ret) == 0 {
		panic("no return value specified for CreateErrorHandler")
	}

	var r0 errorhandlers.ErrorHandler
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, config.MechanismConfig) (errorhandlers.ErrorHandler, error)); ok {
		return rf(version, id, conf)
	}
	if rf, ok := ret.Get(0).(func(string, string, config.MechanismConfig) errorhandlers.ErrorHandler); ok {
		r0 = rf(version, id, conf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errorhandlers.ErrorHandler)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, config.MechanismConfig) error); ok {
		r1 = rf(version, id, conf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MechanismFactoryMock_CreateErrorHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateErrorHandler'
type MechanismFactoryMock_CreateErrorHandler_Call struct {
	*mock.Call
}

// CreateErrorHandler is a helper method to define mock.On call
//   - version string
//   - id string
//   - conf config.MechanismConfig
func (_e *MechanismFactoryMock_Expecter) CreateErrorHandler(version interface{}, id interface{}, conf interface{}) *MechanismFactoryMock_CreateErrorHandler_Call {
	return &MechanismFactoryMock_CreateErrorHandler_Call{Call: _e.mock.On("CreateErrorHandler", version, id, conf)}
}

func (_c *MechanismFactoryMock_CreateErrorHandler_Call) Run(run func(version string, id string, conf config.MechanismConfig)) *MechanismFactoryMock_CreateErrorHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(config.MechanismConfig))
	})
	return _c
}

func (_c *MechanismFactoryMock_CreateErrorHandler_Call) Return(_a0 errorhandlers.ErrorHandler, _a1 error) *MechanismFactoryMock_CreateErrorHandler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MechanismFactoryMock_CreateErrorHandler_Call) RunAndReturn(run func(string, string, config.MechanismConfig) (errorhandlers.ErrorHandler, error)) *MechanismFactoryMock_CreateErrorHandler_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFinalizer provides a mock function with given fields: version, id, conf
func (_m *MechanismFactoryMock) CreateFinalizer(version string, id string, conf config.MechanismConfig) (finalizers.Finalizer, error) {
	ret := _m.Called(version, id, conf)

	if len(ret) == 0 {
		panic("no return value specified for CreateFinalizer")
	}

	var r0 finalizers.Finalizer
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, config.MechanismConfig) (finalizers.Finalizer, error)); ok {
		return rf(version, id, conf)
	}
	if rf, ok := ret.Get(0).(func(string, string, config.MechanismConfig) finalizers.Finalizer); ok {
		r0 = rf(version, id, conf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(finalizers.Finalizer)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, config.MechanismConfig) error); ok {
		r1 = rf(version, id, conf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MechanismFactoryMock_CreateFinalizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFinalizer'
type MechanismFactoryMock_CreateFinalizer_Call struct {
	*mock.Call
}

// CreateFinalizer is a helper method to define mock.On call
//   - version string
//   - id string
//   - conf config.MechanismConfig
func (_e *MechanismFactoryMock_Expecter) CreateFinalizer(version interface{}, id interface{}, conf interface{}) *MechanismFactoryMock_CreateFinalizer_Call {
	return &MechanismFactoryMock_CreateFinalizer_Call{Call: _e.mock.On("CreateFinalizer", version, id, conf)}
}

func (_c *MechanismFactoryMock_CreateFinalizer_Call) Run(run func(version string, id string, conf config.MechanismConfig)) *MechanismFactoryMock_CreateFinalizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(config.MechanismConfig))
	})
	return _c
}

func (_c *MechanismFactoryMock_CreateFinalizer_Call) Return(_a0 finalizers.Finalizer, _a1 error) *MechanismFactoryMock_CreateFinalizer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MechanismFactoryMock_CreateFinalizer_Call) RunAndReturn(run func(string, string, config.MechanismConfig) (finalizers.Finalizer, error)) *MechanismFactoryMock_CreateFinalizer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMechanismFactoryMock creates a new instance of MechanismFactoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMechanismFactoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MechanismFactoryMock {
	mock := &MechanismFactoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
