// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dadrus/heimdall/internal/rules/mechanisms/types"
	mock "github.com/stretchr/testify/mock"
)

// NewRepositoryMock creates a new instance of RepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryMock {
	mock := &RepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepositoryMock is an autogenerated mock type for the Repository type
type RepositoryMock struct {
	mock.Mock
}

type RepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryMock) EXPECT() *RepositoryMock_Expecter {
	return &RepositoryMock_Expecter{mock: &_m.Mock}
}

// Authenticator provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) Authenticator(name string) (types.Mechanism, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Authenticator")
	}

	var r0 types.Mechanism
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.Mechanism, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.Mechanism); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Mechanism)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_Authenticator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticator'
type RepositoryMock_Authenticator_Call struct {
	*mock.Call
}

// Authenticator is a helper method to define mock.On call
//   - name string
func (_e *RepositoryMock_Expecter) Authenticator(name interface{}) *RepositoryMock_Authenticator_Call {
	return &RepositoryMock_Authenticator_Call{Call: _e.mock.On("Authenticator", name)}
}

func (_c *RepositoryMock_Authenticator_Call) Run(run func(name string)) *RepositoryMock_Authenticator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryMock_Authenticator_Call) Return(mechanism types.Mechanism, err error) *RepositoryMock_Authenticator_Call {
	_c.Call.Return(mechanism, err)
	return _c
}

func (_c *RepositoryMock_Authenticator_Call) RunAndReturn(run func(name string) (types.Mechanism, error)) *RepositoryMock_Authenticator_Call {
	_c.Call.Return(run)
	return _c
}

// Authorizer provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) Authorizer(name string) (types.Mechanism, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Authorizer")
	}

	var r0 types.Mechanism
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.Mechanism, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.Mechanism); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Mechanism)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_Authorizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorizer'
type RepositoryMock_Authorizer_Call struct {
	*mock.Call
}

// Authorizer is a helper method to define mock.On call
//   - name string
func (_e *RepositoryMock_Expecter) Authorizer(name interface{}) *RepositoryMock_Authorizer_Call {
	return &RepositoryMock_Authorizer_Call{Call: _e.mock.On("Authorizer", name)}
}

func (_c *RepositoryMock_Authorizer_Call) Run(run func(name string)) *RepositoryMock_Authorizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryMock_Authorizer_Call) Return(mechanism types.Mechanism, err error) *RepositoryMock_Authorizer_Call {
	_c.Call.Return(mechanism, err)
	return _c
}

func (_c *RepositoryMock_Authorizer_Call) RunAndReturn(run func(name string) (types.Mechanism, error)) *RepositoryMock_Authorizer_Call {
	_c.Call.Return(run)
	return _c
}

// Contextualizer provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) Contextualizer(name string) (types.Mechanism, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Contextualizer")
	}

	var r0 types.Mechanism
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.Mechanism, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.Mechanism); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Mechanism)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_Contextualizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Contextualizer'
type RepositoryMock_Contextualizer_Call struct {
	*mock.Call
}

// Contextualizer is a helper method to define mock.On call
//   - name string
func (_e *RepositoryMock_Expecter) Contextualizer(name interface{}) *RepositoryMock_Contextualizer_Call {
	return &RepositoryMock_Contextualizer_Call{Call: _e.mock.On("Contextualizer", name)}
}

func (_c *RepositoryMock_Contextualizer_Call) Run(run func(name string)) *RepositoryMock_Contextualizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryMock_Contextualizer_Call) Return(mechanism types.Mechanism, err error) *RepositoryMock_Contextualizer_Call {
	_c.Call.Return(mechanism, err)
	return _c
}

func (_c *RepositoryMock_Contextualizer_Call) RunAndReturn(run func(name string) (types.Mechanism, error)) *RepositoryMock_Contextualizer_Call {
	_c.Call.Return(run)
	return _c
}

// ErrorHandler provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) ErrorHandler(name string) (types.Mechanism, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ErrorHandler")
	}

	var r0 types.Mechanism
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.Mechanism, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.Mechanism); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Mechanism)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_ErrorHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorHandler'
type RepositoryMock_ErrorHandler_Call struct {
	*mock.Call
}

// ErrorHandler is a helper method to define mock.On call
//   - name string
func (_e *RepositoryMock_Expecter) ErrorHandler(name interface{}) *RepositoryMock_ErrorHandler_Call {
	return &RepositoryMock_ErrorHandler_Call{Call: _e.mock.On("ErrorHandler", name)}
}

func (_c *RepositoryMock_ErrorHandler_Call) Run(run func(name string)) *RepositoryMock_ErrorHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryMock_ErrorHandler_Call) Return(mechanism types.Mechanism, err error) *RepositoryMock_ErrorHandler_Call {
	_c.Call.Return(mechanism, err)
	return _c
}

func (_c *RepositoryMock_ErrorHandler_Call) RunAndReturn(run func(name string) (types.Mechanism, error)) *RepositoryMock_ErrorHandler_Call {
	_c.Call.Return(run)
	return _c
}

// Finalizer provides a mock function for the type RepositoryMock
func (_mock *RepositoryMock) Finalizer(name string) (types.Mechanism, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Finalizer")
	}

	var r0 types.Mechanism
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.Mechanism, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.Mechanism); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Mechanism)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryMock_Finalizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finalizer'
type RepositoryMock_Finalizer_Call struct {
	*mock.Call
}

// Finalizer is a helper method to define mock.On call
//   - name string
func (_e *RepositoryMock_Expecter) Finalizer(name interface{}) *RepositoryMock_Finalizer_Call {
	return &RepositoryMock_Finalizer_Call{Call: _e.mock.On("Finalizer", name)}
}

func (_c *RepositoryMock_Finalizer_Call) Run(run func(name string)) *RepositoryMock_Finalizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryMock_Finalizer_Call) Return(mechanism types.Mechanism, err error) *RepositoryMock_Finalizer_Call {
	_c.Call.Return(mechanism, err)
	return _c
}

func (_c *RepositoryMock_Finalizer_Call) RunAndReturn(run func(name string) (types.Mechanism, error)) *RepositoryMock_Finalizer_Call {
	_c.Call.Return(run)
	return _c
}
