---
title: "Pipelines"
date: 2022-11-29T22:29:36+02:00
draft: false
weight: 11
menu:
  docs:
    parent: "Concepts"
    weight: 1
description: Pipelines let you orchestrate existing authentication and authorization systems via mechanisms.
---

:toc:

== Overview

Pipelines are specified in link:{{< relref "/docs/concepts/rules.adoc" >}}[rules] and are used to authenticate and authorize the particular requests, as well as to handle encountered errors.

As described in the link:{{< relref "/docs/getting_started/discover_heimdall.adoc" >}}[Discover heimdall] chapter and also shown in the diagram below, central aspects of heimdall are upstream specific pipelines, which allow you orchestrating different services to authenticate, enrich and authorize incoming HTTP requests, transform the resulting subject information into a format, or obtain credentials required for the communication with the particular upstream services.

[[_fig_heimdall_request_pipeline]]
.Authentication & Authorization Pipeline
[ditaa, format=svg]
....
                 /-----------------------------------------------------------------------------------\
                 |                                                                                   |
                 :                     Authentication & Authorization Pipeline                       |<- controlled by> --+
                 |                                                                                   |                    |
                 |+------------------+ +------------------+ +------------------+ +------------------+|                    |
                 || cCCC             | | cCCC             | | cCCC             | | cCCC             ||                    :
                 || 1. Authenticate  | | 2. Contextualize | | 3. Authorize     | | 4. Finalize      ||                    |
                 ||                  | |                  | |                  | |                  ||   +------------------+
                 |+------------------+ +------------------+ +------------------+ +------------------+|   |                  |
                 |                                                                                   |   |                  |
+------------+   |                                                                                   |   |   Microservice   |
|            |   |                                                                                   |   |                  |
|   Client   |   |                             Client Request Journey                                |   |                  |
|            |------------------------------------------------------------------------------------------>|                  |
|            |   :                                                                                   |   |                  |
|            |   \-----------------------------------------------------------------------------------/   |                  |
+------------+                                                                                           +------------------+
....

== Authentication & Authorization Pipeline

Even the figure above shows four steps, these are actually organized in three stages as depicted in the diagram below. Each of these stages is assembled by as many link:{{< relref "/docs/concepts/mechanisms.adoc" >}}[mechanisms] (which represent the actual steps), as required to fulfill the corresponding requirements.

.Pipeline Stages
[ditaa, format=svg]
....
                 /----------------------------------------------------------------------------------------\
                 |                                                                                        |
                 :                     Authentication & Authorization Pipeline                            |<- controlled by> --+
                 |                                                                                        |                    |
                 |+--------------------------+  +--------------------------+  +--------------------------+|                    |
                 || cCCC                     |  | cCCC                     |  | cCCC                     ||                    :
                 || Authentication           |  | Contextualization &      |  | Finalization             ||                    |
                 || Stage                    |  | Authorization Stage      |  | Stage                    ||                    |
                 ||                          |  |                          |  |                          ||                    |
                 ||   ---------------------+ |  |   ---------------------+ |  |   ---------------------+ ||   +----------------+-+
                 || +--------------------+ | |  | +--------------------+ | |  | +--------------------+ | ||   |                  |
                 || |     Mechanism      |-+ |  | |     Mechanism      |-+ |  | |     Mechanism      |-+ ||   |                  |
                 || +--------------------+   |  | +--------------------+   |  | +--------------------+   ||   |                  |
+------------+   |+--------------------------+  +--------------------------+  +--------------------------+|   |   Microservice   |
|            |   |           |                     |               |                                      |   |                  |
|   Client   |   |           |                     |               |  Client Request Journey              |   |                  |
|            |------------------------------------------------------------------------------------------->|   |                  |
|            |   :           :                     :               :                                      |   |                  |
|            |   |           |                     |               |                                      |   |                  |
|            |   \----------------------------------------------------------------------------------------/   |                  |
+------------+               |                     |               |                                          +------------------+
                             :                     :               :
                             v                     v               v
                  +----------------+     +----------------+     +----------------+
                  |                |-+   |                |-+   |                |-+
                  | Authentication | |   | Some other     | |   | Authorization  | |
                  |                | |   |                | |   |                | |
                  |  System        | |   |  System        | |   |  System        | |
                  |                | |   |                | |   |                | |
                  +----------------+ |   +----------------+ |   +----------------+ |
                     ----------------+      ----------------+      ----------------+
....

* **Authentication Stage:** In that stage you can use any amount of link:{{< relref "/docs/mechanisms/authenticators.adoc" >}}[authentication] mechanisms, to let heimdall communicate with the actual authentication systems. This can be getting information about the authenticated subject of the request, getting key material to verify the authentication information provided in the request, or perform some other activities related to authentication. This stage is mandatory, which means, at least one authentication mechanism must be specified. If multiple are specified, the subsequent ones are only executed if the previous either fail or were not responsible for the authentication data available with the request.

* **Authorization Stage:** In that stage you can make use of any amount of link:{{< relref "/docs/mechanisms/contextualizers.adoc" >}}[contextualization] and link:{{< relref "/docs/mechanisms/authorizers.adoc" >}}[authorization] mechanisms in any order to fulfill your authorization requirements. Here, you let heimdall communicate with other systems to collect contextual information required for authorization purposes (like e.g. getting the country for the IP, the request came from, retrieving subscription status of your customer, etc), and to perform the actual authorization, e.g. by talking to an Open Policy Agent, OpenFGA, any other type of authorization system, or even let heimdall perform the required checks locally. That stage is optional and is only executed after the successful execution of the authentication stage. The mechanisms specified in it are executed in order of their definition.

* **Finalization Stage:** In that stage, you can use any amount of link:{{< relref "/docs/mechanisms/finalizers.adoc" >}}[finalization] mechanisms to complete the pipeline execution and allows you transforming the information collected about the subject in the previous stages into a format expected or required by your upstream service, or even driving specific protocols, e.g. to obtain a token required by the upstream service. That stage is optional and is only executed after the successful execution of the previous stage. The mechanisms specified in it are executed in order of their definition.

NOTE: Stages are implicit. That is, a pipeline is just a list of mechanisms to be executed in the specified order. That means, all link:{{< relref "/docs/mechanisms/authenticators.adoc" >}}[authentication] mechanisms must be specified before any link:{{< relref "/docs/mechanisms/contextualizers.adoc" >}}[contextualization], link:{{< relref "/docs/mechanisms/authorizers.adoc" >}}[authorization] or link:{{< relref "/docs/mechanisms/finalizers.adoc" >}}[finalization] mechanisms are specified, with all link:{{< relref "/docs/mechanisms/finalizers.adoc" >}}[finalization] mechanisms required to be specified at the end. Violation of that rule will let heimdall refuse loading of the particular rule.

== Error Pipeline

Obviously, a link:{{< relref "/docs/concepts/mechanisms.adoc" >}}[mechanism] used in the previously described link:{{< relref "#_authentication_authorization_pipeline" >}}[Authentication & Authorization Pipeline] may fail. That will result in the execution of the error pipeline, which is basically a list of link:{{< relref "/docs/mechanisms/error_handlers.adoc" >}}[error handler] mechanisms, ranging from a simple error response to the client (which sent the request) to sophisticated ones supporting complex logic and redirects. Mechanisms in this pipeline define conditions under which they are executed. The first mechanism, which condition evaluates to true is executed and other are ignored. If conditions of all mechanisms fail, the default error handler is executed (see also below).

The error pipeline is optional. If no error handlers are defined, heimdall will just response with an HTTP response code based on the error raised in the authentication & authorization pipeline.
