version: '3.7'

services:
 
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning

  upstream:
    image: containous/whoami:latest
    labels:
      - traefik.enable=true
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.rule=PathPrefix("/")
      - traefik.http.routers.whoami.middlewares=heimdall

