log:
  level: debug

serve:
  decision:
    trusted_proxies:
      - 0.0.0.0/0

cache:
  type: redis-cluster
  config:
    addrs:
      - "localhost:7000"
      - "localhost:7001"
      - "localhost:7002"
      - "localhost:7003"
      - "localhost:7004"
      - "localhost:7005"
    username: default
    password: secret

mechanisms:
  authenticators:
    - id: anon
      type: anonymous
    - id: reject_requests
      type: unauthorized
  finalizers:
    - id: create_jwt
      type: jwt
  error_handlers:
    - id: default
      type: default
    - id: redirect_to_login
      type: redirect
      if: >
        type(Error) == authentication_error &&
        Error.Source == "reject_requests" &&
        Request.Header("Accept").contains("Bar")
      config:
        to: http://127.0.0.1:8080/login?origin={{ .Request.URL | urlenc }}

default_rule:
  methods:
    - GET
    - POST
  execute:
    - authenticator: reject_requests
  on_error:
    - error_handler: redirect_to_login

providers:
  file_system:
    src: ./upstream-rules.yaml
    watch: true
