operator:
  scanAllNamespaces: true
grafana:
  dashboardLabelSelectors:
    - matchLabels:
        release: grafana
  ingress:
    enabled: true
  config:
    users:
      auto_assign_org_role: Admin
    log:
      level: debug
    metrics:
      enabled: true
    security:
      admin_user: admin
      admin_password: monitoring
    feature_toggles:
      enable: flameGraph