// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dadrus/heimdall/internal/pipeline"
	mock "github.com/stretchr/testify/mock"
)

// NewPipelineMock creates a new instance of PipelineMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPipelineMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PipelineMock {
	mock := &PipelineMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PipelineMock is an autogenerated mock type for the Pipeline type
type PipelineMock struct {
	mock.Mock
}

type PipelineMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PipelineMock) EXPECT() *PipelineMock_Expecter {
	return &PipelineMock_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type PipelineMock
func (_mock *PipelineMock) Execute(ctx pipeline.Context, subject pipeline.Subject) error {
	ret := _mock.Called(ctx, subject)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(pipeline.Context, pipeline.Subject) error); ok {
		r0 = returnFunc(ctx, subject)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PipelineMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type PipelineMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx pipeline.Context
//   - subject pipeline.Subject
func (_e *PipelineMock_Expecter) Execute(ctx interface{}, subject interface{}) *PipelineMock_Execute_Call {
	return &PipelineMock_Execute_Call{Call: _e.mock.On("Execute", ctx, subject)}
}

func (_c *PipelineMock_Execute_Call) Run(run func(ctx pipeline.Context, subject pipeline.Subject)) *PipelineMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pipeline.Context
		if args[0] != nil {
			arg0 = args[0].(pipeline.Context)
		}
		var arg1 pipeline.Subject
		if args[1] != nil {
			arg1 = args[1].(pipeline.Subject)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PipelineMock_Execute_Call) Return(err error) *PipelineMock_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PipelineMock_Execute_Call) RunAndReturn(run func(ctx pipeline.Context, subject pipeline.Subject) error) *PipelineMock_Execute_Call {
	_c.Call.Return(run)
	return _c
}
