---
title: "Signature Keys & Certificates"
date: 2022-08-15T06:47:22+02:00
draft: false
weight: 130
menu:
  docs:
    weight: 45
    parent: "Configuration"
---

Some link:{{< relref "/docs/configuration/pipeline/mutators.adoc" >}}[Mutators], which finalize the successful execution of the pipeline, can generated signed objects, like a JWT, to be forwarded to the upstream services. In such cases Heimdall acts as an issuer of such objects and needs at least corresponding key material.

== Configuration

The configuration related to the issuance of signed objects can be done using the `signer` property, which resides on the top level of heimdall's configuration and supports the following properties.

* *`name`*: _string_ (optional)
+
The name used to specify the issuer. E.g. if a JWT is generated, this value is used to set the `iss` claim. If not set the value `heimdall` is used.

* *`key_store`*: _string_ (optional)
+
Path to a file in PEM format, containing the cryptographic material for signature creation purposes. If this file is specified, at least one private key must be present.
+
If the PEM file contains X.509 certificates in addition to the keys, heimdall will try to identify a certificate (incl its chain) for each private key (the order of the certificates doesn't matter). If heimdall was able to identify the certificate chain, the chain is validated. This includes the following steps:

** cryptographic validity
** time validity
** certificate to allow creation of digital signatures.

+
PKCS#1, as well as PKCS#8 encodings are supported for private keys. If `key_store` is not specified, heimdall generates an RSA key on startup.

* *`password`*: _string_ (optional)
+
If the key material is protected with a password, this property can be set to decipher it.
+
CAUTION: If the PEM file contains multiple keys and these keys are password protected, same password must be used for all of these.

* *`key_id`*: _string_ (optional)
+
If the `key_store` references a PEM file, containing multiple keys, this property can be used to specify the key to use (see also link:{{< relref "#_key_id_lookup" >}}[Key-Id Lookup]). If not specified, the first key is used. If specified, but there is no key for the given key id present, an error is raised on startup.

.Possible configuration
====
Imagine you have a PEM file located in `/opt/heimdall/keystore.pem` with the following contents:

[source, txt]
----
-----BEGIN EC PRIVATE KEY-----
X-Key-ID: foo

MIGkAgEBBDBRLr783dIM5NHJnDDMRVBiFSF56xqHle5lZk1ZCyyow9wKZGuF4EWK
jRBISBkE3NSgBwYFK4EEACKhZANiAAQ+oGUOJpVjntIWuanYxpXe6oN5tKhzLhBX
GP1SOXiLhnPNnN2uZu9KwOoBzoZhr/Fxw+sziXmzHJwjluz78VOlFKyopxTfmxRZ
0qq3f/KHWdDtVvmTfT0O/ux9mg6mCJw=
-----END EC PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
MIIByjCCAVGgAwIBAgIBATAKBggqhkjOPQQDAzAuMQswCQYDVQQGEwJFVTENMAsG
A1UEChMEVGVzdDEQMA4GA1UEAxMHVGVzdCBDQTAeFw0yMjA4MTUwOTE3MTFaFw0y
MjA4MTUxMDE3MTFaMDAxCzAJBgNVBAYTAkVVMQ0wCwYDVQQKEwRUZXN0MRIwEAYD
VQQDEwlUZXN0IEVFIDEwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQ+oGUOJpVjntIW
uanYxpXe6oN5tKhzLhBXGP1SOXiLhnPNnN2uZu9KwOoBzoZhr/Fxw+sziXmzHJwj
luz78VOlFKyopxTfmxRZ0qq3f/KHWdDtVvmTfT0O/ux9mg6mCJyjQTA/MA4GA1Ud
DwEB/wQEAwIHgDAMBgNVHQ4EBQQDYmFyMB8GA1UdIwQYMBaAFLO77bgPgZMKz11D
BVDUXvtNGeBnMAoGCCqGSM49BAMDA2cAMGQCMFRlx9Bq0MuSh5pDhDTqRq/MnxxD
W7qZg15AXoNnLrR60vV9gHjzkp1UkcU9viRIuAIwU0BjwDncp9z1seqKh+/eJV3f
xstQe2rzUEptWLIiPFoOBWZuw9wJ/Hunjik3a9T/
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIByjCCAVCgAwIBAgIBATAKBggqhkjOPQQDAzAuMQswCQYDVQQGEwJFVTENMAsG
A1UEChMEVGVzdDEQMA4GA1UEAxMHVGVzdCBDQTAeFw0yMjA4MTUwOTE3MTFaFw0y
MjA4MTYwOTE3MTFaMC4xCzAJBgNVBAYTAkVVMQ0wCwYDVQQKEwRUZXN0MRAwDgYD
VQQDEwdUZXN0IENBMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEf96tstMNdNoNfYjl
bGY6BvBFTsl9E3hpPnta7SJn6BqIYz6KEohDJ+8DXwUMVb5Ytr/QkEikg966HCY3
A9TFBUdAs01TV8f2KoAPRQVrh+ccSLLJyACENfZ5VbGSQ0wso0IwQDAOBgNVHQ8B
Af8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUs7vtuA+BkwrPXUMF
UNRe+00Z4GcwCgYIKoZIzj0EAwMDaAAwZQIxAMPgE/Z+1Dcj+lH7jioE16Hig0HQ
FC4qBx1UU05H05Gs23ECB1hzD2qXikVpaNyuDgIwbogEu42wIwpDa5xdJIZcIhmz
DIuPvEscUDjU3C+1GPxmACcRMPv9QVUEcBAvZkfn
-----END CERTIFICATE-----
----

Then you can configure heimdall to use it like follows:

[source, yaml]
----
signer:
  name: foobar
  key_store: /opt/heimdall/keystore.pem
  key_id: foo
----
====

== Key-Id Lookup

When heimdall loads the `key_store` following algorithm is used to get the key id for the key:

* if the PEM entry with the private key has `X-Key-ID` header specified, this value is used as key id
* Otherwise, if an X.509 certificate is present for the private key, and it has the `Subject Key Identifier` extension set, the hex representation of it is used as key id.
* Otherwise, heimdall calculates the value for the `Subject Key Identifier` according to https://www.ietf.org/rfc/rfc3280.html#section-4.2.1.2[RFC 3280, Section 4.2.1.2] and uses hex representation of it as key id.