// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dadrus/heimdall/internal/rules/mechanisms/template"
	mock "github.com/stretchr/testify/mock"
)

// NewSecretStoreMock creates a new instance of SecretStoreMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretStoreMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretStoreMock {
	mock := &SecretStoreMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SecretStoreMock is an autogenerated mock type for the SecretStore type
type SecretStoreMock struct {
	mock.Mock
}

type SecretStoreMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretStoreMock) EXPECT() *SecretStoreMock_Expecter {
	return &SecretStoreMock_Expecter{mock: &_m.Mock}
}

// GetSecret provides a mock function for the type SecretStoreMock
func (_mock *SecretStoreMock) GetSecret(ref template.SecretReference) (string, error) {
	ret := _mock.Called(ref)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(template.SecretReference) (string, error)); ok {
		return returnFunc(ref)
	}
	if returnFunc, ok := ret.Get(0).(func(template.SecretReference) string); ok {
		r0 = returnFunc(ref)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(template.SecretReference) error); ok {
		r1 = returnFunc(ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretStoreMock_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type SecretStoreMock_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ref template.SecretReference
func (_e *SecretStoreMock_Expecter) GetSecret(ref interface{}) *SecretStoreMock_GetSecret_Call {
	return &SecretStoreMock_GetSecret_Call{Call: _e.mock.On("GetSecret", ref)}
}

func (_c *SecretStoreMock_GetSecret_Call) Run(run func(ref template.SecretReference)) *SecretStoreMock_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 template.SecretReference
		if args[0] != nil {
			arg0 = args[0].(template.SecretReference)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SecretStoreMock_GetSecret_Call) Return(s string, err error) *SecretStoreMock_GetSecret_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *SecretStoreMock_GetSecret_Call) RunAndReturn(run func(ref template.SecretReference) (string, error)) *SecretStoreMock_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterSecret provides a mock function for the type SecretStoreMock
func (_mock *SecretStoreMock) RegisterSecret(ref template.SecretReference) error {
	ret := _mock.Called(ref)

	if len(ret) == 0 {
		panic("no return value specified for RegisterSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(template.SecretReference) error); ok {
		r0 = returnFunc(ref)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SecretStoreMock_RegisterSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterSecret'
type SecretStoreMock_RegisterSecret_Call struct {
	*mock.Call
}

// RegisterSecret is a helper method to define mock.On call
//   - ref template.SecretReference
func (_e *SecretStoreMock_Expecter) RegisterSecret(ref interface{}) *SecretStoreMock_RegisterSecret_Call {
	return &SecretStoreMock_RegisterSecret_Call{Call: _e.mock.On("RegisterSecret", ref)}
}

func (_c *SecretStoreMock_RegisterSecret_Call) Run(run func(ref template.SecretReference)) *SecretStoreMock_RegisterSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 template.SecretReference
		if args[0] != nil {
			arg0 = args[0].(template.SecretReference)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SecretStoreMock_RegisterSecret_Call) Return(err error) *SecretStoreMock_RegisterSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SecretStoreMock_RegisterSecret_Call) RunAndReturn(run func(ref template.SecretReference) error) *SecretStoreMock_RegisterSecret_Call {
	_c.Call.Return(run)
	return _c
}
