---
title: "API"
date: 2022-06-29T17:32:36+02:00
draft: false
weight: 30
menu:
  docs:
    weight: 40
---

This section lists available endpoints implemented by heimdall:

== Decision

This endpoint is available under `<decision service>/` path when Heimdall is operated in the Decision operation mode. It accepts any subpaths, headers, cookies, etc. Also, all methods can be used as well.

== Proxy

This endpoint is available under `<proxy service>/` path when Heimdall is operated in the Proxy mode. It accepts any subpaths, headers, cookies, etc. Also, all methods can be used as well.

== Health

This endpoint is available under `<management service>/.well-known/health` and can be called using HTTP `GET` verb. The response is always an HTTP `200 OK` with body set to `{ "status": "ok" }`.

== JWKS

This endpoint is available under `<management service>/.well-known/jwks` and can be called using HTTP `GET` verb. The response is a JSON Web Key Set according to https://datatracker.ietf.org/doc/html/rfc7517[RFC 7517]. This key set contains the key material configured for signing JWTs. This endpoint make use of https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag[ETag] for caching purposes.

The contents served by this endpoint directly depend on the configuration for link:{{< relref "/docs/configuration/signature_keys_and_certificates.adoc" >}}[Signature Keys & Certificates]. So, if nothing has been configured, the response will contain the JWKS with a single JWK for the key material heimdall generated on start up. Otherwise, the response will contain the JWKS with as many JWK entries, as you've specified via the above referenced configuration. If certificates have been configured together with the keys, the corresponding `x5c` entries will be present as well.

.Possible response
====
Imagine you configure `signer` `key_store` property with a PEM file with the following contents:

[source, text]
----
-----BEGIN EC PRIVATE KEY-----
X-Key-ID: foo

MIGkAgEBBDDo3RMhffhf9OlmyGkDItJt2Xl+CI+mnwxOm0Rxo6P2Dk2vNOIMHNpH
aznjXi8GqnqgBwYFK4EEACKhZANiAAQAFUfJwN3gJT3kEbIKghNlFAsZHsv3bsF5
G8aRPOyINEmmejg6g5wHYGScuiTUrHGOqTMQCl8TX/3zffoSTvUIChSPHGZRYeeZ
ch2aVQopCqdFFcWHBoxHLHK89jo4uS0=
-----END EC PRIVATE KEY-----
-----BEGIN EC PRIVATE KEY-----
X-Key-ID: bar

MIGkAgEBBDA5iBXfURi1mnOpxLTEOHz4+5Cy1qW+nsymnPvwi9GgLiu+zNyKvoKo
6f1oKq7nF72gBwYFK4EEACKhZANiAASaOh9MIwDLqLl924EothJnz7N19U472vCe
PfcAOUzCmxQiLmjw6DlW6/aR+xeR1OrWEhQbgJf7nRO6HA+UzhySKJallR+14tKw
VfeP3/aHHtBxo019d0RzUOXm4N4F97c=
-----END EC PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
MIIBwjCCAUmgAwIBAgIBATAKBggqhkjOPQQDAzA0MQswCQYDVQQGEwJFVTENMAsG
A1UEChMEVGVzdDEWMBQGA1UEAxMNVGVzdCBJbnQgQ0EgMTAeFw0yMjA4MTUxMzI2
NTVaFw0yMjA4MTYxMzI2NTVaMDAxCzAJBgNVBAYTAkVVMQ0wCwYDVQQKEwRUZXN0
MRIwEAYDVQQDEwlUZXN0IEVFIDEwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQAFUfJ
wN3gJT3kEbIKghNlFAsZHsv3bsF5G8aRPOyINEmmejg6g5wHYGScuiTUrHGOqTMQ
Cl8TX/3zffoSTvUIChSPHGZRYeeZch2aVQopCqdFFcWHBoxHLHK89jo4uS2jMzAx
MA4GA1UdDwEB/wQEAwIHgDAfBgNVHSMEGDAWgBTVe7ko0R5OcFCHjnlch8D7FuUy
2TAKBggqhkjOPQQDAwNnADBkAjAv1RMkVae8yjgFAYEwXlkt2fJLd+2e1huNPKTQ
klVpaEzG90pOml4I/GY4WdkA+aQCMGRJO4NcHore6gW8O/q3UH+sNKI7ajrPir/X
mifLlRo8WqHqtwdr7PPAdaWJk2Z3rA==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIB9zCCAX6gAwIBAgIBATAKBggqhkjOPQQDAzA1MQswCQYDVQQGEwJFVTENMAsG
A1UEChMEVGVzdDEXMBUGA1UEAxMOVGVzdCBSb290IENBIDEwHhcNMjIwODE1MTMy
NjU1WhcNMjIwODE2MTMyNjU1WjA0MQswCQYDVQQGEwJFVTENMAsGA1UEChMEVGVz
dDEWMBQGA1UEAxMNVGVzdCBJbnQgQ0EgMTB2MBAGByqGSM49AgEGBSuBBAAiA2IA
BDMJBSK7YohCKPo5DPiUnf9l5rmap/1LeodMPQYaNUCuIlHbeM+04BKYyIhK9hGj
dNqNcH+072V7ACGA0ws5T2gDFP91xtahjL2wez5+CTTrM3Dv7wn79YX9yg7fRmg9
d6NjMGEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYE
FNV7uSjRHk5wUIeOeVyHwPsW5TLZMB8GA1UdIwQYMBaAFEoIzc7CBkrctksa5pCT
I3Np8B/6MAoGCCqGSM49BAMDA2cAMGQCMCNss/k8OaTnMzl3+OF0H+hZlylFm8vs
dwyERJ+eTU7zH3VOog1ylmkwedj+BnEJ8wIwSTu6IBJt4Db1V7ZJN2rIfbrPlIfs
V7IK5SdVJT3a5Ta6lxdxTtZABlYPHEV7GaUB
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIB2TCCAV6gAwIBAgIBATAKBggqhkjOPQQDAzA1MQswCQYDVQQGEwJFVTENMAsG
A1UEChMEVGVzdDEXMBUGA1UEAxMOVGVzdCBSb290IENBIDEwHhcNMjIwODE1MTMy
NjU1WhcNMjIwODE2MTMyNjU1WjA1MQswCQYDVQQGEwJFVTENMAsGA1UEChMEVGVz
dDEXMBUGA1UEAxMOVGVzdCBSb290IENBIDEwdjAQBgcqhkjOPQIBBgUrgQQAIgNi
AAR60dYKMyR7IJGOkJUCfBnft32DoFtpeIEQwYUkZDBzDIy5l8pqlX6OdsnRBtwa
yjFuOQtqjgtb71nrcQSjI6aVTJqBnwsC5tPtqD0cdzICSK/WGokrMnUVF/MYHdhb
wyejQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
BBRKCM3OwgZK3LZLGuaQkyNzafAf+jAKBggqhkjOPQQDAwNpADBmAjEA41BYFNhv
gDbE3LOyOWwk6Es/Yatjy7482q/PxfcElvyhX9/h1p6eoLkIILsFXjnnAjEAnHns
KGAWrW03rnntkKBgkv1vO/Hn8dkKYqPGzgN1kmrXM0qvE6K8lXD0dnVAF6mx
-----END CERTIFICATE-----
----

Then the response from the JWKS endpoint will be as follows (line breaks and spaces were added to enhance readability):

[source, json]
----
HTTP/1.1 200 OK
Date: Mon, 15 Aug 2022 13:26:55 GMT
Content-Type: application/json
Content-Length: 2361
Etag: "2361-623541857"

{
  "keys": [
    {
      "use": "sig",
      "kty": "EC",
      "kid": "foo",
      "crv": "P-384",
      "alg": "ES384",
      "x": "ABVHycDd4CU95BGyCoITZRQLGR7L927BeRvGkTzsiDRJpno4OoOcB2BknLok1Kxx",
      "y": "jqkzEApfE1_98336Ek71CAoUjxxmUWHnmXIdmlUKKQqnRRXFhwaMRyxyvPY6OLkt",
      "x5c": [
"MIIBwjCCAUmgAwIBAgIBATAKBggqhkjOPQQDAzA0MQswCQYDVQQGEwJFVTENMAs
GA1UEChMEVGVzdDEWMBQGA1UEAxMNVGVzdCBJbnQgQ0EgMTAeFw0yMjA4MTUxMzI
2NTVaFw0yMjA4MTYxMzI2NTVaMDAxCzAJBgNVBAYTAkVVMQ0wCwYDVQQKEwRUZXN
0MRIwEAYDVQQDEwlUZXN0IEVFIDEwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQAFUf
JwN3gJT3kEbIKghNlFAsZHsv3bsF5G8aRPOyINEmmejg6g5wHYGScuiTUrHGOqTM
QCl8TX/3zffoSTvUIChSPHGZRYeeZch2aVQopCqdFFcWHBoxHLHK89jo4uS2jMzA
xMA4GA1UdDwEB/wQEAwIHgDAfBgNVHSMEGDAWgBTVe7ko0R5OcFCHjnlch8D7FuU
y2TAKBggqhkjOPQQDAwNnADBkAjAv1RMkVae8yjgFAYEwXlkt2fJLd+2e1huNPKT
QklVpaEzG90pOml4I/GY4WdkA+aQCMGRJO4NcHore6gW8O/q3UH+sNKI7ajrPir/
XmifLlRo8WqHqtwdr7PPAdaWJk2Z3rA==",
"MIIB9zCCAX6gAwIBAgIBATAKBggqhkjOPQQDAzA1MQswCQYDVQQGEwJFVTENMAs
GA1UEChMEVGVzdDEXMBUGA1UEAxMOVGVzdCBSb290IENBIDEwHhcNMjIwODE1MTM
yNjU1WhcNMjIwODE2MTMyNjU1WjA0MQswCQYDVQQGEwJFVTENMAsGA1UEChMEVGV
zdDEWMBQGA1UEAxMNVGVzdCBJbnQgQ0EgMTB2MBAGByqGSM49AgEGBSuBBAAiA2I
ABDMJBSK7YohCKPo5DPiUnf9l5rmap/1LeodMPQYaNUCuIlHbeM+04BKYyIhK9hG
jdNqNcH+072V7ACGA0ws5T2gDFP91xtahjL2wez5+CTTrM3Dv7wn79YX9yg7fRmg
9d6NjMGEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBY
EFNV7uSjRHk5wUIeOeVyHwPsW5TLZMB8GA1UdIwQYMBaAFEoIzc7CBkrctksa5pC
TI3Np8B/6MAoGCCqGSM49BAMDA2cAMGQCMCNss/k8OaTnMzl3+OF0H+hZlylFm8v
sdwyERJ+eTU7zH3VOog1ylmkwedj+BnEJ8wIwSTu6IBJt4Db1V7ZJN2rIfbrPlIf
sV7IK5SdVJT3a5Ta6lxdxTtZABlYPHEV7GaUB",
"MIIB2TCCAV6gAwIBAgIBATAKBggqhkjOPQQDAzA1MQswCQYDVQQGEwJFVTENMAs
GA1UEChMEVGVzdDEXMBUGA1UEAxMOVGVzdCBSb290IENBIDEwHhcNMjIwODE1MTM
yNjU1WhcNMjIwODE2MTMyNjU1WjA1MQswCQYDVQQGEwJFVTENMAsGA1UEChMEVGV
zdDEXMBUGA1UEAxMOVGVzdCBSb290IENBIDEwdjAQBgcqhkjOPQIBBgUrgQQAIgN
iAAR60dYKMyR7IJGOkJUCfBnft32DoFtpeIEQwYUkZDBzDIy5l8pqlX6OdsnRBtw
ayjFuOQtqjgtb71nrcQSjI6aVTJqBnwsC5tPtqD0cdzICSK/WGokrMnUVF/MYHdh
bwyejQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQ
WBBRKCM3OwgZK3LZLGuaQkyNzafAf+jAKBggqhkjOPQQDAwNpADBmAjEA41BYFNh
vgDbE3LOyOWwk6Es/Yatjy7482q/PxfcElvyhX9/h1p6eoLkIILsFXjnnAjEAnHn
sKGAWrW03rnntkKBgkv1vO/Hn8dkKYqPGzgN1kmrXM0qvE6K8lXD0dnVAF6mx"
      ]
    },
    {
      "use": "sig",
      "kty": "EC",
      "kid": "bar",
      "crv": "P-384",
      "alg": "ES384",
      "x": "mjofTCMAy6i5fduBKLYSZ8-zdfVOO9rwnj33ADlMwpsUIi5o8Og5Vuv2kfsXkdTq",
      "y": "1hIUG4CX-50TuhwPlM4ckiiWpZUfteLSsFX3j9_2hx7QcaNNfXdEc1Dl5uDeBfe3"
    }
  ]
}
----
====