---
title: "API"
date: 2022-06-29T17:32:36+02:00
draft: false
weight: 30
menu:
  docs:
    weight: 40
---

This section lists available endpoints implemented by heimdall:

== Decision API

This endpoint is available under `<decision service>/` path when Heimdall is operated in the Decision API mode. It accepts any subpaths, headers, cookies, etc. Also, all methods can be used as well.

== Proxy

This endpoint is available under `<proxy service>/` path when Heimdall is operated in the Proxy mode. It accepts any subpaths, headers, cookies, etc. Also, all methods can be used as well.

== Health

This endpoint is available under `<management service>/.well-known/health` and can be called using HTTP `GET` verb. The response is always an HTTP `200 OK` with body set to `{ "status": "ok" }`.

== JWKS

This endpoint is available under `<management service>/.well-known/jwks` and can be called using HTTP `GET` verb. The response is a JSON Web Key Set according to https://datatracker.ietf.org/doc/html/rfc7517[RFC 7517]. This key set contains the key material configured for signing JWTs. This endpoint make use of https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag[ETag] for caching purposes.