---
title: "Finalizers"
date: 2022-06-09T18:57:16+02:00
draft: false
weight: 90
menu:
  docs:
    weight: 40
    parent: "Pipeline Mechanisms"
---

Finalizers, as the name implies, finalize the successful execution of the pipeline and make the available information about the link:{{< relref "overview.adoc#_subject" >}}[`Subject`] and the link:{{< relref "overview.adoc#_request" >}}[`Request`] to the upstream service in a format expected, respectively required by it. This ranges from adding a simple header to a structured JWT in a specific header.

== Finalizer Types

The following sections describe the available finalizer types in more detail. Some of these may support or require additional configuration. The corresponding properties are annotated with `mandatory`, respectively `optional` to denote configuration requirement, as well as with `overridable`, `not overriddable` and `partially overridable` to indicate whether the property can be overridden in a rule pipeline.

=== Noop

As the name implies, this finalizer does nothing. As finalizer are the last step in a rule pipeline and act on the available link:{{< relref "overview.adoc#_subject" >}}[`Subject`] information, the usage of this finalizer makes only sense in combination with the link:{{< relref "authenticators.adoc#_noop">}}[Noop Authenticator], e.g. if your API should be publicly available. This finalizer type also doesn't have any configuration options.

To enable the usage of this finalizer, you have to set the `type` property to `noop`.

.Noop finalizer configuration
====
[source, yaml]
----
id: foo
type: noop
----
====

=== Header

This finalizer enables transformation of a link:{{< relref "overview.adoc#_subject" >}}[`Subject`] into HTTP headers. It can also be used to map information from the original link:{{< relref "overview.adoc#_request" >}}[`Request`] into headers expected by the upstream service.

To enable the usage of this finalizer, you have to set the `type` property to `header`.

Configuration using the `config` property is mandatory. Following properties are available:

* *`headers`*: _string map_ (mandatory, overridable)
+
Enables configuration of arbitrary headers with any values build from available subject and request information (See also link:{{< relref "overview.adoc#_templating" >}}[Templating]).

.Header finalizer configuration
====
[source, yaml]
----
id: foo
type: header
config:
  headers:
    X-User-ID: '{{ quote .Subject.ID }}'
    X-User-Email: '{{ quote .Subject.Attributes["email"] }}'
    Host: '{{ quote .Request.Header("Host") }}'
----
====

=== Cookie

This finalizer enables transformation of a link:{{< relref "overview.adoc#_subject" >}}[`Subject`] into cookies. It can also be used to map information from the original link:{{< relref "overview.adoc#_request" >}}[`Request`] into cookies expected by the upstream service.

To enable the usage of this finalizer, you have to set the `type` property to `cookie`.

Configuration using the `config` property is mandatory. Following properties are available:

* *`cookies`*: _string map_ (mandatory, overridable)
+
Enables configuration of arbitrary cookies with any values build from available subject information (See also link:{{< relref "overview.adoc#_templating" >}}[Templating]).

.Cookie finalizer configuration
====
[source, yaml]
----
id: foo
type: cookies
config:
  cookies:
    user_id_cookie: '{{ quote .Subject.ID }}'
    user_email_cookie: '{{ quote .Subject.Attributes["email"] }}'
----
====

=== JWT

This finalizer enables transformation of the link:{{< relref "overview.adoc#_subject" >}}[`Subject`] and the link:{{< relref "overview.adoc#_request" >}}[`Request`] object into a token in a https://www.rfc-editor.org/rfc/rfc7519[JWT] format, which is then made available to your upstream service in either the HTTP `Authorization` header with `Bearer` scheme set, or in a custom header. In addition to setting the JWT specific claims, it allows setting custom claims as well. Your upstream service can then verify the signature of the JWT by making use of heimdall's JWKS endpoint to retrieve the required public keys/certificates from.

NOTE: To enable the usage of this finalizer, you have to set the `type` property to `jwt`. The usage of this finalizer type requires a configured link:{{< relref "/docs/configuration/cryptographic_material.adoc" >}}[Signer] as well. At least it is a must in production environments.

Configuration using the `config` property is optional. Following properties are available:

* *`claims`*: _string_ (optional, overridable)
+
Your template with custom claims, you would like to add to the JWT (See also link:{{< relref "overview.adoc#_templating" >}}[Templating]).

* *`ttl`*: _link:{{< relref "/docs/configuration/reference/types.adoc#_duration" >}}[Duration]_ (optional, overridable)
+
Defines how long the JWT should be valid. Defaults to 5 minutes. Heimdall sets the `iat` and the `nbf` claims to the current system time. The value of the `exp` claim is then influenced by the `ttl` property.

* *`header`*: _object_ (optional, not overridable)
+
Defines the `name` and `scheme` to be used for the header. Defaults to `Authorization` with scheme `Bearer`. If defined, the `name` property must be set. If `scheme` is not defined, no scheme will be prepended to the resulting JWT.

The generated JWT is always cached until 5 seconds before its expiration. The cache key is calculated from the entire configuration of the finalizer instance and the available information about the current subject.

.JWT finalizer configuration
====
[source, yaml]
----
id: jwt_finalizer
type: jwt
config:
  ttl: 5m
  header:
    name: X-Token
  claims: |
    {
      {{ $user_name := .Subject.Attributes.identity.user_name -}}
      "email": {{ quote .Subject.Attributes.identity.email }},
      "email_verified": {{ .Subject.Attributes.identity.email_verified }},
      "name": {{ if $user_name }}{{ quote $user_name }}{{ else }}{{ quote $email }}{{ end }}
    }
----
====
