---
title: "About"
date: 2022-06-10T17:30:17+02:00
draft: false
menu:
  docs:
    parent: "Introduction"
    weight: 10
---

== Background

The link:{{< relref "#_fig_typical_deployment_scenario" >}}[Typical deployment scenario] diagram sketches how authentication and authorization is handled in most of today's applications.

[[_fig_typical_deployment_scenario]]
.Typical deployment scenario
[ditaa, format=svg, scale=0.7]
....

                                                       +------------------+
                                                       |                  |
                                                       |  Authentication  |
                                   +-----------------> |                  |
                                   |                   |    System        |
                                   |                   |                  |
                                   |                   |                  |
                                   |                   +------------------+
                                   |
                    +--------------|--------------------------------------------------------------------------------------------------+
                    |              |                                                                                                  |
                    :              |                                  Environment                                                     |
                    |              |                                                                                                  |
                    |              |                   +--------------------------------------------------------------------------+   |
                    |              |                   |                                                                          |   |
                    |              |                   |                               Backend Service                            |   |
                    |              |                   |                                                                          |   |
                    |              |                   |                                                                          |   |
                    |              |                   |    +-------------------+    +------------------+   +-----------------+   |   |
+------------+      |     +--------+--------+          |    |                   |    |                  |   |                 |   |   |
|            |      |     |                 |          |    |                   |    |                  |   |                 |   |   |
|            |      |     |  Authentication |          |    |  Verify Request's |    |    Authorize     |   |    Business     |   |   |
|   Client   +----------->|                 +--------->|    |                   |    |                  |   |                 |   |   |
|            |      |     |      Proxy      |          |    |  Authentication   |    |     Request      |   |     Logic       |   |   |
|            |      |     |                 |          |    |                   |    |                  |   |                 |   |   |
+------------+      |     +-----------------+          |    |     Status        |    |                  |   |                 |   |   |
                    |                                  |    |                   |    |                  |   |                 |   |   |
                    |                                  |    |                   |    |                  |   |                 |   |   |
                    |                                  |    +-------------------+    +------------------+   +-----------------+   |   |
                    :                                  |                                                                          |   |
                    |                                  |                                                                          |   |
                    |                                  +--------------------------------------------------------------------------+   |
                    |                                                                                                                 |
                    +-----------------------------------------------------------------------------------------------------------------+

....

On the one hand it allows the backend service to fully control the corresponding security requirements. On the other hand it has some limitations:

* It works as long as there is just one authentication system.
* It requires each backend service to repetitively implement security related capabilities in its code, and related to this
* it requires many backend services to communicate to further systems to e.g. get additional (context) information about the request subject (the user the request belongs to).

All of this leads pretty often to implementation efforts, which consist of 60% for security related capabilities and 40% for the actual business related functionality. In addition, these limitations imply a lot of effort if there are changes to authentication and authorization requirements. So, what would you do if you have to use multiple authentication systems, e.g. for your customers and for your system admins, or backoffice stuff? What would you do, if e.g. our business would like to introduce a new service subscription model for its customers? What does this mean in sense of coordination-, implementation efforts and time-to-market?

== Heimdall's Promise

Heimdall addresses the aforesaid challenges companies and developers face, especially with a distributed or microservices architecture. Whether you're building from scratch or migrating existing applications, Heimdall can help and allows you to transparently add security capabilities related to authentication and authorization, without adding them to your own code, but nevertheless by completely retaining control. It can do so standalone, but also integrated into available infrastructure or plattform.

== How It Works

Heimdall intercepts all your application related network traffic, allowing a broad set of application aware authentication and authorization features based on the configuration you set. This is done by routing each request through a pipeline as depicted in link:{{< relref "#_fig_heimdall_request_pipeline" >}}[Request Pipeline].


[[_fig_heimdall_request_pipeline]]
.Request Pipeline
[ditaa, format=svg, scale=0.7]
....

                   /-----------------------------------------------------------------------------------------------------\
                   |                                                                                                     |
                   :                                        Heimdall's Pipeline                                          |<- controlled by> --+
                   |                                                                                                     |                    |
                   |  +------------------+      +------------------+     +------------------+     +------------------+   |                    |
                   |  | cCCC             |      | cCCC             |     | cCCC             |     | cCCC             |   |                    :
                   |  | 1. Authenticate  |      | 2. Contextualize |     | 3. Authorize     |     | 4. Unify         |   |                    |
                   |  |                  |      |                  |     |                  |     |                  |   |      +------------------------+
                   |  +------------------+      +------------------+     +------------------+     +------------------+   |      |     Backend Service    |
                   |                                                                                                     |      |                        |
+------------+     |                                                                                                     |      |  +------------------+  |
|            |     |                                                                                                     |      |  |                  |  |
|   Client   |     |                                     Client Request Journey                                          |      |  |    Business      |  |
|            |----------------------------------------------------------------------------------------------------------------->|  |                  |  |
|   Request  |     :                                                                                                     |      |  |    Logic         |  |
|            |     |                                                                                                     |      |  |                  |  |
+------------+     \-----------------------------------------------------------------------------------------------------/      |  +------------------+  |
                                                                                                                                |                        |
                                                                                                                                +------------------------+
....

This pipeline ensures that, according to the needs of the particular backend service endpoint,

. each request is authenticated (so, you know who the subject of the request is),
. the required contextual information is available (so the required additional information about the subject is present), so that
. the subject is authorized and
. the information about the subject is transformed into a format, required by the backend service. So that irrespectively of the used authentication or authorization system, the subject information is always provided in the same stable representation.

And all of that can be controlled by each and every backend service individually.



