// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	heimdall "github.com/dadrus/heimdall/internal/heimdall"
	mock "github.com/stretchr/testify/mock"
)

// ErrorHandlerMock is an autogenerated mock type for the errorHandler type
type ErrorHandlerMock struct {
	mock.Mock
}

type ErrorHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorHandlerMock) EXPECT() *ErrorHandlerMock_Expecter {
	return &ErrorHandlerMock_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, causeErr
func (_m *ErrorHandlerMock) Execute(ctx heimdall.RequestContext, causeErr error) error {
	ret := _m.Called(ctx, causeErr)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(heimdall.RequestContext, error) error); ok {
		r0 = rf(ctx, causeErr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ErrorHandlerMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ErrorHandlerMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx heimdall.RequestContext
//   - causeErr error
func (_e *ErrorHandlerMock_Expecter) Execute(ctx interface{}, causeErr interface{}) *ErrorHandlerMock_Execute_Call {
	return &ErrorHandlerMock_Execute_Call{Call: _e.mock.On("Execute", ctx, causeErr)}
}

func (_c *ErrorHandlerMock_Execute_Call) Run(run func(ctx heimdall.RequestContext, causeErr error)) *ErrorHandlerMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(heimdall.RequestContext), args[1].(error))
	})
	return _c
}

func (_c *ErrorHandlerMock_Execute_Call) Return(_a0 error) *ErrorHandlerMock_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ErrorHandlerMock_Execute_Call) RunAndReturn(run func(heimdall.RequestContext, error) error) *ErrorHandlerMock_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with given fields:
func (_m *ErrorHandlerMock) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ErrorHandlerMock_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type ErrorHandlerMock_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *ErrorHandlerMock_Expecter) ID() *ErrorHandlerMock_ID_Call {
	return &ErrorHandlerMock_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *ErrorHandlerMock_ID_Call) Run(run func()) *ErrorHandlerMock_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ErrorHandlerMock_ID_Call) Return(_a0 string) *ErrorHandlerMock_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ErrorHandlerMock_ID_Call) RunAndReturn(run func() string) *ErrorHandlerMock_ID_Call {
	_c.Call.Return(run)
	return _c
}

// NewErrorHandlerMock creates a new instance of ErrorHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorHandlerMock {
	mock := &ErrorHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
