// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dadrus/heimdall/internal/heimdall"
	"github.com/dadrus/heimdall/internal/rules/mechanisms/subject"
	mock "github.com/stretchr/testify/mock"
)

// NewSubjectHandlerMock creates a new instance of SubjectHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubjectHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubjectHandlerMock {
	mock := &SubjectHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SubjectHandlerMock is an autogenerated mock type for the subjectHandler type
type SubjectHandlerMock struct {
	mock.Mock
}

type SubjectHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SubjectHandlerMock) EXPECT() *SubjectHandlerMock_Expecter {
	return &SubjectHandlerMock_Expecter{mock: &_m.Mock}
}

// ContinueOnError provides a mock function for the type SubjectHandlerMock
func (_mock *SubjectHandlerMock) ContinueOnError() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContinueOnError")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// SubjectHandlerMock_ContinueOnError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContinueOnError'
type SubjectHandlerMock_ContinueOnError_Call struct {
	*mock.Call
}

// ContinueOnError is a helper method to define mock.On call
func (_e *SubjectHandlerMock_Expecter) ContinueOnError() *SubjectHandlerMock_ContinueOnError_Call {
	return &SubjectHandlerMock_ContinueOnError_Call{Call: _e.mock.On("ContinueOnError")}
}

func (_c *SubjectHandlerMock_ContinueOnError_Call) Run(run func()) *SubjectHandlerMock_ContinueOnError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SubjectHandlerMock_ContinueOnError_Call) Return(b bool) *SubjectHandlerMock_ContinueOnError_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *SubjectHandlerMock_ContinueOnError_Call) RunAndReturn(run func() bool) *SubjectHandlerMock_ContinueOnError_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type SubjectHandlerMock
func (_mock *SubjectHandlerMock) Execute(ctx heimdall.RequestContext, sub *subject.Subject) error {
	ret := _mock.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(heimdall.RequestContext, *subject.Subject) error); ok {
		r0 = returnFunc(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SubjectHandlerMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type SubjectHandlerMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx heimdall.RequestContext
//   - sub *subject.Subject
func (_e *SubjectHandlerMock_Expecter) Execute(ctx interface{}, sub interface{}) *SubjectHandlerMock_Execute_Call {
	return &SubjectHandlerMock_Execute_Call{Call: _e.mock.On("Execute", ctx, sub)}
}

func (_c *SubjectHandlerMock_Execute_Call) Run(run func(ctx heimdall.RequestContext, sub *subject.Subject)) *SubjectHandlerMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 heimdall.RequestContext
		if args[0] != nil {
			arg0 = args[0].(heimdall.RequestContext)
		}
		var arg1 *subject.Subject
		if args[1] != nil {
			arg1 = args[1].(*subject.Subject)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SubjectHandlerMock_Execute_Call) Return(err error) *SubjectHandlerMock_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SubjectHandlerMock_Execute_Call) RunAndReturn(run func(ctx heimdall.RequestContext, sub *subject.Subject) error) *SubjectHandlerMock_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type SubjectHandlerMock
func (_mock *SubjectHandlerMock) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SubjectHandlerMock_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type SubjectHandlerMock_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *SubjectHandlerMock_Expecter) ID() *SubjectHandlerMock_ID_Call {
	return &SubjectHandlerMock_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *SubjectHandlerMock_ID_Call) Run(run func()) *SubjectHandlerMock_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SubjectHandlerMock_ID_Call) Return(s string) *SubjectHandlerMock_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *SubjectHandlerMock_ID_Call) RunAndReturn(run func() string) *SubjectHandlerMock_ID_Call {
	_c.Call.Return(run)
	return _c
}
