// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package app

import (
	"github.com/dadrus/heimdall/internal/config"
	"github.com/dadrus/heimdall/internal/keyholder"
	"github.com/dadrus/heimdall/internal/otel/metrics/certificate"
	"github.com/dadrus/heimdall/internal/validation"
	"github.com/dadrus/heimdall/internal/watcher"
	"github.com/rs/zerolog"
	mock "github.com/stretchr/testify/mock"
)

// NewContextMock creates a new instance of ContextMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContextMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContextMock {
	mock := &ContextMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ContextMock is an autogenerated mock type for the Context type
type ContextMock struct {
	mock.Mock
}

type ContextMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ContextMock) EXPECT() *ContextMock_Expecter {
	return &ContextMock_Expecter{mock: &_m.Mock}
}

// CertificateObserver provides a mock function for the type ContextMock
func (_mock *ContextMock) CertificateObserver() certificate.Observer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificateObserver")
	}

	var r0 certificate.Observer
	if returnFunc, ok := ret.Get(0).(func() certificate.Observer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(certificate.Observer)
		}
	}
	return r0
}

// ContextMock_CertificateObserver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificateObserver'
type ContextMock_CertificateObserver_Call struct {
	*mock.Call
}

// CertificateObserver is a helper method to define mock.On call
func (_e *ContextMock_Expecter) CertificateObserver() *ContextMock_CertificateObserver_Call {
	return &ContextMock_CertificateObserver_Call{Call: _e.mock.On("CertificateObserver")}
}

func (_c *ContextMock_CertificateObserver_Call) Run(run func()) *ContextMock_CertificateObserver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ContextMock_CertificateObserver_Call) Return(observer certificate.Observer) *ContextMock_CertificateObserver_Call {
	_c.Call.Return(observer)
	return _c
}

func (_c *ContextMock_CertificateObserver_Call) RunAndReturn(run func() certificate.Observer) *ContextMock_CertificateObserver_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type ContextMock
func (_mock *ContextMock) Config() *config.Configuration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *config.Configuration
	if returnFunc, ok := ret.Get(0).(func() *config.Configuration); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Configuration)
		}
	}
	return r0
}

// ContextMock_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type ContextMock_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *ContextMock_Expecter) Config() *ContextMock_Config_Call {
	return &ContextMock_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *ContextMock_Config_Call) Run(run func()) *ContextMock_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ContextMock_Config_Call) Return(configuration *config.Configuration) *ContextMock_Config_Call {
	_c.Call.Return(configuration)
	return _c
}

func (_c *ContextMock_Config_Call) RunAndReturn(run func() *config.Configuration) *ContextMock_Config_Call {
	_c.Call.Return(run)
	return _c
}

// KeyHolderRegistry provides a mock function for the type ContextMock
func (_mock *ContextMock) KeyHolderRegistry() keyholder.Registry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for KeyHolderRegistry")
	}

	var r0 keyholder.Registry
	if returnFunc, ok := ret.Get(0).(func() keyholder.Registry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(keyholder.Registry)
		}
	}
	return r0
}

// ContextMock_KeyHolderRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyHolderRegistry'
type ContextMock_KeyHolderRegistry_Call struct {
	*mock.Call
}

// KeyHolderRegistry is a helper method to define mock.On call
func (_e *ContextMock_Expecter) KeyHolderRegistry() *ContextMock_KeyHolderRegistry_Call {
	return &ContextMock_KeyHolderRegistry_Call{Call: _e.mock.On("KeyHolderRegistry")}
}

func (_c *ContextMock_KeyHolderRegistry_Call) Run(run func()) *ContextMock_KeyHolderRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ContextMock_KeyHolderRegistry_Call) Return(registry keyholder.Registry) *ContextMock_KeyHolderRegistry_Call {
	_c.Call.Return(registry)
	return _c
}

func (_c *ContextMock_KeyHolderRegistry_Call) RunAndReturn(run func() keyholder.Registry) *ContextMock_KeyHolderRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type ContextMock
func (_mock *ContextMock) Logger() zerolog.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 zerolog.Logger
	if returnFunc, ok := ret.Get(0).(func() zerolog.Logger); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(zerolog.Logger)
	}
	return r0
}

// ContextMock_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type ContextMock_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *ContextMock_Expecter) Logger() *ContextMock_Logger_Call {
	return &ContextMock_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *ContextMock_Logger_Call) Run(run func()) *ContextMock_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ContextMock_Logger_Call) Return(logger zerolog.Logger) *ContextMock_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *ContextMock_Logger_Call) RunAndReturn(run func() zerolog.Logger) *ContextMock_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Validator provides a mock function for the type ContextMock
func (_mock *ContextMock) Validator() validation.Validator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validator")
	}

	var r0 validation.Validator
	if returnFunc, ok := ret.Get(0).(func() validation.Validator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(validation.Validator)
		}
	}
	return r0
}

// ContextMock_Validator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validator'
type ContextMock_Validator_Call struct {
	*mock.Call
}

// Validator is a helper method to define mock.On call
func (_e *ContextMock_Expecter) Validator() *ContextMock_Validator_Call {
	return &ContextMock_Validator_Call{Call: _e.mock.On("Validator")}
}

func (_c *ContextMock_Validator_Call) Run(run func()) *ContextMock_Validator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ContextMock_Validator_Call) Return(validator validation.Validator) *ContextMock_Validator_Call {
	_c.Call.Return(validator)
	return _c
}

func (_c *ContextMock_Validator_Call) RunAndReturn(run func() validation.Validator) *ContextMock_Validator_Call {
	_c.Call.Return(run)
	return _c
}

// Watcher provides a mock function for the type ContextMock
func (_mock *ContextMock) Watcher() watcher.Watcher {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Watcher")
	}

	var r0 watcher.Watcher
	if returnFunc, ok := ret.Get(0).(func() watcher.Watcher); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watcher.Watcher)
		}
	}
	return r0
}

// ContextMock_Watcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watcher'
type ContextMock_Watcher_Call struct {
	*mock.Call
}

// Watcher is a helper method to define mock.On call
func (_e *ContextMock_Expecter) Watcher() *ContextMock_Watcher_Call {
	return &ContextMock_Watcher_Call{Call: _e.mock.On("Watcher")}
}

func (_c *ContextMock_Watcher_Call) Run(run func()) *ContextMock_Watcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ContextMock_Watcher_Call) Return(watcher1 watcher.Watcher) *ContextMock_Watcher_Call {
	_c.Call.Return(watcher1)
	return _c
}

func (_c *ContextMock_Watcher_Call) RunAndReturn(run func() watcher.Watcher) *ContextMock_Watcher_Call {
	_c.Call.Return(run)
	return _c
}
