---
title: "Metrics"
date: 2022-06-09T22:16:45+02:00
draft: false
weight: 55
menu:
  docs:
    weight: 20
    parent: "Observability"
---

Heimdall generates https://opentelemetry.io/[OpenTelemetry] metrics and can export these either by pushing these to an OTEL collector (the default behavior), or by exposing them via a pull based service (https://grafana.com/oss/prometheus/[Prometheus] style).

Metrics are generated and exported by default. If this is not desired, you can explicitly disable this behavior by making use of the configuration options, described below. Alternatively, you can set the `OTEL_METRICS_EXPORTER` environment variable to `none`.

== Configuration

Configuration for this service can be adjusted in the `metrics` property of heimdall's configuration by making use of the following properties.

* *`enabled`*: _boolean_ (optional)
+
By making use of this property, you can configure heimdall to enable or disable the metrics service. Defaults to `true` (metrics exposure is enabled).
+
.Disabling metrics.
====
[source, yaml]
----
metrics:
  enabled: false
----
====

Beyond that, the entire configuration happens by making use of the environment variables as defined by https://opentelemetry.io/docs/reference/specification/sdk-environment-variables/[OpenTelemetry Environment Variable Specification] and https://opentelemetry.io/docs/concepts/sdk-configuration/[OpenTelemetry SDK Configuration]. Head over to link:{{< relref "/docs/operations/observability.adoc#_metrics_in_heimdall" >}}[Observability] section and the referenced OTEL documentation for more details.



