---
title: "Metrics"
date: 2022-06-09T22:16:45+02:00
draft: false
weight: 55
menu:
  docs:
    weight: 20
    parent: "Observability"
---

As of today, heimdall only supports https://grafana.com/oss/prometheus/[Prometheus] as metrics backend, which is also enabled by default by exposing available metrics on `0.0.0.0:10250/metrics` endpoint.

== Prometheus

Configuration for Prometheus can be adjusted in the `prometheus` property, which lives in the `metrics` property of heimdall's configuration and supports following properties.

* *`host`*: _string_ (optional)
+
By making use of this property, you can specify the TCP/IP address on which heimdall should listen for connections from client applications. The entry `0.0.0.0` allows listening for all IPv4 addresses. `0.0.0.0` is also the default setting.
+
.Configure heimdall to allow only local TCP/IP “loopback” connections to be made.
====
[source, yaml]
----
metrics:
  prometheus:
    host: 127.0.0.1
----
====

* *`port`*: _integer_ (optional)
+
By making use of this property, you can specify the TCP port the heimdall should listen on. Defaults to `10250`.
+
.Configure heimdall to listen on port `9999` for metrics requests.
====
[source, yaml]
----
metrics:
  prometheus:
    port: 9999
----
====

* *`metrics_path`*: _string_ (optional)
+
By making use of this property, you can specify the path under which prometheus metrics information is made available. Defaults to `/metrics`.
+
.Configure heimdall expose metrics information behind `/prometheus` path.
====
[source, yaml]
----
metrics:
  prometheus:
    metrics_path: /prometheus
----
====
