---
title: "Tracing"
date: 2022-06-09T18:56:12+02:00
draft: false
weight: 60
menu:
  docs:
    weight: 30
    parent: "Observability"
---

Heimdall allows visualization of call flows in your infrastructure. It does this by using https://opentracing.io/[OpenTracing], an open standard designed for distributed tracing.

Following tracing backends are currently supported:

* https://www.jaegertracing.io/[Jaeger]
* https://www.instana.com/[Instana]

== Configuration

By default, tracing is disabled, but can be configured in the `tracing` property of heimdall's configuration and supports following properties.

* *`provider`*: _string_ (mandatory)
+
By making use of this property, you can configure heimdall to enable tracing and use one of the supported tracing providers:
+
--
** `jaeger` - to use https://www.jaegertracing.io/[Jaeger]
** `instana` - to use https://www.instana.com/[Instana]
--
+
Further configuration of the tracer happens with tracer specific environment variables. If you don't do this, Heimdall makes use of tracer specific defaults. Head over to the configuration documentation of the supported tracing system, you want to use, for more details.
+
.Enabling tracing with Jaeger.
====
[source, yaml]
----
tracing:
  provider: jaeger
----

By default, Jaeger client assumes the agent is running on the same host. You can however, as mentioned above, change it by making use of `JAEGER_AGENT_HOST` environment variable.
====

* *`service_name`*: _string_ (optional)
+
By setting this property, you can adjust the service name, appearing for Heimdall for your tracing backend. Defaults to `heimdall`. You can also override this value by making use of tracer specific configuration via environment variables.
+
.Setting the service name, appearing for Heimdall in your tracing backend to `foobar`.
====
[source, yaml]
----
tracing:
  service_name: foobar
----
====


