// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package admission

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewHandlerMock creates a new instance of HandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerMock {
	mock := &HandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HandlerMock is an autogenerated mock type for the Handler type
type HandlerMock struct {
	mock.Mock
}

type HandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HandlerMock) EXPECT() *HandlerMock_Expecter {
	return &HandlerMock_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type HandlerMock
func (_mock *HandlerMock) Handle(ctx context.Context, req *Request) *Response {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 *Response
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Request) *Response); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}
	return r0
}

// HandlerMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type HandlerMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - req *Request
func (_e *HandlerMock_Expecter) Handle(ctx interface{}, req interface{}) *HandlerMock_Handle_Call {
	return &HandlerMock_Handle_Call{Call: _e.mock.On("Handle", ctx, req)}
}

func (_c *HandlerMock_Handle_Call) Run(run func(ctx context.Context, req *Request)) *HandlerMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Request
		if args[1] != nil {
			arg1 = args[1].(*Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HandlerMock_Handle_Call) Return(response *Response) *HandlerMock_Handle_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *HandlerMock_Handle_Call) RunAndReturn(run func(ctx context.Context, req *Request) *Response) *HandlerMock_Handle_Call {
	_c.Call.Return(run)
	return _c
}
