// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package secrets2

import (
	mock "github.com/stretchr/testify/mock"
)

// NewScopeReleaserMock creates a new instance of ScopeReleaserMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScopeReleaserMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScopeReleaserMock {
	mock := &ScopeReleaserMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ScopeReleaserMock is an autogenerated mock type for the scopeReleaser type
type ScopeReleaserMock struct {
	mock.Mock
}

type ScopeReleaserMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ScopeReleaserMock) EXPECT() *ScopeReleaserMock_Expecter {
	return &ScopeReleaserMock_Expecter{mock: &_m.Mock}
}

// releaseScope provides a mock function for the type ScopeReleaserMock
func (_mock *ScopeReleaserMock) releaseScope(namespace string, scope *scope) {
	_mock.Called(namespace, scope)
	return
}

// ScopeReleaserMock_releaseScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'releaseScope'
type ScopeReleaserMock_releaseScope_Call struct {
	*mock.Call
}

// releaseScope is a helper method to define mock.On call
//   - namespace string
//   - scope *scope
func (_e *ScopeReleaserMock_Expecter) releaseScope(namespace interface{}, scope interface{}) *ScopeReleaserMock_releaseScope_Call {
	return &ScopeReleaserMock_releaseScope_Call{Call: _e.mock.On("releaseScope", namespace, scope)}
}

func (_c *ScopeReleaserMock_releaseScope_Call) Run(run func(namespace string, scope *scope)) *ScopeReleaserMock_releaseScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *scope
		if args[1] != nil {
			arg1 = args[1].(*scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScopeReleaserMock_releaseScope_Call) Return() *ScopeReleaserMock_releaseScope_Call {
	_c.Call.Return()
	return _c
}

func (_c *ScopeReleaserMock_releaseScope_Call) RunAndReturn(run func(namespace string, scope *scope)) *ScopeReleaserMock_releaseScope_Call {
	_c.Run(run)
	return _c
}
