// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package secrets2

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewBindingProviderMock creates a new instance of BindingProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBindingProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *BindingProviderMock {
	mock := &BindingProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BindingProviderMock is an autogenerated mock type for the bindingProvider type
type BindingProviderMock struct {
	mock.Mock
}

type BindingProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *BindingProviderMock) EXPECT() *BindingProviderMock_Expecter {
	return &BindingProviderMock_Expecter{mock: &_m.Mock}
}

// certificateBundleBinding provides a mock function for the type BindingProviderMock
func (_mock *BindingProviderMock) certificateBundleBinding(ctx context.Context, reference scopedReference, opts ...ResolveOption) (*binding[CertificateBundle], bindingKey, error) {
	// ResolveOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, reference)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for certificateBundleBinding")
	}

	var r0 *binding[CertificateBundle]
	var r1 bindingKey
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, scopedReference, ...ResolveOption) (*binding[CertificateBundle], bindingKey, error)); ok {
		return returnFunc(ctx, reference, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, scopedReference, ...ResolveOption) *binding[CertificateBundle]); ok {
		r0 = returnFunc(ctx, reference, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*binding[CertificateBundle])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, scopedReference, ...ResolveOption) bindingKey); ok {
		r1 = returnFunc(ctx, reference, opts...)
	} else {
		r1 = ret.Get(1).(bindingKey)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, scopedReference, ...ResolveOption) error); ok {
		r2 = returnFunc(ctx, reference, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// BindingProviderMock_certificateBundleBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'certificateBundleBinding'
type BindingProviderMock_certificateBundleBinding_Call struct {
	*mock.Call
}

// certificateBundleBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - reference scopedReference
//   - opts ...ResolveOption
func (_e *BindingProviderMock_Expecter) certificateBundleBinding(ctx interface{}, reference interface{}, opts ...interface{}) *BindingProviderMock_certificateBundleBinding_Call {
	return &BindingProviderMock_certificateBundleBinding_Call{Call: _e.mock.On("certificateBundleBinding",
		append([]interface{}{ctx, reference}, opts...)...)}
}

func (_c *BindingProviderMock_certificateBundleBinding_Call) Run(run func(ctx context.Context, reference scopedReference, opts ...ResolveOption)) *BindingProviderMock_certificateBundleBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 scopedReference
		if args[1] != nil {
			arg1 = args[1].(scopedReference)
		}
		var arg2 []ResolveOption
		variadicArgs := make([]ResolveOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(ResolveOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BindingProviderMock_certificateBundleBinding_Call) Return(bindingMoqParam *binding[CertificateBundle], bindingKeyMoqParam bindingKey, err error) *BindingProviderMock_certificateBundleBinding_Call {
	_c.Call.Return(bindingMoqParam, bindingKeyMoqParam, err)
	return _c
}

func (_c *BindingProviderMock_certificateBundleBinding_Call) RunAndReturn(run func(ctx context.Context, reference scopedReference, opts ...ResolveOption) (*binding[CertificateBundle], bindingKey, error)) *BindingProviderMock_certificateBundleBinding_Call {
	_c.Call.Return(run)
	return _c
}

// credentialsBinding provides a mock function for the type BindingProviderMock
func (_mock *BindingProviderMock) credentialsBinding(ctx context.Context, reference scopedReference, opts ...ResolveOption) (*binding[Credentials], bindingKey, error) {
	// ResolveOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, reference)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for credentialsBinding")
	}

	var r0 *binding[Credentials]
	var r1 bindingKey
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, scopedReference, ...ResolveOption) (*binding[Credentials], bindingKey, error)); ok {
		return returnFunc(ctx, reference, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, scopedReference, ...ResolveOption) *binding[Credentials]); ok {
		r0 = returnFunc(ctx, reference, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*binding[Credentials])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, scopedReference, ...ResolveOption) bindingKey); ok {
		r1 = returnFunc(ctx, reference, opts...)
	} else {
		r1 = ret.Get(1).(bindingKey)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, scopedReference, ...ResolveOption) error); ok {
		r2 = returnFunc(ctx, reference, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// BindingProviderMock_credentialsBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'credentialsBinding'
type BindingProviderMock_credentialsBinding_Call struct {
	*mock.Call
}

// credentialsBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - reference scopedReference
//   - opts ...ResolveOption
func (_e *BindingProviderMock_Expecter) credentialsBinding(ctx interface{}, reference interface{}, opts ...interface{}) *BindingProviderMock_credentialsBinding_Call {
	return &BindingProviderMock_credentialsBinding_Call{Call: _e.mock.On("credentialsBinding",
		append([]interface{}{ctx, reference}, opts...)...)}
}

func (_c *BindingProviderMock_credentialsBinding_Call) Run(run func(ctx context.Context, reference scopedReference, opts ...ResolveOption)) *BindingProviderMock_credentialsBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 scopedReference
		if args[1] != nil {
			arg1 = args[1].(scopedReference)
		}
		var arg2 []ResolveOption
		variadicArgs := make([]ResolveOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(ResolveOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BindingProviderMock_credentialsBinding_Call) Return(bindingMoqParam *binding[Credentials], bindingKeyMoqParam bindingKey, err error) *BindingProviderMock_credentialsBinding_Call {
	_c.Call.Return(bindingMoqParam, bindingKeyMoqParam, err)
	return _c
}

func (_c *BindingProviderMock_credentialsBinding_Call) RunAndReturn(run func(ctx context.Context, reference scopedReference, opts ...ResolveOption) (*binding[Credentials], bindingKey, error)) *BindingProviderMock_credentialsBinding_Call {
	_c.Call.Return(run)
	return _c
}

// releaseBinding provides a mock function for the type BindingProviderMock
func (_mock *BindingProviderMock) releaseBinding(key bindingKey, count int) {
	_mock.Called(key, count)
	return
}

// BindingProviderMock_releaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'releaseBinding'
type BindingProviderMock_releaseBinding_Call struct {
	*mock.Call
}

// releaseBinding is a helper method to define mock.On call
//   - key bindingKey
//   - count int
func (_e *BindingProviderMock_Expecter) releaseBinding(key interface{}, count interface{}) *BindingProviderMock_releaseBinding_Call {
	return &BindingProviderMock_releaseBinding_Call{Call: _e.mock.On("releaseBinding", key, count)}
}

func (_c *BindingProviderMock_releaseBinding_Call) Run(run func(key bindingKey, count int)) *BindingProviderMock_releaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bindingKey
		if args[0] != nil {
			arg0 = args[0].(bindingKey)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BindingProviderMock_releaseBinding_Call) Return() *BindingProviderMock_releaseBinding_Call {
	_c.Call.Return()
	return _c
}

func (_c *BindingProviderMock_releaseBinding_Call) RunAndReturn(run func(key bindingKey, count int)) *BindingProviderMock_releaseBinding_Call {
	_c.Run(run)
	return _c
}

// secretBinding provides a mock function for the type BindingProviderMock
func (_mock *BindingProviderMock) secretBinding(ctx context.Context, reference scopedReference, opts ...ResolveOption) (*binding[Secret], bindingKey, error) {
	// ResolveOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, reference)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for secretBinding")
	}

	var r0 *binding[Secret]
	var r1 bindingKey
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, scopedReference, ...ResolveOption) (*binding[Secret], bindingKey, error)); ok {
		return returnFunc(ctx, reference, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, scopedReference, ...ResolveOption) *binding[Secret]); ok {
		r0 = returnFunc(ctx, reference, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*binding[Secret])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, scopedReference, ...ResolveOption) bindingKey); ok {
		r1 = returnFunc(ctx, reference, opts...)
	} else {
		r1 = ret.Get(1).(bindingKey)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, scopedReference, ...ResolveOption) error); ok {
		r2 = returnFunc(ctx, reference, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// BindingProviderMock_secretBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'secretBinding'
type BindingProviderMock_secretBinding_Call struct {
	*mock.Call
}

// secretBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - reference scopedReference
//   - opts ...ResolveOption
func (_e *BindingProviderMock_Expecter) secretBinding(ctx interface{}, reference interface{}, opts ...interface{}) *BindingProviderMock_secretBinding_Call {
	return &BindingProviderMock_secretBinding_Call{Call: _e.mock.On("secretBinding",
		append([]interface{}{ctx, reference}, opts...)...)}
}

func (_c *BindingProviderMock_secretBinding_Call) Run(run func(ctx context.Context, reference scopedReference, opts ...ResolveOption)) *BindingProviderMock_secretBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 scopedReference
		if args[1] != nil {
			arg1 = args[1].(scopedReference)
		}
		var arg2 []ResolveOption
		variadicArgs := make([]ResolveOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(ResolveOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BindingProviderMock_secretBinding_Call) Return(bindingMoqParam *binding[Secret], bindingKeyMoqParam bindingKey, err error) *BindingProviderMock_secretBinding_Call {
	_c.Call.Return(bindingMoqParam, bindingKeyMoqParam, err)
	return _c
}

func (_c *BindingProviderMock_secretBinding_Call) RunAndReturn(run func(ctx context.Context, reference scopedReference, opts ...ResolveOption) (*binding[Secret], bindingKey, error)) *BindingProviderMock_secretBinding_Call {
	_c.Call.Return(run)
	return _c
}

// secretSetBinding provides a mock function for the type BindingProviderMock
func (_mock *BindingProviderMock) secretSetBinding(ctx context.Context, reference scopedReference, opts ...ResolveOption) (*binding[[]Secret], bindingKey, error) {
	// ResolveOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, reference)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for secretSetBinding")
	}

	var r0 *binding[[]Secret]
	var r1 bindingKey
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, scopedReference, ...ResolveOption) (*binding[[]Secret], bindingKey, error)); ok {
		return returnFunc(ctx, reference, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, scopedReference, ...ResolveOption) *binding[[]Secret]); ok {
		r0 = returnFunc(ctx, reference, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*binding[[]Secret])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, scopedReference, ...ResolveOption) bindingKey); ok {
		r1 = returnFunc(ctx, reference, opts...)
	} else {
		r1 = ret.Get(1).(bindingKey)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, scopedReference, ...ResolveOption) error); ok {
		r2 = returnFunc(ctx, reference, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// BindingProviderMock_secretSetBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'secretSetBinding'
type BindingProviderMock_secretSetBinding_Call struct {
	*mock.Call
}

// secretSetBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - reference scopedReference
//   - opts ...ResolveOption
func (_e *BindingProviderMock_Expecter) secretSetBinding(ctx interface{}, reference interface{}, opts ...interface{}) *BindingProviderMock_secretSetBinding_Call {
	return &BindingProviderMock_secretSetBinding_Call{Call: _e.mock.On("secretSetBinding",
		append([]interface{}{ctx, reference}, opts...)...)}
}

func (_c *BindingProviderMock_secretSetBinding_Call) Run(run func(ctx context.Context, reference scopedReference, opts ...ResolveOption)) *BindingProviderMock_secretSetBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 scopedReference
		if args[1] != nil {
			arg1 = args[1].(scopedReference)
		}
		var arg2 []ResolveOption
		variadicArgs := make([]ResolveOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(ResolveOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *BindingProviderMock_secretSetBinding_Call) Return(bindingMoqParam *binding[[]Secret], bindingKeyMoqParam bindingKey, err error) *BindingProviderMock_secretSetBinding_Call {
	_c.Call.Return(bindingMoqParam, bindingKeyMoqParam, err)
	return _c
}

func (_c *BindingProviderMock_secretSetBinding_Call) RunAndReturn(run func(ctx context.Context, reference scopedReference, opts ...ResolveOption) (*binding[[]Secret], bindingKey, error)) *BindingProviderMock_secretSetBinding_Call {
	_c.Call.Return(run)
	return _c
}
