logs:
  general:
    level: DEBUG
  access:
    enabled: true

tracing:
  otlp:
    enabled: true
    grpc:
      enabled: true
      endpoint: alloy.monitoring:4317
      insecure: true

metrics:
  prometheus:
    serviceMonitor:
      enabled: true

experimental:
  kubernetesGateway:
    enabled: true
    namespacePolicy: All
    certificate:
      group: ""
      kind: Secret
      name: traefik-tls

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

ports:
  traefik:
    port: 9000
    expose:
      default: true
  web:
    middlewares:
      - heimdall-heimdall@kubernetescrd
  websecure:
    middlewares:
      - heimdall-heimdall@kubernetescrd
