apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: emissary-tls-ingress-listener
  namespace: emissary-ingress-controller
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL