services:
  edge-router:
    image: caddy:2.9.1-alpine@sha256:b4e3952384eb9524a887633ce65c752dd7c71314d2c2acf98cd5c715aaa534f0
    ports:
      - "9090:9090"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  heimdall:
    command: serve decision -c /etc/heimdall/config.yaml --insecure