services:
  heimdall-init:
    image: finalgene/openssh
    command: /tmp/generate_keys.sh
    volumes:
      - ./generate_keys.sh:/tmp/generate_keys.sh:ro
      - heimdall-keys:/etc/heimdall/keys

  heimdall:
    image: dadrus/heimdall:0.17.3
    depends_on:
      heimdall-init:
        condition: service_started
    volumes:
    - ./heimdall-config.yaml:/etc/heimdall/config.yaml:ro
    - ./upstream-rules.yaml:/etc/heimdall/rules.yaml:ro
    - heimdall-keys:/etc/heimdall/keys:ro

  upstream:
    image: containous/whoami:latest
    command: --port=8081

  idp:
    image: nginx:1.29.1
    volumes:
    - ./idp.nginx:/etc/nginx/nginx.conf:ro
    - ./jwks.json:/var/www/nginx/jwks.json:ro

  opa:
    image: openpolicyagent/opa:1.8.0
    command: run --server --addr=0.0.0.0:8181 /etc/opa/policies
    volumes:
    - ./policy.rego:/etc/opa/policies/policy.rego:ro

volumes:
  heimdall-keys:

