services:
  edge-router:
    image: caddy:2.10.0-alpine@sha256:e2e3a089760c453bc51c4e718342bd7032d6714f15b437db7121bfc2de2654a6
    ports:
      - "9090:9090"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  heimdall:
    command: serve decision -c /etc/heimdall/config.yaml --insecure