// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	heimdall "github.com/dadrus/heimdall/internal/heimdall"
	contextualizers "github.com/dadrus/heimdall/internal/rules/mechanisms/contextualizers"

	mock "github.com/stretchr/testify/mock"

	subject "github.com/dadrus/heimdall/internal/rules/mechanisms/subject"
)

// ContextualizerMock is an autogenerated mock type for the Contextualizer type
type ContextualizerMock struct {
	mock.Mock
}

type ContextualizerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ContextualizerMock) EXPECT() *ContextualizerMock_Expecter {
	return &ContextualizerMock_Expecter{mock: &_m.Mock}
}

// ContinueOnError provides a mock function with given fields:
func (_m *ContextualizerMock) ContinueOnError() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ContextualizerMock_ContinueOnError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContinueOnError'
type ContextualizerMock_ContinueOnError_Call struct {
	*mock.Call
}

// ContinueOnError is a helper method to define mock.On call
func (_e *ContextualizerMock_Expecter) ContinueOnError() *ContextualizerMock_ContinueOnError_Call {
	return &ContextualizerMock_ContinueOnError_Call{Call: _e.mock.On("ContinueOnError")}
}

func (_c *ContextualizerMock_ContinueOnError_Call) Run(run func()) *ContextualizerMock_ContinueOnError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ContextualizerMock_ContinueOnError_Call) Return(_a0 bool) *ContextualizerMock_ContinueOnError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContextualizerMock_ContinueOnError_Call) RunAndReturn(run func() bool) *ContextualizerMock_ContinueOnError_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *ContextualizerMock) Execute(_a0 heimdall.RequestContext, _a1 *subject.Subject) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(heimdall.RequestContext, *subject.Subject) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ContextualizerMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ContextualizerMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 heimdall.RequestContext
//   - _a1 *subject.Subject
func (_e *ContextualizerMock_Expecter) Execute(_a0 interface{}, _a1 interface{}) *ContextualizerMock_Execute_Call {
	return &ContextualizerMock_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *ContextualizerMock_Execute_Call) Run(run func(_a0 heimdall.RequestContext, _a1 *subject.Subject)) *ContextualizerMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(heimdall.RequestContext), args[1].(*subject.Subject))
	})
	return _c
}

func (_c *ContextualizerMock_Execute_Call) Return(_a0 error) *ContextualizerMock_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContextualizerMock_Execute_Call) RunAndReturn(run func(heimdall.RequestContext, *subject.Subject) error) *ContextualizerMock_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with given fields:
func (_m *ContextualizerMock) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ContextualizerMock_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type ContextualizerMock_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *ContextualizerMock_Expecter) ID() *ContextualizerMock_ID_Call {
	return &ContextualizerMock_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *ContextualizerMock_ID_Call) Run(run func()) *ContextualizerMock_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ContextualizerMock_ID_Call) Return(_a0 string) *ContextualizerMock_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContextualizerMock_ID_Call) RunAndReturn(run func() string) *ContextualizerMock_ID_Call {
	_c.Call.Return(run)
	return _c
}

// WithConfig provides a mock function with given fields: config
func (_m *ContextualizerMock) WithConfig(config map[string]interface{}) (contextualizers.Contextualizer, error) {
	ret := _m.Called(config)

	var r0 contextualizers.Contextualizer
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) (contextualizers.Contextualizer, error)); ok {
		return rf(config)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) contextualizers.Contextualizer); ok {
		r0 = rf(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contextualizers.Contextualizer)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContextualizerMock_WithConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithConfig'
type ContextualizerMock_WithConfig_Call struct {
	*mock.Call
}

// WithConfig is a helper method to define mock.On call
//   - config map[string]interface{}
func (_e *ContextualizerMock_Expecter) WithConfig(config interface{}) *ContextualizerMock_WithConfig_Call {
	return &ContextualizerMock_WithConfig_Call{Call: _e.mock.On("WithConfig", config)}
}

func (_c *ContextualizerMock_WithConfig_Call) Run(run func(config map[string]interface{})) *ContextualizerMock_WithConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]interface{}))
	})
	return _c
}

func (_c *ContextualizerMock_WithConfig_Call) Return(_a0 contextualizers.Contextualizer, _a1 error) *ContextualizerMock_WithConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContextualizerMock_WithConfig_Call) RunAndReturn(run func(map[string]interface{}) (contextualizers.Contextualizer, error)) *ContextualizerMock_WithConfig_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewContextualizerMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewContextualizerMock creates a new instance of ContextualizerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewContextualizerMock(t mockConstructorTestingTNewContextualizerMock) *ContextualizerMock {
	mock := &ContextualizerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
