apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-cert
  namespace: monitoring
spec:
  dnsNames:
    - "*.minio-hl"
    - "*.minio-hl.monitoring"
    - "*.minio-hl.monitoring.svc"
    - '*.minio-hl.monitoring.svc.cluster.local'
    - "minio.monitoring.svc.cluster.local"
  secretName: minio-tls
  issuerRef:
    name: root-ca
    kind: ClusterIssuer
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-storage-configuration
  namespace: monitoring
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
type: Opaque
---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: Y29uc29sZQ==
  CONSOLE_SECRET_KEY: Y29uc29sZTEyMw==
kind: Secret
metadata:
  name: minio-storage-user
  namespace: monitoring
type: Opaque
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
  labels:
    app: minio
  name: minio
  namespace: monitoring
spec:
  certConfig: {}
  configuration:
    name: minio-storage-configuration
  env: []
  externalCaCertSecret: []
  ## Use certificates generated by cert-manager.
  externalCertSecret:
    - name: minio-tls
      type: cert-manager.io/v1
  externalClientCertSecrets: []
  features:
    bucketDNS: false
    domains: {}
  image: quay.io/minio/minio:RELEASE.2024-10-02T17-50-41Z
  imagePullSecret: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - affinity:
      nodeAffinity: {}
      podAffinity: {}
      podAntiAffinity: {}
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    name: pool-0
    nodeSelector: {}
    resources: {}
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    servers: 4
    tolerations: []
    topologySpreadConstraints: []
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Ti
        storageClassName: standard
      status: {}
    volumesPerServer: 4
  priorityClassName: ""
  ## Disable default tls certificates.
  requestAutoCert: false
  serviceAccountName: ""
  serviceMetadata:
    consoleServiceAnnotations: {}
    consoleServiceLabels: {}
    minioServiceAnnotations: {}
    minioServiceLabels: {}
  subPath: ""
  users:
  - name: minio-storage-user
  buckets:
    - name: tempo
    - name: loki
