apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-gw
  namespace: istio-gw
spec:
  dnsNames:
    - echo-app
    - echo-app.default
    - echo-app.default.svc
    - echo-app.default.svc.cluster.local
    - echo-app.local
  ipAddresses:
    - 172.18.255.200
  secretName: istio-gw-tls
  issuerRef:
    name: root-ca
    kind: ClusterIssuer