secret_management:
  tls_keys:
    type: pem
    config:
      path: "${TEST_KEYSTORE_FILE}"

serve:
  port: 4468
  tls:
    secret:
      source: tls_keys

management:
  tls:
    secret:
      source: tls_keys

mechanisms:
  authenticators:
    - id: some_authenticator
      type: anonymous

  finalizers:
    - id: some_finalizer
      type: noop

providers:
  http_endpoint:
    endpoints:
      - url: http://example.com/rules
