secret_management:
  inline_secrets:
    type: inline
    config:
      client_credentials:
        client_id: test-client-id
        client_secret: test-client-secret
  jwt_secrets:
    type: pem
    config:
      path: "${TEST_KEYSTORE_FILE}"

serve:
  port: 4468
  tls:
    key_store:
      path: /path/to/file.pem

management:
  tls:
    key_store:
      path: /path/to/file.pem

mechanisms:
  authenticators:
    - id: some_authenticator
      type: anonymous

  finalizers:
    - id: some_finalizer
      type: oauth2_client_credentials
      config:
        token_url: http://example.com/token
        credentials:
          source: inline_secrets
          selector: client_credentials

providers:
  file_system:
    src: test_rules.yaml
    watch: true
