secret_management:
  inline_secrets:
    type: inline
    config:
      client_credentials:
        client_id: test-client-id
        client_secret: test-client-secret
  jwt_secrets:
    type: pem
    config:
      path: "${TEST_KEYSTORE_FILE}"
  tls_keys:
    type: pem
    config:
      path: "${TEST_KEYSTORE_FILE}"

serve:
  port: 4468
  tls:
    secret:
      source: tls_keys

management:
  tls:
    secret:
      source: tls_keys

mechanisms:
  authenticators:
    - id: some_authenticator
      type: generic
      config:
        identity_info_endpoint:
          url: https://example.com/whoami
          auth:
            type: oauth2_client_credentials
            config:
              token_url: http://example.com/token
              credentials:
                source: inline_secrets
                selector: client_credentials
        authentication_data_source:
          - cookie: SESSION-ID
        principal:
          id: id

  finalizers:
    - id: some_finalizer
      type: noop

providers:
  file_system:
    src: test_rules.yaml
    watch: true
