serve:
  port: 4468
  tls:
    key_store:
      path: /path/to/file.pem

management:
  tls:
    key_store:
      path: /path/to/file.pem

mechanisms:
  authenticators:
    - id: some_authenticator
      type: anonymous

  finalizers:
    - id: some_finalizer
      type: oauth2_client_credentials
      config:
        token_url: http://example.com/token
        client_id: foo
        client_secret: bar

providers:
  file_system:
    src: test_rules.yaml
    watch: true
