secret_management:
  tls_keys:
    type: pem
    config:
      path: "${TEST_KEYSTORE_FILE}"
  inline_secrets:
    type: inline
    config:
      redis_credentials:
        user: foo
        password: very-secure-one

cache:
  type: redis
  config:
    address: redis:6379
    credentials:
      source: inline_secrets
      selector: redis_credentials
    tls:
      disabled: true

serve:
  port: 4468
  tls:
    secret:
      source: tls_keys

management:
  tls:
    secret:
      source: tls_keys

mechanisms:
  authenticators:
    - id: some_authenticator
      type: anonymous

  finalizers:
    - id: some_finalizer
      type: noop

