secret_management:
  tls_keys:
    type: pem
    config:
      path: "${TEST_KEYSTORE_FILE}"

serve:
  port: 4468
  tls:
    secret:
      source: tls_keys

management:
  tls:
    secret:
      source: tls_keys

mechanisms:
  authenticators:
    - id: some_authenticator
      type: anonymous

  contextualizers:
    - id: some_contextualizer
      type: generic
      config:
        endpoint:
          url: http://example.com
          method: GET

  finalizers:
    - id: some_finalizer
      type: noop

providers:
  file_system:
    src: test_rules.yaml
    watch: true
