---
title: "Traefik Proxy Integration"
date: 2022-06-09T18:59:49+02:00
draft: false
weight: 16
menu:
  guides:
    parent: "API Gateways & Proxies"
description: This guide explains how to integrate heimdall with Traefik Proxy.
---

:toc:

https://doc.traefik.io/traefik/[Traefik Proxy] is a modern HTTP proxy and load balancer for microservices, heimdall can be integrated with via the https://doc.traefik.io/traefik/middlewares/http/forwardauth/[ForwardAuth Middleware]. If heimdall answers with a 2XX code, traefik grants access and forwards the original request to the upstream service. Otherwise, the response from heimdall is returned to the client.

== Prerequisites

* Integration with Envoy proxy requires heimdall being operated in link:{{< relref "/docs/concepts/operating_modes.adoc#_decision_mode" >}}[Decision Operation Mode].

[CAUTION]
====
Traefik makes use of `X-Forwarded-*` HTTP headers to forward the HTTP method, protocol, host, etc. to the ForwardAuth middleware. By default, heimdall does not trust those. To allow heimdall making use of such headers, you must configure link:{{< relref "/docs/services/decision.adoc#_trusted_proxies" >}}[trusted proxies] in heimdall's decision service configuration to contain the IPs or networks of your traefik instances. For test purposes, you can set it to "0.0.0.0/0", which would basically disable the check and let heimdall trust requests from any source.
====

== Vanilla Traefik

Traefik can be configured statically, but also load dynamic configuration from many sources managed by so-called providers. The two following sections describe how to integrate with heimdall using both approaches.

=== Global Configuration

To let Traefik forward all incoming requests to heimdall, there is a need

* to configure the https://doc.traefik.io/traefik/middlewares/http/forwardauth/[ForwardAuth] middleware, and
* to add it to the list of https://doc.traefik.io/traefik/routing/entrypoints/#middlewares[middlewares] that are prepended by default to the list of middlewares of each router associated to a named entry point.

Both is shown in the snippet below

[source, yaml]
----
entryPoints:
  http:
    address: ":8080"
    middlewares: # <1>
    - heimdall

http:
  middlewares:
    heimdall: # <2>
      forwardAuth: # <3>
        address: "https://heimdall:4456" # <4>
        authResponseHeaders:
        - Authorization # <5>

----
<1> The list of default middlewares. Here only the middleware named "heimdall" is included. That way, traefik will use this middleware for each and every request.
<2> The definition of the middleware named "heimdall"
<3> which is of type https://doc.traefik.io/traefik/middlewares/http/forwardauth/[`forwardAuth`]
<4> Configures this middleware to forward requests to a service available under "heimdall" DNS name
<5> Configures this middleware to forward the `Authorization` header from heimdall's response to the upstream service

=== Route-based Configuration

The integration options, described here makes use of the https://doc.traefik.io/traefik/providers/docker/[Docker Provider] for configuration discovery.

The following `docker-compose.yaml` file shows a minimal required configuration.

[source, yaml]
----
version: '3.7'

services:
  proxy:
    image: traefik:2.11.0
    ports:
    - "9090:9090"
    command: >
      --providers.docker=true <1>
      --providers.docker.exposedbydefault=false
      --entryPoints.http.address=":9090"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro" # <2>
    # other config options
    labels:
    # other labels
    - traefik.http.middlewares.heimdall.forwardauth.address=http://heimdall:4456 # <3>
    - traefik.http.middlewares.heimdall.forwardauth.authResponseHeaders=Authorization # <4>

  heimdall:
    image: dadrus/heimdall:latest
    # further config

  upstream:
    # image and config of your upstream service
    labels:
    # other labels
    - traefik.http.routers.upstream.middlewares=heimdall # <5>
----
<1> This and the next line configures the docker provider
<2> The docker provider reads the configuration from labels of the services and requires access to the docker socket for this purpose
<3> Configuration of the https://doc.traefik.io/traefik/middlewares/http/forwardauth/[ForwardAuth] middleware to forward incoming requests to heimdall. The name of middleware is set to "heimdall" here.
<4> Configuration of the ForwardAuth middleware to forward the `Authorization` header from heimdall's response to the upstream service
<5> Configuration of the required middlewares on the route level of a particular service. Here only the middleware named "heimdall" is referenced. Without that label, traefik will not forward requests to heimdall before routing them to that upstream service.

== Traefik Ingress Controller

If you have Traefik as Ingress Controller in your Kubernetes cluster, you can simply integrate heimdall globally as descibed in link:{{< relref "#_global_configuration" >}}[Global Configuration] chapter above and make use of the standard https://kubernetes.io/docs/concepts/services-networking/ingress/[Ingress resource].

There is also an option to have a route based configuration. In that case, you'll have to use Traefik proprietary https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-middleware[`Middleware`] and https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroute[`IngressRoute`] custom resources to define and use the https://doc.traefik.io/traefik/middlewares/http/forwardauth/[ForwardAuth] middleware.

== Additional Resources

A fully working example with Traefik is shown in the link:{{< relref "/docs/getting_started/protect_an_app.adoc" >}}[Protect an Application] quickstart and is also available on https://github.com/dadrus/heimdall/tree/main/examples[GitHub].

====
