// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dadrus/heimdall/internal/secrets"
	mock "github.com/stretchr/testify/mock"
)

// NewCredentialsHandleMock creates a new instance of CredentialsHandleMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialsHandleMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialsHandleMock {
	mock := &CredentialsHandleMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CredentialsHandleMock is an autogenerated mock type for the CredentialsHandle type
type CredentialsHandleMock struct {
	mock.Mock
}

type CredentialsHandleMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialsHandleMock) EXPECT() *CredentialsHandleMock_Expecter {
	return &CredentialsHandleMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type CredentialsHandleMock
func (_mock *CredentialsHandleMock) Get() (secrets.Credentials, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 secrets.Credentials
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (secrets.Credentials, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() secrets.Credentials); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secrets.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// CredentialsHandleMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CredentialsHandleMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *CredentialsHandleMock_Expecter) Get() *CredentialsHandleMock_Get_Call {
	return &CredentialsHandleMock_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *CredentialsHandleMock_Get_Call) Run(run func()) *CredentialsHandleMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CredentialsHandleMock_Get_Call) Return(v secrets.Credentials, b bool) *CredentialsHandleMock_Get_Call {
	_c.Call.Return(v, b)
	return _c
}

func (_c *CredentialsHandleMock_Get_Call) RunAndReturn(run func() (secrets.Credentials, bool)) *CredentialsHandleMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// OnUpdate provides a mock function for the type CredentialsHandleMock
func (_mock *CredentialsHandleMock) OnUpdate(callback secrets.UpdateFunc[secrets.Credentials]) {
	_mock.Called(callback)
	return
}

// CredentialsHandleMock_OnUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnUpdate'
type CredentialsHandleMock_OnUpdate_Call struct {
	*mock.Call
}

// OnUpdate is a helper method to define mock.On call
//   - callback secrets.UpdateFunc[secrets.Credentials]
func (_e *CredentialsHandleMock_Expecter) OnUpdate(callback interface{}) *CredentialsHandleMock_OnUpdate_Call {
	return &CredentialsHandleMock_OnUpdate_Call{Call: _e.mock.On("OnUpdate", callback)}
}

func (_c *CredentialsHandleMock_OnUpdate_Call) Run(run func(callback secrets.UpdateFunc[secrets.Credentials])) *CredentialsHandleMock_OnUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 secrets.UpdateFunc[secrets.Credentials]
		if args[0] != nil {
			arg0 = args[0].(secrets.UpdateFunc[secrets.Credentials])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CredentialsHandleMock_OnUpdate_Call) Return() *CredentialsHandleMock_OnUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *CredentialsHandleMock_OnUpdate_Call) RunAndReturn(run func(callback secrets.UpdateFunc[secrets.Credentials])) *CredentialsHandleMock_OnUpdate_Call {
	_c.Run(run)
	return _c
}
