// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dadrus/heimdall/internal/secrets"
	mock "github.com/stretchr/testify/mock"
)

// NewResolverMock creates a new instance of ResolverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResolverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResolverMock {
	mock := &ResolverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResolverMock is an autogenerated mock type for the Resolver type
type ResolverMock struct {
	mock.Mock
}

type ResolverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ResolverMock) EXPECT() *ResolverMock_Expecter {
	return &ResolverMock_Expecter{mock: &_m.Mock}
}

// CertificateBundle provides a mock function for the type ResolverMock
func (_mock *ResolverMock) CertificateBundle(ctx context.Context, ref secrets.Reference) (secrets.CertificateBundleHandle, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for CertificateBundle")
	}

	var r0 secrets.CertificateBundleHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) (secrets.CertificateBundleHandle, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) secrets.CertificateBundleHandle); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secrets.CertificateBundleHandle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, secrets.Reference) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResolverMock_CertificateBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificateBundle'
type ResolverMock_CertificateBundle_Call struct {
	*mock.Call
}

// CertificateBundle is a helper method to define mock.On call
//   - ctx context.Context
//   - ref secrets.Reference
func (_e *ResolverMock_Expecter) CertificateBundle(ctx interface{}, ref interface{}) *ResolverMock_CertificateBundle_Call {
	return &ResolverMock_CertificateBundle_Call{Call: _e.mock.On("CertificateBundle", ctx, ref)}
}

func (_c *ResolverMock_CertificateBundle_Call) Run(run func(ctx context.Context, ref secrets.Reference)) *ResolverMock_CertificateBundle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 secrets.Reference
		if args[1] != nil {
			arg1 = args[1].(secrets.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResolverMock_CertificateBundle_Call) Return(certificateBundleHandle secrets.CertificateBundleHandle, err error) *ResolverMock_CertificateBundle_Call {
	_c.Call.Return(certificateBundleHandle, err)
	return _c
}

func (_c *ResolverMock_CertificateBundle_Call) RunAndReturn(run func(ctx context.Context, ref secrets.Reference) (secrets.CertificateBundleHandle, error)) *ResolverMock_CertificateBundle_Call {
	_c.Call.Return(run)
	return _c
}

// Credentials provides a mock function for the type ResolverMock
func (_mock *ResolverMock) Credentials(ctx context.Context, ref secrets.Reference) (secrets.CredentialsHandle, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Credentials")
	}

	var r0 secrets.CredentialsHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) (secrets.CredentialsHandle, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) secrets.CredentialsHandle); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secrets.CredentialsHandle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, secrets.Reference) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResolverMock_Credentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Credentials'
type ResolverMock_Credentials_Call struct {
	*mock.Call
}

// Credentials is a helper method to define mock.On call
//   - ctx context.Context
//   - ref secrets.Reference
func (_e *ResolverMock_Expecter) Credentials(ctx interface{}, ref interface{}) *ResolverMock_Credentials_Call {
	return &ResolverMock_Credentials_Call{Call: _e.mock.On("Credentials", ctx, ref)}
}

func (_c *ResolverMock_Credentials_Call) Run(run func(ctx context.Context, ref secrets.Reference)) *ResolverMock_Credentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 secrets.Reference
		if args[1] != nil {
			arg1 = args[1].(secrets.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResolverMock_Credentials_Call) Return(credentialsHandle secrets.CredentialsHandle, err error) *ResolverMock_Credentials_Call {
	_c.Call.Return(credentialsHandle, err)
	return _c
}

func (_c *ResolverMock_Credentials_Call) RunAndReturn(run func(ctx context.Context, ref secrets.Reference) (secrets.CredentialsHandle, error)) *ResolverMock_Credentials_Call {
	_c.Call.Return(run)
	return _c
}

// Secret provides a mock function for the type ResolverMock
func (_mock *ResolverMock) Secret(ctx context.Context, ref secrets.Reference) (secrets.SecretHandle, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Secret")
	}

	var r0 secrets.SecretHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) (secrets.SecretHandle, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) secrets.SecretHandle); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secrets.SecretHandle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, secrets.Reference) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResolverMock_Secret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Secret'
type ResolverMock_Secret_Call struct {
	*mock.Call
}

// Secret is a helper method to define mock.On call
//   - ctx context.Context
//   - ref secrets.Reference
func (_e *ResolverMock_Expecter) Secret(ctx interface{}, ref interface{}) *ResolverMock_Secret_Call {
	return &ResolverMock_Secret_Call{Call: _e.mock.On("Secret", ctx, ref)}
}

func (_c *ResolverMock_Secret_Call) Run(run func(ctx context.Context, ref secrets.Reference)) *ResolverMock_Secret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 secrets.Reference
		if args[1] != nil {
			arg1 = args[1].(secrets.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResolverMock_Secret_Call) Return(secretHandle secrets.SecretHandle, err error) *ResolverMock_Secret_Call {
	_c.Call.Return(secretHandle, err)
	return _c
}

func (_c *ResolverMock_Secret_Call) RunAndReturn(run func(ctx context.Context, ref secrets.Reference) (secrets.SecretHandle, error)) *ResolverMock_Secret_Call {
	_c.Call.Return(run)
	return _c
}

// SecretSet provides a mock function for the type ResolverMock
func (_mock *ResolverMock) SecretSet(ctx context.Context, ref secrets.Reference) (secrets.SecretSetHandle, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for SecretSet")
	}

	var r0 secrets.SecretSetHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) (secrets.SecretSetHandle, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) secrets.SecretSetHandle); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secrets.SecretSetHandle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, secrets.Reference) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResolverMock_SecretSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecretSet'
type ResolverMock_SecretSet_Call struct {
	*mock.Call
}

// SecretSet is a helper method to define mock.On call
//   - ctx context.Context
//   - ref secrets.Reference
func (_e *ResolverMock_Expecter) SecretSet(ctx interface{}, ref interface{}) *ResolverMock_SecretSet_Call {
	return &ResolverMock_SecretSet_Call{Call: _e.mock.On("SecretSet", ctx, ref)}
}

func (_c *ResolverMock_SecretSet_Call) Run(run func(ctx context.Context, ref secrets.Reference)) *ResolverMock_SecretSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 secrets.Reference
		if args[1] != nil {
			arg1 = args[1].(secrets.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResolverMock_SecretSet_Call) Return(secretSetHandle secrets.SecretSetHandle, err error) *ResolverMock_SecretSet_Call {
	_c.Call.Return(secretSetHandle, err)
	return _c
}

func (_c *ResolverMock_SecretSet_Call) RunAndReturn(run func(ctx context.Context, ref secrets.Reference) (secrets.SecretSetHandle, error)) *ResolverMock_SecretSet_Call {
	_c.Call.Return(run)
	return _c
}
