// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dadrus/heimdall/internal/secrets"
	mock "github.com/stretchr/testify/mock"
)

// NewScopedResolverFactoryMock creates a new instance of ScopedResolverFactoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScopedResolverFactoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScopedResolverFactoryMock {
	mock := &ScopedResolverFactoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ScopedResolverFactoryMock is an autogenerated mock type for the ScopedResolverFactory type
type ScopedResolverFactoryMock struct {
	mock.Mock
}

type ScopedResolverFactoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ScopedResolverFactoryMock) EXPECT() *ScopedResolverFactoryMock_Expecter {
	return &ScopedResolverFactoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ScopedResolverFactoryMock
func (_mock *ScopedResolverFactoryMock) Create(opts ...secrets.ScopeOption) secrets.ScopedResolver {
	// secrets.ScopeOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 secrets.ScopedResolver
	if returnFunc, ok := ret.Get(0).(func(...secrets.ScopeOption) secrets.ScopedResolver); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secrets.ScopedResolver)
		}
	}
	return r0
}

// ScopedResolverFactoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ScopedResolverFactoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - opts ...secrets.ScopeOption
func (_e *ScopedResolverFactoryMock_Expecter) Create(opts ...interface{}) *ScopedResolverFactoryMock_Create_Call {
	return &ScopedResolverFactoryMock_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{}, opts...)...)}
}

func (_c *ScopedResolverFactoryMock_Create_Call) Run(run func(opts ...secrets.ScopeOption)) *ScopedResolverFactoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []secrets.ScopeOption
		variadicArgs := make([]secrets.ScopeOption, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(secrets.ScopeOption)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *ScopedResolverFactoryMock_Create_Call) Return(scopedResolver secrets.ScopedResolver) *ScopedResolverFactoryMock_Create_Call {
	_c.Call.Return(scopedResolver)
	return _c
}

func (_c *ScopedResolverFactoryMock_Create_Call) RunAndReturn(run func(opts ...secrets.ScopeOption) secrets.ScopedResolver) *ScopedResolverFactoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}
