// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dadrus/heimdall/internal/secrets"
	mock "github.com/stretchr/testify/mock"
)

// NewScopedResolverMock creates a new instance of ScopedResolverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScopedResolverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScopedResolverMock {
	mock := &ScopedResolverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ScopedResolverMock is an autogenerated mock type for the ScopedResolver type
type ScopedResolverMock struct {
	mock.Mock
}

type ScopedResolverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ScopedResolverMock) EXPECT() *ScopedResolverMock_Expecter {
	return &ScopedResolverMock_Expecter{mock: &_m.Mock}
}

// AwaitReady provides a mock function for the type ScopedResolverMock
func (_mock *ScopedResolverMock) AwaitReady(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AwaitReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ScopedResolverMock_AwaitReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AwaitReady'
type ScopedResolverMock_AwaitReady_Call struct {
	*mock.Call
}

// AwaitReady is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ScopedResolverMock_Expecter) AwaitReady(ctx interface{}) *ScopedResolverMock_AwaitReady_Call {
	return &ScopedResolverMock_AwaitReady_Call{Call: _e.mock.On("AwaitReady", ctx)}
}

func (_c *ScopedResolverMock_AwaitReady_Call) Run(run func(ctx context.Context)) *ScopedResolverMock_AwaitReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ScopedResolverMock_AwaitReady_Call) Return(err error) *ScopedResolverMock_AwaitReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ScopedResolverMock_AwaitReady_Call) RunAndReturn(run func(ctx context.Context) error) *ScopedResolverMock_AwaitReady_Call {
	_c.Call.Return(run)
	return _c
}

// CertificateBundle provides a mock function for the type ScopedResolverMock
func (_mock *ScopedResolverMock) CertificateBundle(ctx context.Context, ref secrets.Reference) (secrets.CertificateBundleHandle, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for CertificateBundle")
	}

	var r0 secrets.CertificateBundleHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) (secrets.CertificateBundleHandle, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) secrets.CertificateBundleHandle); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secrets.CertificateBundleHandle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, secrets.Reference) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScopedResolverMock_CertificateBundle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificateBundle'
type ScopedResolverMock_CertificateBundle_Call struct {
	*mock.Call
}

// CertificateBundle is a helper method to define mock.On call
//   - ctx context.Context
//   - ref secrets.Reference
func (_e *ScopedResolverMock_Expecter) CertificateBundle(ctx interface{}, ref interface{}) *ScopedResolverMock_CertificateBundle_Call {
	return &ScopedResolverMock_CertificateBundle_Call{Call: _e.mock.On("CertificateBundle", ctx, ref)}
}

func (_c *ScopedResolverMock_CertificateBundle_Call) Run(run func(ctx context.Context, ref secrets.Reference)) *ScopedResolverMock_CertificateBundle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 secrets.Reference
		if args[1] != nil {
			arg1 = args[1].(secrets.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScopedResolverMock_CertificateBundle_Call) Return(certificateBundleHandle secrets.CertificateBundleHandle, err error) *ScopedResolverMock_CertificateBundle_Call {
	_c.Call.Return(certificateBundleHandle, err)
	return _c
}

func (_c *ScopedResolverMock_CertificateBundle_Call) RunAndReturn(run func(ctx context.Context, ref secrets.Reference) (secrets.CertificateBundleHandle, error)) *ScopedResolverMock_CertificateBundle_Call {
	_c.Call.Return(run)
	return _c
}

// Credentials provides a mock function for the type ScopedResolverMock
func (_mock *ScopedResolverMock) Credentials(ctx context.Context, ref secrets.Reference) (secrets.CredentialsHandle, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Credentials")
	}

	var r0 secrets.CredentialsHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) (secrets.CredentialsHandle, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) secrets.CredentialsHandle); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secrets.CredentialsHandle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, secrets.Reference) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScopedResolverMock_Credentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Credentials'
type ScopedResolverMock_Credentials_Call struct {
	*mock.Call
}

// Credentials is a helper method to define mock.On call
//   - ctx context.Context
//   - ref secrets.Reference
func (_e *ScopedResolverMock_Expecter) Credentials(ctx interface{}, ref interface{}) *ScopedResolverMock_Credentials_Call {
	return &ScopedResolverMock_Credentials_Call{Call: _e.mock.On("Credentials", ctx, ref)}
}

func (_c *ScopedResolverMock_Credentials_Call) Run(run func(ctx context.Context, ref secrets.Reference)) *ScopedResolverMock_Credentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 secrets.Reference
		if args[1] != nil {
			arg1 = args[1].(secrets.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScopedResolverMock_Credentials_Call) Return(credentialsHandle secrets.CredentialsHandle, err error) *ScopedResolverMock_Credentials_Call {
	_c.Call.Return(credentialsHandle, err)
	return _c
}

func (_c *ScopedResolverMock_Credentials_Call) RunAndReturn(run func(ctx context.Context, ref secrets.Reference) (secrets.CredentialsHandle, error)) *ScopedResolverMock_Credentials_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type ScopedResolverMock
func (_mock *ScopedResolverMock) Release() {
	_mock.Called()
	return
}

// ScopedResolverMock_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type ScopedResolverMock_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
func (_e *ScopedResolverMock_Expecter) Release() *ScopedResolverMock_Release_Call {
	return &ScopedResolverMock_Release_Call{Call: _e.mock.On("Release")}
}

func (_c *ScopedResolverMock_Release_Call) Run(run func()) *ScopedResolverMock_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ScopedResolverMock_Release_Call) Return() *ScopedResolverMock_Release_Call {
	_c.Call.Return()
	return _c
}

func (_c *ScopedResolverMock_Release_Call) RunAndReturn(run func()) *ScopedResolverMock_Release_Call {
	_c.Run(run)
	return _c
}

// Secret provides a mock function for the type ScopedResolverMock
func (_mock *ScopedResolverMock) Secret(ctx context.Context, ref secrets.Reference) (secrets.SecretHandle, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Secret")
	}

	var r0 secrets.SecretHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) (secrets.SecretHandle, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) secrets.SecretHandle); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secrets.SecretHandle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, secrets.Reference) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScopedResolverMock_Secret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Secret'
type ScopedResolverMock_Secret_Call struct {
	*mock.Call
}

// Secret is a helper method to define mock.On call
//   - ctx context.Context
//   - ref secrets.Reference
func (_e *ScopedResolverMock_Expecter) Secret(ctx interface{}, ref interface{}) *ScopedResolverMock_Secret_Call {
	return &ScopedResolverMock_Secret_Call{Call: _e.mock.On("Secret", ctx, ref)}
}

func (_c *ScopedResolverMock_Secret_Call) Run(run func(ctx context.Context, ref secrets.Reference)) *ScopedResolverMock_Secret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 secrets.Reference
		if args[1] != nil {
			arg1 = args[1].(secrets.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScopedResolverMock_Secret_Call) Return(secretHandle secrets.SecretHandle, err error) *ScopedResolverMock_Secret_Call {
	_c.Call.Return(secretHandle, err)
	return _c
}

func (_c *ScopedResolverMock_Secret_Call) RunAndReturn(run func(ctx context.Context, ref secrets.Reference) (secrets.SecretHandle, error)) *ScopedResolverMock_Secret_Call {
	_c.Call.Return(run)
	return _c
}

// SecretSet provides a mock function for the type ScopedResolverMock
func (_mock *ScopedResolverMock) SecretSet(ctx context.Context, ref secrets.Reference) (secrets.SecretSetHandle, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for SecretSet")
	}

	var r0 secrets.SecretSetHandle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) (secrets.SecretSetHandle, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, secrets.Reference) secrets.SecretSetHandle); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(secrets.SecretSetHandle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, secrets.Reference) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScopedResolverMock_SecretSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecretSet'
type ScopedResolverMock_SecretSet_Call struct {
	*mock.Call
}

// SecretSet is a helper method to define mock.On call
//   - ctx context.Context
//   - ref secrets.Reference
func (_e *ScopedResolverMock_Expecter) SecretSet(ctx interface{}, ref interface{}) *ScopedResolverMock_SecretSet_Call {
	return &ScopedResolverMock_SecretSet_Call{Call: _e.mock.On("SecretSet", ctx, ref)}
}

func (_c *ScopedResolverMock_SecretSet_Call) Run(run func(ctx context.Context, ref secrets.Reference)) *ScopedResolverMock_SecretSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 secrets.Reference
		if args[1] != nil {
			arg1 = args[1].(secrets.Reference)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ScopedResolverMock_SecretSet_Call) Return(secretSetHandle secrets.SecretSetHandle, err error) *ScopedResolverMock_SecretSet_Call {
	_c.Call.Return(secretSetHandle, err)
	return _c
}

func (_c *ScopedResolverMock_SecretSet_Call) RunAndReturn(run func(ctx context.Context, ref secrets.Reference) (secrets.SecretSetHandle, error)) *ScopedResolverMock_SecretSet_Call {
	_c.Call.Return(run)
	return _c
}
