// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dadrus/heimdall/internal/secrets"
	mock "github.com/stretchr/testify/mock"
)

// NewSecretSetHandleMock creates a new instance of SecretSetHandleMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretSetHandleMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretSetHandleMock {
	mock := &SecretSetHandleMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SecretSetHandleMock is an autogenerated mock type for the SecretSetHandle type
type SecretSetHandleMock struct {
	mock.Mock
}

type SecretSetHandleMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretSetHandleMock) EXPECT() *SecretSetHandleMock_Expecter {
	return &SecretSetHandleMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type SecretSetHandleMock
func (_mock *SecretSetHandleMock) Get(ctx context.Context) ([]secrets.Secret, bool) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []secrets.Secret
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]secrets.Secret, bool)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []secrets.Secret); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]secrets.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// SecretSetHandleMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SecretSetHandleMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SecretSetHandleMock_Expecter) Get(ctx interface{}) *SecretSetHandleMock_Get_Call {
	return &SecretSetHandleMock_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *SecretSetHandleMock_Get_Call) Run(run func(ctx context.Context)) *SecretSetHandleMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SecretSetHandleMock_Get_Call) Return(vs []secrets.Secret, b bool) *SecretSetHandleMock_Get_Call {
	_c.Call.Return(vs, b)
	return _c
}

func (_c *SecretSetHandleMock_Get_Call) RunAndReturn(run func(ctx context.Context) ([]secrets.Secret, bool)) *SecretSetHandleMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// OnUpdate provides a mock function for the type SecretSetHandleMock
func (_mock *SecretSetHandleMock) OnUpdate(updateFunc secrets.UpdateFunc[[]secrets.Secret]) {
	_mock.Called(updateFunc)
	return
}

// SecretSetHandleMock_OnUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnUpdate'
type SecretSetHandleMock_OnUpdate_Call struct {
	*mock.Call
}

// OnUpdate is a helper method to define mock.On call
//   - updateFunc secrets.UpdateFunc[[]secrets.Secret]
func (_e *SecretSetHandleMock_Expecter) OnUpdate(updateFunc interface{}) *SecretSetHandleMock_OnUpdate_Call {
	return &SecretSetHandleMock_OnUpdate_Call{Call: _e.mock.On("OnUpdate", updateFunc)}
}

func (_c *SecretSetHandleMock_OnUpdate_Call) Run(run func(updateFunc secrets.UpdateFunc[[]secrets.Secret])) *SecretSetHandleMock_OnUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 secrets.UpdateFunc[[]secrets.Secret]
		if args[0] != nil {
			arg0 = args[0].(secrets.UpdateFunc[[]secrets.Secret])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SecretSetHandleMock_OnUpdate_Call) Return() *SecretSetHandleMock_OnUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *SecretSetHandleMock_OnUpdate_Call) RunAndReturn(run func(updateFunc secrets.UpdateFunc[[]secrets.Secret])) *SecretSetHandleMock_OnUpdate_Call {
	_c.Run(run)
	return _c
}
