{{- if not .Values.demoSetup }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "heimdall.fullname" . }}-config
  {{- include "heimdall.namespace" . | nindent 2 }}
  labels:
{{ include "heimdall.labels" . | indent 4 }}
data:
  heimdall.yaml: |
    {{- with .Values.serve }}
    serve:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.log }}
    log:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.metrics }}
    metrics:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.tracing }}
    tracing:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.signer }}
    signer:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.pipeline }}
    pipeline:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.rules }}
    rules:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}