{{- $data := dict "Release" .Release "Values" .Values "Chart" .Chart "Component" "service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "heimdall.fullname" $data }}
  {{- include "heimdall.namespace" $data | nindent 2 }}
  labels:
    {{- include "heimdall.labels" $data | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.management.port }}
      targetPort: http-management
      protocol: TCP
      name: {{ .Values.service.management.name }}
      {{- if eq .Values.operationMode "decision" }}
    - port: {{ .Values.service.decision.port }}
      targetPort: http-decision
      protocol: TCP
      name: {{ .Values.service.decision.name }}
      {{- else if eq .Values.operationMode "proxy" }}
    - port: {{ .Values.service.proxy.port }}
      targetPort: http-proxy
      protocol: TCP
      name: {{ .Values.service.proxy.name }}
      {{- else }}
      {{- required "A valid operationMode is required!" .Values.operationMode -}}
      {{- end }}
  selector:
    {{- include "heimdall.selectorLabels" $data | nindent 4 }}
