// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	"net/http"

	"github.com/stretchr/testify/mock"
)

// ErrorHandlerMock is an autogenerated mock type for the ErrorHandler type
type ErrorHandlerMock struct {
	mock.Mock
}

type ErrorHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorHandlerMock) EXPECT() *ErrorHandlerMock_Expecter {
	return &ErrorHandlerMock_Expecter{mock: &_m.Mock}
}

// HandleError provides a mock function with given fields: rw, req, err
func (_m *ErrorHandlerMock) HandleError(rw http.ResponseWriter, req *http.Request, err error) {
	_m.Called(rw, req, err)
}

// ErrorHandlerMock_HandleError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleError'
type ErrorHandlerMock_HandleError_Call struct {
	*mock.Call
}

// HandleError is a helper method to define mock.On call
//   - rw http.ResponseWriter
//   - req *http.Request
//   - err error
func (_e *ErrorHandlerMock_Expecter) HandleError(rw interface{}, req interface{}, err interface{}) *ErrorHandlerMock_HandleError_Call {
	return &ErrorHandlerMock_HandleError_Call{Call: _e.mock.On("HandleError", rw, req, err)}
}

func (_c *ErrorHandlerMock_HandleError_Call) Run(run func(rw http.ResponseWriter, req *http.Request, err error)) *ErrorHandlerMock_HandleError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request), args[2].(error))
	})
	return _c
}

func (_c *ErrorHandlerMock_HandleError_Call) Return() *ErrorHandlerMock_HandleError_Call {
	_c.Call.Return()
	return _c
}

func (_c *ErrorHandlerMock_HandleError_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request, error)) *ErrorHandlerMock_HandleError_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewErrorHandlerMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewErrorHandlerMock creates a new instance of ErrorHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewErrorHandlerMock(t mockConstructorTestingTNewErrorHandlerMock) *ErrorHandlerMock {
	mock := &ErrorHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
