// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package source

import (
	"context"

	"github.com/dadrus/heimdall/internal/secrets/types"
	mock "github.com/stretchr/testify/mock"
)

// NewDependencyResolverMock creates a new instance of DependencyResolverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDependencyResolverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DependencyResolverMock {
	mock := &DependencyResolverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DependencyResolverMock is an autogenerated mock type for the DependencyResolver type
type DependencyResolverMock struct {
	mock.Mock
}

type DependencyResolverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DependencyResolverMock) EXPECT() *DependencyResolverMock_Expecter {
	return &DependencyResolverMock_Expecter{mock: &_m.Mock}
}

// ResolveCredentials provides a mock function for the type DependencyResolverMock
func (_mock *DependencyResolverMock) ResolveCredentials(ctx context.Context, reference types.SecretRef) (types.Credentials, error) {
	ret := _mock.Called(ctx, reference)

	if len(ret) == 0 {
		panic("no return value specified for ResolveCredentials")
	}

	var r0 types.Credentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.SecretRef) (types.Credentials, error)); ok {
		return returnFunc(ctx, reference)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.SecretRef) types.Credentials); ok {
		r0 = returnFunc(ctx, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.SecretRef) error); ok {
		r1 = returnFunc(ctx, reference)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DependencyResolverMock_ResolveCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveCredentials'
type DependencyResolverMock_ResolveCredentials_Call struct {
	*mock.Call
}

// ResolveCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - reference types.SecretRef
func (_e *DependencyResolverMock_Expecter) ResolveCredentials(ctx interface{}, reference interface{}) *DependencyResolverMock_ResolveCredentials_Call {
	return &DependencyResolverMock_ResolveCredentials_Call{Call: _e.mock.On("ResolveCredentials", ctx, reference)}
}

func (_c *DependencyResolverMock_ResolveCredentials_Call) Run(run func(ctx context.Context, reference types.SecretRef)) *DependencyResolverMock_ResolveCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.SecretRef
		if args[1] != nil {
			arg1 = args[1].(types.SecretRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DependencyResolverMock_ResolveCredentials_Call) Return(credentials types.Credentials, err error) *DependencyResolverMock_ResolveCredentials_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *DependencyResolverMock_ResolveCredentials_Call) RunAndReturn(run func(ctx context.Context, reference types.SecretRef) (types.Credentials, error)) *DependencyResolverMock_ResolveCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveSecret provides a mock function for the type DependencyResolverMock
func (_mock *DependencyResolverMock) ResolveSecret(ctx context.Context, reference types.SecretRef) (types.Secret, error) {
	ret := _mock.Called(ctx, reference)

	if len(ret) == 0 {
		panic("no return value specified for ResolveSecret")
	}

	var r0 types.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.SecretRef) (types.Secret, error)); ok {
		return returnFunc(ctx, reference)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.SecretRef) types.Secret); ok {
		r0 = returnFunc(ctx, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.SecretRef) error); ok {
		r1 = returnFunc(ctx, reference)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DependencyResolverMock_ResolveSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveSecret'
type DependencyResolverMock_ResolveSecret_Call struct {
	*mock.Call
}

// ResolveSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - reference types.SecretRef
func (_e *DependencyResolverMock_Expecter) ResolveSecret(ctx interface{}, reference interface{}) *DependencyResolverMock_ResolveSecret_Call {
	return &DependencyResolverMock_ResolveSecret_Call{Call: _e.mock.On("ResolveSecret", ctx, reference)}
}

func (_c *DependencyResolverMock_ResolveSecret_Call) Run(run func(ctx context.Context, reference types.SecretRef)) *DependencyResolverMock_ResolveSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.SecretRef
		if args[1] != nil {
			arg1 = args[1].(types.SecretRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DependencyResolverMock_ResolveSecret_Call) Return(secret types.Secret, err error) *DependencyResolverMock_ResolveSecret_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *DependencyResolverMock_ResolveSecret_Call) RunAndReturn(run func(ctx context.Context, reference types.SecretRef) (types.Secret, error)) *DependencyResolverMock_ResolveSecret_Call {
	_c.Call.Return(run)
	return _c
}
