---
title: "Concepts"
date: 2022-06-25T14:29:17+02:00
draft: false
weight: 10
menu:
  docs:
    parent: "Getting Started"
    weight: 10
  main:
    parent: get_started
---

Everything you need to know.

== Pipeline

As described in the link:{{< relref "/docs/welcome.adoc" >}}[Welcome] section and also shown in the link:{{< relref "#_fig_heimdall_request_pipeline" >}}[diagram] below, Heimdall authenticates and authorizes incoming HTTP requests, rejecting unauthenticated or unauthorized ones, as well as enriches the valid requests with further information and transforms resulting subject information to a format, required by the upstream services. This is done in upstream service specific link:{{< relref "/docs/configuration/rules/overview.adoc" >}}[rules], which define the required individual link:{{< relref "/docs/configuration/pipeline/overview.adoc" >}}[pipelines].

[[_fig_heimdall_request_pipeline]]
.Request Pipeline
[ditaa, format=svg]
....
                 /-----------------------------------------------------------------------------------\
                 |                                                                                   |
                 :                                Heimdall's Pipeline                                |<- controlled by> --+
                 |                                                                                   |                    |
                 |+------------------+ +------------------+ +------------------+ +------------------+|                    |
                 || cCCC             | | cCCC             | | cCCC             | | cCCC             ||                    :
                 || 1. Authenticate  | | 2. Contextualize | | 3. Authorize     | | 4. Unify         ||                    |
                 ||                  | |                  | |                  | |                  ||   +------------------+
                 |+------------------+ +------------------+ +------------------+ +------------------+|   |  Backend Service |
                 |                                                                                   |   |                  |
+------------+   |                                                                                   |   |+----------------+|
|            |   |                                                                                   |   ||                ||
|   Client   |   |                                   Client Request Journey                          |   ||    Business    ||
|            |------------------------------------------------------------------------------------------>||                ||
|   Request  |   :                                                                                   |   ||    Logic       ||
|            |   |                                                                                   |   ||                ||
|            |   \-----------------------------------------------------------------------------------/   |+----------------+|
+------------+                                                                                           +------------------+
....

Each rule defines which pipeline steps are required and executed in which order.

In general each rule contains

* an identifier - to uniquely identify a rule
* an url pattern - to match the incoming request against
* a list of allowed HTTP methods for the matched requests
* a regular pipeline, consisting of a list with
** *authentication* mechanisms, so-called link:{{< relref "/docs/configuration/pipeline/authenticators.adoc" >}}[Authenticators], to be executed (if multiple are defined, they are executed as fallbacks) - step 1 in the figure above.
** *contextualization* mechanisms, so-called link:{{< relref "/docs/configuration/pipeline/hydrators.adoc" >}}[Hydrators], to be executed (if multiple are defined, they are executed in the order of their definition; can be mixed with authorization mechanisms) - step 2 in the figure above.
** *authorization* mechanisms, so-called link:{{< relref "/docs/configuration/pipeline/authorizers.adoc" >}}[Authorizers], to be executed (if multiple are defined, they are executed in the order of their definition; can be mixed with contextualization mechanisms) - step 3 in the figure above.
** *unification* mechanisms, so-called link:{{< relref "/docs/configuration/pipeline/mutators.adoc" >}}[Mutators], to be executed (if multiple are defined, they are executed in the order of their definition) - step 4 in the figure above.
* an error pipeline, consisting of an link:{{< relref "/docs/configuration/pipeline/error_handlers.adoc" >}}[error handler] list (if multiple are defined, they are executed as fallbacks), which are executed if any of the regular pipeline mechanisms fails. These range from a simple error response to the client, which sent the request, to sophisticated handlers supporting complex logic and redirects.

The diagram below sketches the related execution logic

[mermaid, format=svg, width=70%]
....
flowchart TD
    req[Request] --> findRule{1: url\nmatches\nrule?}
    findRule -->|yes| methodCheck{2: method\nallowed?}
    findRule -->|no| err1[404 Not Found]
    methodCheck -->|yes| regularPipeline[3: execute regular pipeline]
    methodCheck -->|no| err2[405 Method Not Allowed]
    regularPipeline --> failed{failed?}
    failed -->|yes| errPipeline[execute error pipeline]
    failed -->|no| success[4: forward request,\nrespectively respond\nto the API gateway]
    errPipeline --> errResult[5: result of the\nused error handler]
....

. *Url matches rule?* - This is the first step executed by heimdall. The information about the scheme, host and path is taken either from the URL itself, or if present from the `X-Forwarded-Proto`, `X-Forwarded-Host`, `X-Forwarded-Uri` headers of the incoming request. The request is denied if there is no matching rule. Otherwise, the rule specific pipeline is executed.
. *Method allowed?* - As soon as a rule matches a request, a verification is done whether the used HTTP method is allowed or not. The information about the HTTP method is either taken from the request itself or, if present from the `X-Forwarded-Method`.
. *Execute regular pipeline* - when the above steps succeed, the regular pipeline mechanisms defined in the matched rule are executed.
. *Forward request, respectively respond to the API gateway* - when the above steps succeed, heimdall, depending on the link:{{< relref "#_operating_modes" >}}[operating mode], responds with, respectively forwards whatever was defined in the pipeline (usually this is a set of HTTP headers). Otherwise
. *Execute error pipeline* is executed if any of the mechanisms, defined in the regular pipeline fail. This again results in a response, this time however, based on the definition in the used error handler.

== Operating Modes

To support different deployment scenarios, Heimdall supports two operating modes:

* as a link:{{< relref "#_proxy_mode" >}}[Reverse Proxy] in front of your upstream API or web server, or
* as a link:{{< relref "#_decision_api_mode" >}}[Decision API], integrated with your Reverse Proxy, or API Gateway (like https://konghq.com/[Kong], https://nginx.org[NGNIX], https://www.envoyproxy.io/[Envoy], https://traefik.io/[Traefik] and much more)

=== Proxy Mode

[[_fig_heimdall_proxy_deployment]]
.Proxy Deployment
[ditaa, format=svg]
....
                                                                          +------------------------+
                                                                          |     Backend Service    |
                                                                          |                        |
+------------+                    +---------------------+                 |  +------------------+  |
|            |                    |                     |                 |  |                  |  |
|   Client   |                    |                     |                 |  |    Business      |  |
|            |----- request ----->|      Heimdall       |---- request --->|  |                  |  |
|            |                    |                     |     + header    |  |    Logic         |  |
|            |                    |                     |                 |  |                  |  |
+------------+                    +---------------------+                 |  +------------------+  |
                                             :                            |                        |
                                        uses |                            +------------------------+
                                             v                                         |
                                      -----------------+                               |
                                    -----------------+ |                               |
                                  +----------------+ | |                               :
                                  |                | | |<----=-- defined by>  ---------+
                                  |    pipeline    | | |
                                  |                | | |
                                  |   definitions  | | +
                                  |                | +
                                  +----------------+
....

In this mode heimdall forwards requests to the upstream service, if these satisfy the conditions defined in pipeline definition rules. Otherwise, heimdall returns an error to the client. If the pipeline execution was successful, it also forwards additional headers, specified in the used pipeline to the upstream service.

Starting heimdall in this mode happens via the `serve proxy` command. Head over to the description of link:{{< relref "/docs/operations/cli.adoc" >}}[CLI] as well as link:{{< relref "/docs/configuration/services/proxy.adoc" >}}[Configuration] options for more details.

.Reverse Proxy Example
====
Imagine following request hits Heimdall

[source, bash]
----
GET /my-service/api HTTP/1.1
Host: heimdall:4455

Some payload
----

And there is a rule, which defines a pipeline, allowing anonymous requests and setting a header with subject id set to `anonymous` like this

[source, yaml]
----
id: rule:my-service:anonymous-api-access
url: /my-service/api
for: https://my-backend-service:8888
methods:
  - GET
execute:
  - authenticator: anonymous-authn
  - mutator: id-header
----

Then the request will be forwarded as follows:

[source, bash]
----
GET /my-service/api HTTP/1.1
Host: my-backend-service:8888
X-User-ID: anonymous

Some payload
----

====

=== Decision API Mode

[[_fig_heimdall_decision_api_deployment]]
.Decision API Deployment
[ditaa, format=svg]
....
                                                                          +------------------------+
                                                                          |     Backend Service    |
                                                                          |                        |
+------------+                    +---------------------+                 |  +------------------+  |
|            |                    |                     |                 |  |                  |  |
|   Client   |                    |                     |                 |  |    Business      |  |
|            |----- request ----->|      API Gateway    |---- request --->|  |                  |  |
|            |                    |                     |     + header    |  |    Logic         |  |
|            |                    |                     |                 |  |                  |  |
+------------+                    +---------------------+                 |  +------------------+  |
                                         |       ^                        |                        |
                                         |       |                        +------------------------+
                           ok to forward |  ok / not ok                                |
                           request?      |   + header                                  |
                                         |       |                                     |
                                         |       |                                     |
                                         v       |                                     |
                                  +---------------------+                              |
                                  |                     |                              |
                                  |       Heimdall      |                              |
                                  |                     |                              |
                                  +---------------------+                              |
                                             |                                         |
                                        uses :                                         |
                                             v                                         |
                                      -----------------+                               |
                                    -----------------+ |                               |
                                  +----------------+ | |                               :
                                  |                | | |<----=-- defined by>  ---------+
                                  |    pipeline    | | |
                                  |                | | |
                                  |   definitions  | | +
                                  |                | +
                                  +----------------+
....

In this mode, you can integrate heimdall with most probably all modern API gateways and reverse proxies as a so-called "authentication middleware". Here the reverse proxy, respectively API gateway integrating with heimdall, will forward requests to heimdall by making use of its `decisions` endpoint for authentication and authorization purposes. As in the link:{{< relref "#_proxy_mode" >}}[Reverse Proxy] mode, heimdall will check if these satisfy the conditions defined in pipeline definition rules. Otherwise, heimdall returns an error to its client (here API gateway/reverse proxy). If the pipeline execution was successful, it also responds to the API gateway/reverse proxy with additional headers, specified in the used pipeline, which can then be forwarded by it to the upstream service.

Starting heimdall in this mode happens via the `serve api` command. Head over to the description of link:{{< relref "/docs/operations/cli.adoc" >}}[CLI] as well as to link:{{< relref "/docs/configuration/services/decision_api.adoc" >}}[Configuration] options for more details.

.Decision API Example
====
Imagine following request hits Heimdall (sent to it by an API gateway)

[source, bash]
----
GET decisions/my-service/api HTTP/1.1
Host: heimdall:4455

Some payload
----

And there is a rule, which defines a pipeline, allowing anonymous requests and setting a header with subject id set to `anonymous` like this

[source, yaml]
----
id: rule:my-service:anonymous-api-access
url: /my-service/api
methods:
  - GET
execute:
  - authenticator: anonymous-authn
  - mutator: id-header
----

Then heimdall will respond with:

[source, bash]
----
HTTP/1.1 202 Accepted
X-User-ID: anonymous
----

====