---
title: "Core Concepts"
date: 2023-11-29T22:06:28+02:00
draft: false
weight: 6
menu:
  docs:
    parent: "Getting Started"
    weight: 10
description: Gives you the required insights about heimdall's architecture to get started.
---

:toc:

== How are the challenges addressed

Remember the figure from link:{{< relref "/docs/getting_started/what_is_heimdall.adoc#_challenges_addressed_by_heimdall">}}["Challenges addressed by Heimdall"]?

.Typical microservice deployment scenario
[ditaa, format=svg]
....
                                              +------------------+
                                              |                  |
                                              |  Authentication  |
                          +-----------------> |                  |
                          |                   |    System        |
                          |                   |                  |
                          |                   +------------------+
                          |
                          |            +--------------------------------------------------------------------+
                          |            |                                                                    |-+
                          |            |                          Microservice (Code)                       | |
                          |            |                                                                    | |
+------------+   +--------+--------+   |  +-------------------+  +------------------+  +-----------------+  | |
|            |   |                 |   |  |                   |  |                  |  |                 |  | |
|            |   |  Authentication |   |  |  Verify Request's |  |    Authorize     |  |    Business     |  | |
|   Client   +-->|                 +-->|  |                   |  |                  |  |                 |  | |
|            |   |      Proxy      |   |  |  Authentication   |  |     Request      |  |     Logic       |  | |
|            |   |                 |   |  |                   |  |                  |  |                 |  | |
+------------+   +-----------------+   |  +-------------------+  +----+--------+----+  +-----------------+  | |
                                       |                              |        |                            | |
                                       +------------------------------|--------|----------------------------+ |
                                          ----------------------------|--------|------------------------------+
                                           +--------------------------+        |
                                           |                                   |
                                           v                                   v
                                 +------------------+                +------------------+
                                 |                  |                |                  |-+
                                 |  Authorization   |                |  Other Services  | |
                                 |                  +--------------->|                  | |
                                 |    System        |                |                  | |
                                 |                  |                |                  | |
                                 +------------------+                +------------------+ |
                                                                       -------------------+
....

What if we let heimdall care about most of the existing authentication and authorization challenges? Our new setup would look as depicted below.

.Heimdall based deployment scenario
[ditaa, format=svg]
....

                                              +------------------+
                                              |                  |-+
                                              |  Authentication  | |
                          +-----------------> |                  | |
                          |                   |    System        | |
                          |                   |                  | |
                          |                   +------------------+ |
                          |                      ------------------+
                          |
                          |            +--------------------------------------------+
                          |            |                                            |
                          |            |            Microservice (Code)             |
                          |            |                                            |
+------------+   +--------+--------+   |  +------------------+  +-----------------+ |
|            |   |                 |   |  |                  |  |                 | |
|            |   |                 |   |  |    Authorize     |  |    Business     | |
|   Client   +-->|     Heimdall    +-->|  |                  |  |                 | |
|            |   |                 |   |  |     Request      |  |     Logic       | |
|            |   |                 |   |  |                  |  |                 | |
+------------+   +----+-------+----+   |  +------------------+  +-----------------+ |
                      |       |        +--------------------------------------------+
                      |       |
           +----------+       +---------+
           |                            |
           v                            v
  +------------------+         +------------------+
  |                  |-+       |                  |-+
  |  Authorization   | |       |  Other Services  | |
  |                  | |       |                  | |
  |    System        | |       |                  | |
  |                  | |       |                  | |
  +------------------+ |       +------------------+ |
     ------------------+         -------------------+

....

This way you let heimdall orchestrate existing authentication and authorization systems and also provide the information about the authenticated and authorized subjects to your microservice in a unified format completely independent of the used authentication strategy or protocol. There is however still the need to perform some type of authorization logic in your microservice code. Especially if we talk about read requests (most probably you want to provide different representation of the requested resource based on the authorization status). But it is much simpler, and it gives you much more freedom compared to all previous approaches.

== How it works

Heimdall intercepts all your application related HTTP(s) traffic, allowing a broad set of identity and application aware authentication and authorization features based on the rules you specify and deploy together with your particular service. These rules let heimdall route each request through a service or even endpoint specific authentication and authorization pipeline as depicted in diagram below.

[[_fig_heimdall_request_pipeline]]
.Authentication & Authorization Pipeline
[ditaa, format=svg]
....
                 /-----------------------------------------------------------------------------------\
                 |                                                                                   |
                 :                     Authentication & Authorization Pipeline                       |<- controlled by> --+
                 |                                                                                   |                    |
                 |+------------------+ +------------------+ +------------------+ +------------------+|                    |
                 || cCCC             | | cCCC             | | cCCC             | | cCCC             ||                    :
                 || 1. Authenticate  | | 2. Contextualize | | 3. Authorize     | | 4. Finalize      ||                    |
                 ||                  | |                  | |                  | |                  ||   +------------------+
                 |+------------------+ +------------------+ +------------------+ +------------------+|   |                  |
                 |                                                                                   |   |                  |
+------------+   |                                                                                   |   |   Microservice   |
|            |   |                                                                                   |   |                  |
|   Client   |   |                             Client Request Journey                                |   |                  |
|            |------------------------------------------------------------------------------------------>|                  |
|            |   :                                                                                   |   |                  |
|            |   \-----------------------------------------------------------------------------------/   |                  |
+------------+                                                                                           +------------------+
....

This pipeline ensures that, according to the needs of the particular backend service endpoint,

. each request is authenticated (so, you know who the subject of the request is) by making use of the available identity management systems,
. the required contextual information about the subject is available (like e.g. current location based on IP, roles or groups membership information, etc.) by retrieving it from any possible API, so that
. the subject can be and is authorized by your authorization system, or even directly by heimdall and
. the information about the subject is transformed into a format, required by the backend service. So that despite the used authentication or authorization system or protocol, the subject information is always provided in the same stable representation to your microservice.





