---
title: "Decision API Quickstart"
date: 2022-06-08T20:43:27+02:00
draft: false
weight: 15
menu:
  docs:
    parent: "Getting Started"
    weight: 20
  main:
    parent: get_started
---

This document describes a very simple use case in which you'll see Heimdall's Decision API in action.

== Prerequisites

* link:{{< relref "/docs/operations/install.adoc" >}}[Download Heimdall] in your flavor.

== Configure

heimdall can be configured via environment variables, as well as using a configuration file. For simplicity reasons, we'll use a configuration file here. So create a config file (`config.yaml`) with the following content:

[source, yaml]
----
log:
  level: info // <1>

pipeline:
  authenticators:
    - id: anonymous_authenticator // <2>
      type: anonymous
  mutators:
    - id: create_jwt // <3>
      type: jwt

rules:
  default: // <4>
    methods:
      - GET
      - POST
    execute:
      - authenticator: anonymous_authenticator
      - mutator: create_jwt
----
<1> Here we are setting the log level to `info` to be able to see any log output. By default, Heimdall logs on `error` log level.
<2> Configures the `anonymous` authenticator.
<3> Configured the `jwt` mutator.
<4> Configures the default rule.

Put together, this configuration will let Heimdall create a JSON Web Token (JWT) with `sub` claim set to `anonymous` for every request on every URL for the HTTP methods GET and POST. The JWT itself will be put into the `Authorization` header as a bearer token.

== Run in Decision operation mode
Run heimdall specifying the configuration file from above

If you're using a binary, just execute

[source, bash]
----
$ ./heimdall serve api -c config.yaml
----

The above command will start heimdall in a link:{{< relref "concepts.adoc#_decision_api_mode" >}}[decision api] mode. By default, the service will be served on port `4456`.

Otherwise, if you've built a Docker image, run heimdall in the link:{{< relref "concepts.adoc#_decision_api_mode" >}}[decision api] mode via

[source, bash]
----
$ docker run -t -v $PWD:/heimdall/conf -p 4456:4456 \
  heimdal:local serve api -c /heimdall/conf/config.yaml
----

In both cases, you'll see similar output to

[source, bash]
----
4:07PM INF No opentracing provider configured. Tracing will be disabled.
4:07PM INF Instantiating in memory cache
4:07PM INF Loading pipeline definitions
4:07PM WRN No rule provider configured. Only defaults will be used.
4:07PM WRN Key store is not configured. NEVER DO IT IN PRODUCTION!!!! Generating an RSA key pair.
4:07PM WRN No key id for signer configured. Taking first entry from the key store
4:07PM INF Starting cache evictor
4:07PM INF Starting rule definition loader
4:07PM INF Prometheus endpoint starts listening on: :9000
4:07PM INF Decision API endpoint starts listening on: :4456
4:07PM INF Management endpoint starts listening on: :4457
----

Ignore the warnings. They are expected as we've neither configured a rule provider, nor have we configured a key store for JWT signing purposes. Nevertheless, the default rule can be used.

== Use

Sent some request to heimdall's decision endpoint:

[source, bash]
----
$ curl -v 127.0.0.1:4456/decisions/foobar
----

Here, we're asking to apply the default rule for the `foobar` path using the `GET` HTTP verb.

On completion, you should see the `Authorization` header in the response, like in the output below:

[source, bash]
----
*   Trying 127.0.0.1:4456...
* Connected to 127.0.0.1 (127.0.0.1) port 4456 (#0)
> GET /decisions/foobar HTTP/1.1
> Host: 127.0.0.1:4456
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 202 Accepted
< Server: Heimdall Decision API
< Date: Sat, 25 Jun 2022 14:10:16 GMT
< Content-Length: 0
< Authorization: Bearer eyJhbGciOiJQUzI1NiIsImtpZCI6IjJkZGIxZDM3MWU1MGFjNDQ5ZGJhNjcyNj
ZmZDRjMzU0OWZjNmRmYTYiLCJ0eXAiOiJKV1QifQeyJleHAiOjE2NTYxNjY1MTYsImlhdCI6MTY1NjE2NjIxNi
wiaXNzIjoiaGVpbWRhbGwiLCJqdGkiOiIxYjdlODdjYi0zYjdjLTQ1ZDAtYWEyZi00MTRhYmI2YjBlMzciLCJu
YmYiOjE2NTYxNjYyMTYsInN1YiI6ImFub255bW91cyJ9MY6fjk7K6ZNn57Mrjy6UGI1cvIMCOOEJoCQF45PHQ3
4BfoPxMuTRjdVUZPX4xnT4suyWySsaU1wisgXv4CuMf4WsEUCPKOH8NKv5Zty6eXjTdWQpekDWYsHpVVwz8UHL
mrRASlo_JKErj64wPbRcQWyLMR9X-4cR28ZuH3IbyXh4-XlGNEMAVWYFaZGv1QlEd7jcw3jSVK0b5AtY-NUcVQ
lccWpqWD43AE-3spchqboFuiuW5IxFGd4Mc0Dp6uepuQ-XiWEFg9rxnaxl-Grr3LfSY83oML53Akrl4lGtVBu5
5QVVjduv_b2ykRnqh7Im9lSivokuVMEuSE8bN2qnqg
<
* Connection #0 to host 127.0.0.1 left intact
----

You should also be able to see similar output as below from the heimdall instance

[source, bash]
----
...
4:10PM INF Handling request http_host=127.0.0.1:4456 http_method=GET
           http_url=http://127.0.0.1:4456/foobar http_user_agent=curl/7.74.0
4:10PM INF Access request granted. granted=true http_host=127.0.0.1:4456
           http_method=GET http_url=http://127.0.0.1:4456/foobar http_user_agent=curl/7.74.0
----