---
title: "What is heimdall"
date: 2023-11-29T22:03:28+02:00
draft: false
weight: 5
menu:
  docs:
    parent: "Getting Started"
    weight: 5
---

:toc:

Heimdall is a cloud native identity aware proxy and access control decision service inspired by the Zero Trust idea. It can be integrated into available proxies and API gateways or operated stand alone and help you scaling and securing you services by transparently adding security capabilities and secure defaults related to authentication and authorization. It brings together authentication and authorization systems and can be thought as an orchestrator for these in front of your services, allowing however completely retaining control even without the need for any type of maintenance in your own code.

== Challenges addressed by Heimdall

A typical (monolithic) system, or named it service, has not only to deal with the actual business logic, but also with authentication and authorization requirements (among other non-functional requirements) as depicted in the figure below.

[ditaa, format=svg]
.A typical monolithic system
....
                                             +------------------+
                                             |                  |
                                             |  Authentication  |
                               +------------>|                  |
                               |             |    System        |
                               |             |                  |
                               |             +------------------+
                               |
                  +------------|-------------------------------------------------------+
                  |            |                                                       |
                  |            |                Service (Code)                         |
                  |            |                                                       |
+------------+    |  +---------+---------+  +--------+---------+  +-----------------+  |
|            |    |  |                   |  |                  |  |                 |  |
|            |    |  |   Authenticate    |  |    Authorize     |  |    Business     |  |
|   Client   +--->|  |                   |  |                  |  |                 |  |
|            |    |  |     Request       |  |     Request      |  |     Logic       |  |
|            |    |  |                   |  |                  |  |                 |  |
+------------+    |  +-------------------+  +---+--------+-----+  +-----------------+  |
                  |                             |        |                             |
                  +-----------------------------|--------|-----------------------------+
                                                |        |
                    +---------------------------+        |
                    |                                    |
                    v                                    v
          +------------------+                +------------------+
          |                  |                |                  |-+
          |  Authorization   |                |  Other Services  | |
          |                  +--------------->|                  | |
          |    System        |                |                  | |
          |                  |                |                  | |
          +------------------+                +------------------+ |
                                                -------------------+

....

What do we have here?

* To cover authentication requirements, that service will make use of some identity management system to verify the request authentication status.
* The existing authorization requirements will most probably result in if else statements in code. Even such approaches are straight forward and easy to implement on the first sight, these are not easy to maintain and have many drawbacks (e.g. testing of particular use cases), and it becomes even more challenging when entering microservices.

How does it look then if we have microservices?

* Not every microservice will hold the entire information required for authorization purposes.
* So, there will be a need to communicate to other services to get the required contextual information about the authenticated subject to be able to take the required authorization decision.
* The management and maintenance of the authorization requirements will become even more challenging, as the implementation of these will usually be scattered across many services.

To overcome these dependencies, organizations either start pushing that contextual information into the identity management system, making it a god system with all resulting negative effects, or start using special purpose authorization systems, allowing managing the corresponding authorization policies outside the code.

Even that approach reduces dependencies between the services and also the time to market, it introduces a new dependency, which all, or almost all services must make use of. And, most probably, the authorization system will also need to somehow retrieve contextual information for authorization policy evaluation purposes.

And we just started to scratch the top of the iceberg. What if our system, comprised from these microservices is implemented in different languages? Even there are many libraries and also frameworks addressing authentication challenges, usually we just want to make the lives of our developers easier by providing components, which work the same way for each and every language. So the setup depicted above, well become similar to the one depicted below.

[[_fig_typical_deployment_scenario]]
.Typical microservice deployment scenario
[ditaa, format=svg]
....
                                              +------------------+
                                              |                  |
                                              |  Authentication  |
                          +-----------------> |                  |
                          |                   |    System        |
                          |                   |                  |
                          |                   +------------------+
                          |
                          |            +--------------------------------------------------------------------+
                          |            |                                                                    |-+
                          |            |                          Microservice (Code)                       | |
                          |            |                                                                    | |
+------------+   +--------+--------+   |  +-------------------+  +------------------+  +-----------------+  | |
|            |   |                 |   |  |                   |  |                  |  |                 |  | |
|            |   |  Authentication |   |  |  Verify Request's |  |    Authorize     |  |    Business     |  | |
|   Client   +-->|                 +-->|  |                   |  |                  |  |                 |  | |
|            |   |      Proxy      |   |  |  Authentication   |  |     Request      |  |     Logic       |  | |
|            |   |                 |   |  |                   |  |                  |  |                 |  | |
+------------+   +-----------------+   |  +-------------------+  +----+--------+----+  +-----------------+  | |
                                       |                              |        |                            | |
                                       +------------------------------|--------|----------------------------+ |
                                          ----------------------------|--------|------------------------------+
                                           +--------------------------+        |
                                           |                                   |
                                           v                                   v
                                 +------------------+                +------------------+
                                 |                  |                |                  |-+
                                 |  Authorization   |                |  Other Services  | |
                                 |                  +--------------->|                  | |
                                 |    System        |                |                  | |
                                 |                  |                |                  | |
                                 +------------------+                +------------------+ |
                                                                       -------------------+
....

Here, a new authentication proxy, typically deployed as a sidecar with each microservice (sometimes also as a central proxy), is introduced taking over the responsibility for the existing authentication challenges and unifying the corresponding implementation. But there are still many drawbacks and limitations, like those addressed by the following questions

* What if there is a need to have multiple identity management systems, e.g. one for the customers and one for accessing administrative or backoffice related functionality of the system?
* What if there is a need to migrate from one authentication or authorization system to another?
* What if there is a need to open the existing APIs?
* What if there is a need to support multiple different clients, like browsers, like mobile apps, IoT devices, etc?
* What if the business decides to change the existing authorization requirements, like introduction of a new subscription model, or alike, which would require additional information about our user, resulting in yet another dependency to some further service?
* What if depending on the client, we need completely different authentication strategies or even protocols, like OAuth2 or OpenID Connect in one case, mTLS in another case and cookie based approach and yet another case?
* How to ensure, that our microservice code does not implement shortcuts and thus does not compromise the security of the entire system? (And there are diverse options achieving that)
* ...

This is by far not an exhaustive list. But the main question related to it is what does all of that mean in sense of coordination-, implementation efforts and time-to-market?

This is exactly where heimdall can step in and help you to address these challenges, reduce the complexity of your code, free resources, increase your time to market and make your system more secure.