// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oauth2

import (
	"time"

	"github.com/dadrus/heimdall/internal/pipeline"
	"github.com/go-jose/go-jose/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewPoPStrategyMock creates a new instance of PoPStrategyMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPoPStrategyMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PoPStrategyMock {
	mock := &PoPStrategyMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PoPStrategyMock is an autogenerated mock type for the PoPStrategy type
type PoPStrategyMock struct {
	mock.Mock
}

type PoPStrategyMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PoPStrategyMock) EXPECT() *PoPStrategyMock_Expecter {
	return &PoPStrategyMock_Expecter{mock: &_m.Mock}
}

// Assert provides a mock function for the type PoPStrategyMock
func (_mock *PoPStrategyMock) Assert(ctx pipeline.Context, token *Token, leeway time.Duration, allowedAlgorithms []jose.SignatureAlgorithm) error {
	ret := _mock.Called(ctx, token, leeway, allowedAlgorithms)

	if len(ret) == 0 {
		panic("no return value specified for Assert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(pipeline.Context, *Token, time.Duration, []jose.SignatureAlgorithm) error); ok {
		r0 = returnFunc(ctx, token, leeway, allowedAlgorithms)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PoPStrategyMock_Assert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assert'
type PoPStrategyMock_Assert_Call struct {
	*mock.Call
}

// Assert is a helper method to define mock.On call
//   - ctx pipeline.Context
//   - token *Token
//   - leeway time.Duration
//   - allowedAlgorithms []jose.SignatureAlgorithm
func (_e *PoPStrategyMock_Expecter) Assert(ctx interface{}, token interface{}, leeway interface{}, allowedAlgorithms interface{}) *PoPStrategyMock_Assert_Call {
	return &PoPStrategyMock_Assert_Call{Call: _e.mock.On("Assert", ctx, token, leeway, allowedAlgorithms)}
}

func (_c *PoPStrategyMock_Assert_Call) Run(run func(ctx pipeline.Context, token *Token, leeway time.Duration, allowedAlgorithms []jose.SignatureAlgorithm)) *PoPStrategyMock_Assert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pipeline.Context
		if args[0] != nil {
			arg0 = args[0].(pipeline.Context)
		}
		var arg1 *Token
		if args[1] != nil {
			arg1 = args[1].(*Token)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 []jose.SignatureAlgorithm
		if args[3] != nil {
			arg3 = args[3].([]jose.SignatureAlgorithm)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PoPStrategyMock_Assert_Call) Return(err error) *PoPStrategyMock_Assert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PoPStrategyMock_Assert_Call) RunAndReturn(run func(ctx pipeline.Context, token *Token, leeway time.Duration, allowedAlgorithms []jose.SignatureAlgorithm) error) *PoPStrategyMock_Assert_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function for the type PoPStrategyMock
func (_mock *PoPStrategyMock) Merge(other PoPStrategy) PoPStrategy {
	ret := _mock.Called(other)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 PoPStrategy
	if returnFunc, ok := ret.Get(0).(func(PoPStrategy) PoPStrategy); ok {
		r0 = returnFunc(other)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PoPStrategy)
		}
	}
	return r0
}

// PoPStrategyMock_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type PoPStrategyMock_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - other PoPStrategy
func (_e *PoPStrategyMock_Expecter) Merge(other interface{}) *PoPStrategyMock_Merge_Call {
	return &PoPStrategyMock_Merge_Call{Call: _e.mock.On("Merge", other)}
}

func (_c *PoPStrategyMock_Merge_Call) Run(run func(other PoPStrategy)) *PoPStrategyMock_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 PoPStrategy
		if args[0] != nil {
			arg0 = args[0].(PoPStrategy)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PoPStrategyMock_Merge_Call) Return(poPStrategy PoPStrategy) *PoPStrategyMock_Merge_Call {
	_c.Call.Return(poPStrategy)
	return _c
}

func (_c *PoPStrategyMock_Merge_Call) RunAndReturn(run func(other PoPStrategy) PoPStrategy) *PoPStrategyMock_Merge_Call {
	_c.Call.Return(run)
	return _c
}
