apiVersion: v1
kind: ConfigMap
metadata:
  name: heimdall-config
  namespace: quickstarts
  labels:
    app.kubernetes.io/name: echo-app
immutable: true
data:
  heimdall.yaml: |
    log:
      level: debug

    serve:
      proxy:
        trusted_proxies:
          - 0.0.0.0/0

    mechanisms:
      authenticators:
        - id: anonymous_authenticator
          type: anonymous
        - id: deny_authenticator
          type: unauthorized
      authorizers:
        - id: deny_all_requests
          type: deny
        - id: allow_all_requests
          type: allow
      finalizers:
        - id: create_jwt
          type: jwt
          config:
            signer:
              key_store:
                path: /etc/heimdall/certs/jwt/tls-combined.pem
      error_handlers:
        - id: redirect
          type: redirect
          if: type(Error) == authentication_error
          config:
            to: http://foo.bar?origin={{ .Request.URL | urlenc }}

    default_rule:
      execute:
        - authenticator: anonymous_authenticator
        - authorizer: deny_all_requests
      on_error:
        - error_handler: redirect

    providers:
      file_system:
        src: /heimdall/rules.yaml