apiVersion: v1
kind: ConfigMap
metadata:
  name: heimdall-config
  namespace: quickstarts
  labels:
    app.kubernetes.io/name: echo-app
immutable: true
data:
  heimdall.yaml: |
    log:
      level: debug

    serve:
      proxy:
        trusted_proxies:
          - 0.0.0.0/0

    mechanisms:
      authenticators:
        - id: anonymous_authenticator
          type: anonymous
        - id: deny_authenticator
          type: unauthorized
      authorizers:
        - id: deny_all_requests
          type: deny
        - id: allow_all_requests
          type: allow
      finalizers:
        - id: create_jwt
          type: jwt
      error_handlers:
        - id: redirect
          type: redirect
          config:
            to: http://foo.bar?origin={{ .Request.URL | urlenc }}
            when:
              - error:
                  - type: authentication_error
    default_rule:
      methods:
        - GET
        - POST
      execute:
        - authenticator: anonymous_authenticator
        - authorizer: deny_all_requests
      on_error:
        - error_handler: redirect

    providers:
      file_system:
        src: /heimdall/rules.yaml