apiVersion: v1
kind: Namespace
metadata:
  name: heimdall
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg
  namespace: heimdall
spec:
  dnsNames:
    - echo-app
    - echo-app.default
    - echo-app.default.svc
    - echo-app.default.svc.cluster.local
    - echo-app.local
  ipAddresses:
    - 172.18.255.200
  secretName: eg-tls
  issuerRef:
    name: demo-ca-issuer
    kind: ClusterIssuer
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: heimdall
#  annotations:
#    cert-manager.io/cluster-issuer: demo-ca-issuer
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      hostname: echo-app.local
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: eg-tls
            kind: Secret