// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package secrets

import (
	"context"

	"github.com/dadrus/heimdall/internal/secrets/source"
	"github.com/dadrus/heimdall/internal/secrets/types"
	mock "github.com/stretchr/testify/mock"
)

// NewSecretSourceMock creates a new instance of SecretSourceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretSourceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretSourceMock {
	mock := &SecretSourceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SecretSourceMock is an autogenerated mock type for the secretSource type
type SecretSourceMock struct {
	mock.Mock
}

type SecretSourceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretSourceMock) EXPECT() *SecretSourceMock_Expecter {
	return &SecretSourceMock_Expecter{mock: &_m.Mock}
}

// AccessFromRulesAllowed provides a mock function for the type SecretSourceMock
func (_mock *SecretSourceMock) AccessFromRulesAllowed() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AccessFromRulesAllowed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// SecretSourceMock_AccessFromRulesAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessFromRulesAllowed'
type SecretSourceMock_AccessFromRulesAllowed_Call struct {
	*mock.Call
}

// AccessFromRulesAllowed is a helper method to define mock.On call
func (_e *SecretSourceMock_Expecter) AccessFromRulesAllowed() *SecretSourceMock_AccessFromRulesAllowed_Call {
	return &SecretSourceMock_AccessFromRulesAllowed_Call{Call: _e.mock.On("AccessFromRulesAllowed")}
}

func (_c *SecretSourceMock_AccessFromRulesAllowed_Call) Run(run func()) *SecretSourceMock_AccessFromRulesAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SecretSourceMock_AccessFromRulesAllowed_Call) Return(b bool) *SecretSourceMock_AccessFromRulesAllowed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *SecretSourceMock_AccessFromRulesAllowed_Call) RunAndReturn(run func() bool) *SecretSourceMock_AccessFromRulesAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// Dependencies provides a mock function for the type SecretSourceMock
func (_mock *SecretSourceMock) Dependencies() []types.SecretRef {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dependencies")
	}

	var r0 []types.SecretRef
	if returnFunc, ok := ret.Get(0).(func() []types.SecretRef); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.SecretRef)
		}
	}
	return r0
}

// SecretSourceMock_Dependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dependencies'
type SecretSourceMock_Dependencies_Call struct {
	*mock.Call
}

// Dependencies is a helper method to define mock.On call
func (_e *SecretSourceMock_Expecter) Dependencies() *SecretSourceMock_Dependencies_Call {
	return &SecretSourceMock_Dependencies_Call{Call: _e.mock.On("Dependencies")}
}

func (_c *SecretSourceMock_Dependencies_Call) Run(run func()) *SecretSourceMock_Dependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SecretSourceMock_Dependencies_Call) Return(secretRefs []types.SecretRef) *SecretSourceMock_Dependencies_Call {
	_c.Call.Return(secretRefs)
	return _c
}

func (_c *SecretSourceMock_Dependencies_Call) RunAndReturn(run func() []types.SecretRef) *SecretSourceMock_Dependencies_Call {
	_c.Call.Return(run)
	return _c
}

// DependsOn provides a mock function for the type SecretSourceMock
func (_mock *SecretSourceMock) DependsOn(evt source.Event) bool {
	ret := _mock.Called(evt)

	if len(ret) == 0 {
		panic("no return value specified for DependsOn")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(source.Event) bool); ok {
		r0 = returnFunc(evt)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// SecretSourceMock_DependsOn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DependsOn'
type SecretSourceMock_DependsOn_Call struct {
	*mock.Call
}

// DependsOn is a helper method to define mock.On call
//   - evt source.Event
func (_e *SecretSourceMock_Expecter) DependsOn(evt interface{}) *SecretSourceMock_DependsOn_Call {
	return &SecretSourceMock_DependsOn_Call{Call: _e.mock.On("DependsOn", evt)}
}

func (_c *SecretSourceMock_DependsOn_Call) Run(run func(evt source.Event)) *SecretSourceMock_DependsOn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 source.Event
		if args[0] != nil {
			arg0 = args[0].(source.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SecretSourceMock_DependsOn_Call) Return(b bool) *SecretSourceMock_DependsOn_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *SecretSourceMock_DependsOn_Call) RunAndReturn(run func(evt source.Event) bool) *SecretSourceMock_DependsOn_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentials provides a mock function for the type SecretSourceMock
func (_mock *SecretSourceMock) GetCredentials(ctx context.Context, selector types.Selector) (types.Credentials, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentials")
	}

	var r0 types.Credentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Selector) (types.Credentials, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Selector) types.Credentials); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Credentials)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Selector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretSourceMock_GetCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentials'
type SecretSourceMock_GetCredentials_Call struct {
	*mock.Call
}

// GetCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - selector types.Selector
func (_e *SecretSourceMock_Expecter) GetCredentials(ctx interface{}, selector interface{}) *SecretSourceMock_GetCredentials_Call {
	return &SecretSourceMock_GetCredentials_Call{Call: _e.mock.On("GetCredentials", ctx, selector)}
}

func (_c *SecretSourceMock_GetCredentials_Call) Run(run func(ctx context.Context, selector types.Selector)) *SecretSourceMock_GetCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Selector
		if args[1] != nil {
			arg1 = args[1].(types.Selector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretSourceMock_GetCredentials_Call) Return(credentials types.Credentials, err error) *SecretSourceMock_GetCredentials_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *SecretSourceMock_GetCredentials_Call) RunAndReturn(run func(ctx context.Context, selector types.Selector) (types.Credentials, error)) *SecretSourceMock_GetCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function for the type SecretSourceMock
func (_mock *SecretSourceMock) GetSecret(ctx context.Context, selector types.Selector) (types.Secret, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 types.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Selector) (types.Secret, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Selector) types.Secret); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Selector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretSourceMock_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type SecretSourceMock_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - selector types.Selector
func (_e *SecretSourceMock_Expecter) GetSecret(ctx interface{}, selector interface{}) *SecretSourceMock_GetSecret_Call {
	return &SecretSourceMock_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, selector)}
}

func (_c *SecretSourceMock_GetSecret_Call) Run(run func(ctx context.Context, selector types.Selector)) *SecretSourceMock_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Selector
		if args[1] != nil {
			arg1 = args[1].(types.Selector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretSourceMock_GetSecret_Call) Return(secret types.Secret, err error) *SecretSourceMock_GetSecret_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *SecretSourceMock_GetSecret_Call) RunAndReturn(run func(ctx context.Context, selector types.Selector) (types.Secret, error)) *SecretSourceMock_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretSet provides a mock function for the type SecretSourceMock
func (_mock *SecretSourceMock) GetSecretSet(ctx context.Context, selector types.Selector) ([]types.Secret, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretSet")
	}

	var r0 []types.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Selector) ([]types.Secret, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Selector) []types.Secret); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Selector) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretSourceMock_GetSecretSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretSet'
type SecretSourceMock_GetSecretSet_Call struct {
	*mock.Call
}

// GetSecretSet is a helper method to define mock.On call
//   - ctx context.Context
//   - selector types.Selector
func (_e *SecretSourceMock_Expecter) GetSecretSet(ctx interface{}, selector interface{}) *SecretSourceMock_GetSecretSet_Call {
	return &SecretSourceMock_GetSecretSet_Call{Call: _e.mock.On("GetSecretSet", ctx, selector)}
}

func (_c *SecretSourceMock_GetSecretSet_Call) Run(run func(ctx context.Context, selector types.Selector)) *SecretSourceMock_GetSecretSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Selector
		if args[1] != nil {
			arg1 = args[1].(types.Selector)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretSourceMock_GetSecretSet_Call) Return(secrets []types.Secret, err error) *SecretSourceMock_GetSecretSet_Call {
	_c.Call.Return(secrets, err)
	return _c
}

func (_c *SecretSourceMock_GetSecretSet_Call) RunAndReturn(run func(ctx context.Context, selector types.Selector) ([]types.Secret, error)) *SecretSourceMock_GetSecretSet_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type SecretSourceMock
func (_mock *SecretSourceMock) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SecretSourceMock_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type SecretSourceMock_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *SecretSourceMock_Expecter) Name() *SecretSourceMock_Name_Call {
	return &SecretSourceMock_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *SecretSourceMock_Name_Call) Run(run func()) *SecretSourceMock_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SecretSourceMock_Name_Call) Return(s string) *SecretSourceMock_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *SecretSourceMock_Name_Call) RunAndReturn(run func() string) *SecretSourceMock_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type SecretSourceMock
func (_mock *SecretSourceMock) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SecretSourceMock_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type SecretSourceMock_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SecretSourceMock_Expecter) Start(ctx interface{}) *SecretSourceMock_Start_Call {
	return &SecretSourceMock_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *SecretSourceMock_Start_Call) Run(run func(ctx context.Context)) *SecretSourceMock_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SecretSourceMock_Start_Call) Return(err error) *SecretSourceMock_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SecretSourceMock_Start_Call) RunAndReturn(run func(ctx context.Context) error) *SecretSourceMock_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type SecretSourceMock
func (_mock *SecretSourceMock) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SecretSourceMock_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type SecretSourceMock_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SecretSourceMock_Expecter) Stop(ctx interface{}) *SecretSourceMock_Stop_Call {
	return &SecretSourceMock_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *SecretSourceMock_Stop_Call) Run(run func(ctx context.Context)) *SecretSourceMock_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SecretSourceMock_Stop_Call) Return(err error) *SecretSourceMock_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SecretSourceMock_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *SecretSourceMock_Stop_Call {
	_c.Call.Return(run)
	return _c
}
