// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dadrus/heimdall/internal/heimdall"
	"github.com/dadrus/heimdall/internal/rules/rule"
	mock "github.com/stretchr/testify/mock"
)

// NewExecutorMock creates a new instance of ExecutorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutorMock {
	mock := &ExecutorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExecutorMock is an autogenerated mock type for the Executor type
type ExecutorMock struct {
	mock.Mock
}

type ExecutorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ExecutorMock) EXPECT() *ExecutorMock_Expecter {
	return &ExecutorMock_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type ExecutorMock
func (_mock *ExecutorMock) Execute(ctx heimdall.RequestContext) (rule.Backend, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 rule.Backend
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(heimdall.RequestContext) (rule.Backend, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(heimdall.RequestContext) rule.Backend); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rule.Backend)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(heimdall.RequestContext) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ExecutorMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ExecutorMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx heimdall.RequestContext
func (_e *ExecutorMock_Expecter) Execute(ctx interface{}) *ExecutorMock_Execute_Call {
	return &ExecutorMock_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *ExecutorMock_Execute_Call) Run(run func(ctx heimdall.RequestContext)) *ExecutorMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 heimdall.RequestContext
		if args[0] != nil {
			arg0 = args[0].(heimdall.RequestContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ExecutorMock_Execute_Call) Return(backend rule.Backend, err error) *ExecutorMock_Execute_Call {
	_c.Call.Return(backend, err)
	return _c
}

func (_c *ExecutorMock_Execute_Call) RunAndReturn(run func(ctx heimdall.RequestContext) (rule.Backend, error)) *ExecutorMock_Execute_Call {
	_c.Call.Return(run)
	return _c
}
