// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	heimdall "github.com/dadrus/heimdall/internal/heimdall"
	mock "github.com/stretchr/testify/mock"

	rule "github.com/dadrus/heimdall/internal/rules/rule"
)

// ExecutorMock is an autogenerated mock type for the Executor type
type ExecutorMock struct {
	mock.Mock
}

type ExecutorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ExecutorMock) EXPECT() *ExecutorMock_Expecter {
	return &ExecutorMock_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *ExecutorMock) Execute(ctx heimdall.RequestContext) (rule.Backend, error) {
	ret := _m.Called(ctx)

	var r0 rule.Backend
	var r1 error
	if rf, ok := ret.Get(0).(func(heimdall.RequestContext) (rule.Backend, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(heimdall.RequestContext) rule.Backend); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rule.Backend)
		}
	}

	if rf, ok := ret.Get(1).(func(heimdall.RequestContext) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecutorMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ExecutorMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx heimdall.RequestContext
func (_e *ExecutorMock_Expecter) Execute(ctx interface{}) *ExecutorMock_Execute_Call {
	return &ExecutorMock_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *ExecutorMock_Execute_Call) Run(run func(ctx heimdall.RequestContext)) *ExecutorMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(heimdall.RequestContext))
	})
	return _c
}

func (_c *ExecutorMock_Execute_Call) Return(_a0 rule.Backend, _a1 error) *ExecutorMock_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExecutorMock_Execute_Call) RunAndReturn(run func(heimdall.RequestContext) (rule.Backend, error)) *ExecutorMock_Execute_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewExecutorMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewExecutorMock creates a new instance of ExecutorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExecutorMock(t mockConstructorTestingTNewExecutorMock) *ExecutorMock {
	mock := &ExecutorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
