// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dadrus/heimdall/internal/rules/api/v1beta1"
	mock "github.com/stretchr/testify/mock"
)

// NewRuleSetProcessorMock creates a new instance of RuleSetProcessorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRuleSetProcessorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RuleSetProcessorMock {
	mock := &RuleSetProcessorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RuleSetProcessorMock is an autogenerated mock type for the SetProcessor type
type RuleSetProcessorMock struct {
	mock.Mock
}

type RuleSetProcessorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RuleSetProcessorMock) EXPECT() *RuleSetProcessorMock_Expecter {
	return &RuleSetProcessorMock_Expecter{mock: &_m.Mock}
}

// OnCreated provides a mock function for the type RuleSetProcessorMock
func (_mock *RuleSetProcessorMock) OnCreated(ctx context.Context, ruleSet *v1beta1.RuleSet) error {
	ret := _mock.Called(ctx, ruleSet)

	if len(ret) == 0 {
		panic("no return value specified for OnCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1beta1.RuleSet) error); ok {
		r0 = returnFunc(ctx, ruleSet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RuleSetProcessorMock_OnCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnCreated'
type RuleSetProcessorMock_OnCreated_Call struct {
	*mock.Call
}

// OnCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleSet *v1beta1.RuleSet
func (_e *RuleSetProcessorMock_Expecter) OnCreated(ctx interface{}, ruleSet interface{}) *RuleSetProcessorMock_OnCreated_Call {
	return &RuleSetProcessorMock_OnCreated_Call{Call: _e.mock.On("OnCreated", ctx, ruleSet)}
}

func (_c *RuleSetProcessorMock_OnCreated_Call) Run(run func(ctx context.Context, ruleSet *v1beta1.RuleSet)) *RuleSetProcessorMock_OnCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1beta1.RuleSet
		if args[1] != nil {
			arg1 = args[1].(*v1beta1.RuleSet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RuleSetProcessorMock_OnCreated_Call) Return(err error) *RuleSetProcessorMock_OnCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RuleSetProcessorMock_OnCreated_Call) RunAndReturn(run func(ctx context.Context, ruleSet *v1beta1.RuleSet) error) *RuleSetProcessorMock_OnCreated_Call {
	_c.Call.Return(run)
	return _c
}

// OnDeleted provides a mock function for the type RuleSetProcessorMock
func (_mock *RuleSetProcessorMock) OnDeleted(ctx context.Context, ruleSet *v1beta1.RuleSet) error {
	ret := _mock.Called(ctx, ruleSet)

	if len(ret) == 0 {
		panic("no return value specified for OnDeleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1beta1.RuleSet) error); ok {
		r0 = returnFunc(ctx, ruleSet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RuleSetProcessorMock_OnDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnDeleted'
type RuleSetProcessorMock_OnDeleted_Call struct {
	*mock.Call
}

// OnDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleSet *v1beta1.RuleSet
func (_e *RuleSetProcessorMock_Expecter) OnDeleted(ctx interface{}, ruleSet interface{}) *RuleSetProcessorMock_OnDeleted_Call {
	return &RuleSetProcessorMock_OnDeleted_Call{Call: _e.mock.On("OnDeleted", ctx, ruleSet)}
}

func (_c *RuleSetProcessorMock_OnDeleted_Call) Run(run func(ctx context.Context, ruleSet *v1beta1.RuleSet)) *RuleSetProcessorMock_OnDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1beta1.RuleSet
		if args[1] != nil {
			arg1 = args[1].(*v1beta1.RuleSet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RuleSetProcessorMock_OnDeleted_Call) Return(err error) *RuleSetProcessorMock_OnDeleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RuleSetProcessorMock_OnDeleted_Call) RunAndReturn(run func(ctx context.Context, ruleSet *v1beta1.RuleSet) error) *RuleSetProcessorMock_OnDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// OnUpdated provides a mock function for the type RuleSetProcessorMock
func (_mock *RuleSetProcessorMock) OnUpdated(ctx context.Context, ruleSet *v1beta1.RuleSet) error {
	ret := _mock.Called(ctx, ruleSet)

	if len(ret) == 0 {
		panic("no return value specified for OnUpdated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1beta1.RuleSet) error); ok {
		r0 = returnFunc(ctx, ruleSet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RuleSetProcessorMock_OnUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnUpdated'
type RuleSetProcessorMock_OnUpdated_Call struct {
	*mock.Call
}

// OnUpdated is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleSet *v1beta1.RuleSet
func (_e *RuleSetProcessorMock_Expecter) OnUpdated(ctx interface{}, ruleSet interface{}) *RuleSetProcessorMock_OnUpdated_Call {
	return &RuleSetProcessorMock_OnUpdated_Call{Call: _e.mock.On("OnUpdated", ctx, ruleSet)}
}

func (_c *RuleSetProcessorMock_OnUpdated_Call) Run(run func(ctx context.Context, ruleSet *v1beta1.RuleSet)) *RuleSetProcessorMock_OnUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1beta1.RuleSet
		if args[1] != nil {
			arg1 = args[1].(*v1beta1.RuleSet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RuleSetProcessorMock_OnUpdated_Call) Return(err error) *RuleSetProcessorMock_OnUpdated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RuleSetProcessorMock_OnUpdated_Call) RunAndReturn(run func(ctx context.Context, ruleSet *v1beta1.RuleSet) error) *RuleSetProcessorMock_OnUpdated_Call {
	_c.Call.Return(run)
	return _c
}
