// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dadrus/heimdall/internal/keyregistry"
	"github.com/go-jose/go-jose/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewRegistryMock creates a new instance of RegistryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistryMock {
	mock := &RegistryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RegistryMock is an autogenerated mock type for the Registry type
type RegistryMock struct {
	mock.Mock
}

type RegistryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RegistryMock) EXPECT() *RegistryMock_Expecter {
	return &RegistryMock_Expecter{mock: &_m.Mock}
}

// Keys provides a mock function for the type RegistryMock
func (_mock *RegistryMock) Keys() []jose.JSONWebKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Keys")
	}

	var r0 []jose.JSONWebKey
	if returnFunc, ok := ret.Get(0).(func() []jose.JSONWebKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]jose.JSONWebKey)
		}
	}
	return r0
}

// RegistryMock_Keys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keys'
type RegistryMock_Keys_Call struct {
	*mock.Call
}

// Keys is a helper method to define mock.On call
func (_e *RegistryMock_Expecter) Keys() *RegistryMock_Keys_Call {
	return &RegistryMock_Keys_Call{Call: _e.mock.On("Keys")}
}

func (_c *RegistryMock_Keys_Call) Run(run func()) *RegistryMock_Keys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RegistryMock_Keys_Call) Return(jSONWebKeys []jose.JSONWebKey) *RegistryMock_Keys_Call {
	_c.Call.Return(jSONWebKeys)
	return _c
}

func (_c *RegistryMock_Keys_Call) RunAndReturn(run func() []jose.JSONWebKey) *RegistryMock_Keys_Call {
	_c.Call.Return(run)
	return _c
}

// Notify provides a mock function for the type RegistryMock
func (_mock *RegistryMock) Notify(ki keyregistry.KeyInfo) {
	_mock.Called(ki)
	return
}

// RegistryMock_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type RegistryMock_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - ki keyregistry.KeyInfo
func (_e *RegistryMock_Expecter) Notify(ki interface{}) *RegistryMock_Notify_Call {
	return &RegistryMock_Notify_Call{Call: _e.mock.On("Notify", ki)}
}

func (_c *RegistryMock_Notify_Call) Run(run func(ki keyregistry.KeyInfo)) *RegistryMock_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 keyregistry.KeyInfo
		if args[0] != nil {
			arg0 = args[0].(keyregistry.KeyInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RegistryMock_Notify_Call) Return() *RegistryMock_Notify_Call {
	_c.Call.Return()
	return _c
}

func (_c *RegistryMock_Notify_Call) RunAndReturn(run func(ki keyregistry.KeyInfo)) *RegistryMock_Notify_Call {
	_c.Run(run)
	return _c
}
