apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cacerts
spec:
  sources:
    - secret:
        name: demo-ca
        key: ca.crt
  target:
    configMap:
      key: ca.crt
    secret:
      key: ca.crt