apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rulesets.heimdall.dadrus.github.com
spec:
  group: heimdall.dadrus.github.com
  scope: Namespaced
  names:
    kind: RuleSet
    plural: rulesets
    singular: ruleset
    listKind: RuleSetList
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: array
              items:
                type: object
                properties:
                  id:
                    description: The identifier of the rule
                    type: string
                  url:
                    description: The url to match
                    type: string
                  matching_strategy:
                    description: Strategy to match the url. Can either be regex or glob. defaults to glob
                    type: string
                    default: glob
                    enum:
                      - regex
                      - glob
                  upstream:
                    description: Schema, host and port of the upstream service to forward the request to. Required only if heimdall is used in proxy operation mode.
                    type: string
                  methods:
                    description: The allowed HTTP methods
                    type: array
                    items:
                      type: string
                      enum:
                        - ALL
                        - CONNECT
                        - DELETE
                        - GET
                        - HEAD
                        - OPTIONS
                        - PATCH
                        - POST
                        - PUT
                        - TRACE
                  execute:
                    description: The pipeline mechanisms to execute
                    type: array
                    items:
                      type: object
                  on_error:
                    description: The error pipeline mechanisms.
                    type: array
                    items:
                      type: object



