apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "heimdall.fullname" . }}
  namespace: {{ include "heimdall.namespace" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "heimdall.fullname" . }}
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ruleset-reader
  namespace: {{ include "heimdall.namespace" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
rules:
  - apiGroups: ["heimdall.dadrus.github.com"]
    resources: ["rulesets"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ruleset-reader
  namespace: {{ include "heimdall.namespace" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "heimdall.fullname" . }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ruleset-reader
  apiGroup: rbac.authorization.k8s.io
