name: please-release

on:
  push:
    branches:
      - main
      - release

permissions: {}

jobs:
  create-release:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit
      - name: Please Release
        id: create_release
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.RELEASE_TOKEN }}
          skip-github-pull-request: true
      - name: Please Release PR
        if: steps.create_release.outputs.release_created == false
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-github-release: true
