name: release-please

on:
  push:
    branches:
      - main
      - release

jobs:
  prepare-release:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
      - name: Prepare Release
        id: release_prepare
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.RELEASE_TOKEN }}
