// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	heimdall "github.com/dadrus/heimdall/internal/heimdall"
	mock "github.com/stretchr/testify/mock"

	url "net/url"
)

// ContextMock is an autogenerated mock type for the Context type
type ContextMock struct {
	mock.Mock
}

type ContextMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ContextMock) EXPECT() *ContextMock_Expecter {
	return &ContextMock_Expecter{mock: &_m.Mock}
}

// AddCookieForUpstream provides a mock function with given fields: name, value
func (_m *ContextMock) AddCookieForUpstream(name string, value string) {
	_m.Called(name, value)
}

// ContextMock_AddCookieForUpstream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCookieForUpstream'
type ContextMock_AddCookieForUpstream_Call struct {
	*mock.Call
}

// AddCookieForUpstream is a helper method to define mock.On call
//   - name string
//   - value string
func (_e *ContextMock_Expecter) AddCookieForUpstream(name interface{}, value interface{}) *ContextMock_AddCookieForUpstream_Call {
	return &ContextMock_AddCookieForUpstream_Call{Call: _e.mock.On("AddCookieForUpstream", name, value)}
}

func (_c *ContextMock_AddCookieForUpstream_Call) Run(run func(name string, value string)) *ContextMock_AddCookieForUpstream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ContextMock_AddCookieForUpstream_Call) Return() *ContextMock_AddCookieForUpstream_Call {
	_c.Call.Return()
	return _c
}

func (_c *ContextMock_AddCookieForUpstream_Call) RunAndReturn(run func(string, string)) *ContextMock_AddCookieForUpstream_Call {
	_c.Call.Return(run)
	return _c
}

// AddHeaderForUpstream provides a mock function with given fields: name, value
func (_m *ContextMock) AddHeaderForUpstream(name string, value string) {
	_m.Called(name, value)
}

// ContextMock_AddHeaderForUpstream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHeaderForUpstream'
type ContextMock_AddHeaderForUpstream_Call struct {
	*mock.Call
}

// AddHeaderForUpstream is a helper method to define mock.On call
//   - name string
//   - value string
func (_e *ContextMock_Expecter) AddHeaderForUpstream(name interface{}, value interface{}) *ContextMock_AddHeaderForUpstream_Call {
	return &ContextMock_AddHeaderForUpstream_Call{Call: _e.mock.On("AddHeaderForUpstream", name, value)}
}

func (_c *ContextMock_AddHeaderForUpstream_Call) Run(run func(name string, value string)) *ContextMock_AddHeaderForUpstream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ContextMock_AddHeaderForUpstream_Call) Return() *ContextMock_AddHeaderForUpstream_Call {
	_c.Call.Return()
	return _c
}

func (_c *ContextMock_AddHeaderForUpstream_Call) RunAndReturn(run func(string, string)) *ContextMock_AddHeaderForUpstream_Call {
	_c.Call.Return(run)
	return _c
}

// AppContext provides a mock function with given fields:
func (_m *ContextMock) AppContext() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// ContextMock_AppContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppContext'
type ContextMock_AppContext_Call struct {
	*mock.Call
}

// AppContext is a helper method to define mock.On call
func (_e *ContextMock_Expecter) AppContext() *ContextMock_AppContext_Call {
	return &ContextMock_AppContext_Call{Call: _e.mock.On("AppContext")}
}

func (_c *ContextMock_AppContext_Call) Run(run func()) *ContextMock_AppContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ContextMock_AppContext_Call) Return(_a0 context.Context) *ContextMock_AppContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContextMock_AppContext_Call) RunAndReturn(run func() context.Context) *ContextMock_AppContext_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with given fields: err
func (_m *ContextMock) Error(err error) {
	_m.Called(err)
}

// ContextMock_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type ContextMock_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - err error
func (_e *ContextMock_Expecter) Error(err interface{}) *ContextMock_Error_Call {
	return &ContextMock_Error_Call{Call: _e.mock.On("Error", err)}
}

func (_c *ContextMock_Error_Call) Run(run func(err error)) *ContextMock_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *ContextMock_Error_Call) Return() *ContextMock_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *ContextMock_Error_Call) RunAndReturn(run func(error)) *ContextMock_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Finalize provides a mock function with given fields: targetURL
func (_m *ContextMock) Finalize(targetURL *url.URL) {
	_m.Called(targetURL)
}

// ContextMock_Finalize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finalize'
type ContextMock_Finalize_Call struct {
	*mock.Call
}

// Finalize is a helper method to define mock.On call
//   - targetURL *url.URL
func (_e *ContextMock_Expecter) Finalize(targetURL interface{}) *ContextMock_Finalize_Call {
	return &ContextMock_Finalize_Call{Call: _e.mock.On("Finalize", targetURL)}
}

func (_c *ContextMock_Finalize_Call) Run(run func(targetURL *url.URL)) *ContextMock_Finalize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*url.URL))
	})
	return _c
}

func (_c *ContextMock_Finalize_Call) Return() *ContextMock_Finalize_Call {
	_c.Call.Return()
	return _c
}

func (_c *ContextMock_Finalize_Call) RunAndReturn(run func(*url.URL)) *ContextMock_Finalize_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function with given fields:
func (_m *ContextMock) Request() *heimdall.Request {
	ret := _m.Called()

	var r0 *heimdall.Request
	if rf, ok := ret.Get(0).(func() *heimdall.Request); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*heimdall.Request)
		}
	}

	return r0
}

// ContextMock_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type ContextMock_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
func (_e *ContextMock_Expecter) Request() *ContextMock_Request_Call {
	return &ContextMock_Request_Call{Call: _e.mock.On("Request")}
}

func (_c *ContextMock_Request_Call) Run(run func()) *ContextMock_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ContextMock_Request_Call) Return(_a0 *heimdall.Request) *ContextMock_Request_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContextMock_Request_Call) RunAndReturn(run func() *heimdall.Request) *ContextMock_Request_Call {
	_c.Call.Return(run)
	return _c
}

// SetPipelineError provides a mock function with given fields: err
func (_m *ContextMock) SetPipelineError(err error) {
	_m.Called(err)
}

// ContextMock_SetPipelineError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPipelineError'
type ContextMock_SetPipelineError_Call struct {
	*mock.Call
}

// SetPipelineError is a helper method to define mock.On call
//   - err error
func (_e *ContextMock_Expecter) SetPipelineError(err interface{}) *ContextMock_SetPipelineError_Call {
	return &ContextMock_SetPipelineError_Call{Call: _e.mock.On("SetPipelineError", err)}
}

func (_c *ContextMock_SetPipelineError_Call) Run(run func(err error)) *ContextMock_SetPipelineError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *ContextMock_SetPipelineError_Call) Return() *ContextMock_SetPipelineError_Call {
	_c.Call.Return()
	return _c
}

func (_c *ContextMock_SetPipelineError_Call) RunAndReturn(run func(error)) *ContextMock_SetPipelineError_Call {
	_c.Call.Return(run)
	return _c
}

// Signer provides a mock function with given fields:
func (_m *ContextMock) Signer() heimdall.JWTSigner {
	ret := _m.Called()

	var r0 heimdall.JWTSigner
	if rf, ok := ret.Get(0).(func() heimdall.JWTSigner); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(heimdall.JWTSigner)
		}
	}

	return r0
}

// ContextMock_Signer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signer'
type ContextMock_Signer_Call struct {
	*mock.Call
}

// Signer is a helper method to define mock.On call
func (_e *ContextMock_Expecter) Signer() *ContextMock_Signer_Call {
	return &ContextMock_Signer_Call{Call: _e.mock.On("Signer")}
}

func (_c *ContextMock_Signer_Call) Run(run func()) *ContextMock_Signer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ContextMock_Signer_Call) Return(_a0 heimdall.JWTSigner) *ContextMock_Signer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContextMock_Signer_Call) RunAndReturn(run func() heimdall.JWTSigner) *ContextMock_Signer_Call {
	_c.Call.Return(run)
	return _c
}

// UpstreamURLRequired provides a mock function with given fields:
func (_m *ContextMock) UpstreamURLRequired() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ContextMock_UpstreamURLRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpstreamURLRequired'
type ContextMock_UpstreamURLRequired_Call struct {
	*mock.Call
}

// UpstreamURLRequired is a helper method to define mock.On call
func (_e *ContextMock_Expecter) UpstreamURLRequired() *ContextMock_UpstreamURLRequired_Call {
	return &ContextMock_UpstreamURLRequired_Call{Call: _e.mock.On("UpstreamURLRequired")}
}

func (_c *ContextMock_UpstreamURLRequired_Call) Run(run func()) *ContextMock_UpstreamURLRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ContextMock_UpstreamURLRequired_Call) Return(_a0 bool) *ContextMock_UpstreamURLRequired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContextMock_UpstreamURLRequired_Call) RunAndReturn(run func() bool) *ContextMock_UpstreamURLRequired_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewContextMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewContextMock creates a new instance of ContextMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewContextMock(t mockConstructorTestingTNewContextMock) *ContextMock {
	mock := &ContextMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
