updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
terminationGracePeriodSeconds: 0
nodeSelector:
  ingress-ready: "true"
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    effect: "NoSchedule"
publishService:
  enabled: false