updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
hostNetwork: true
daemonset.useHostPort: true

terminationGracePeriodSeconds: 0
service:
  type: NodePort
nodeSelector:
  ingress-ready: "true"
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    effect: "NoSchedule"
publishService:
  enabled: false
extraArgs:
  publish-status-address: localhost